added states validate and verify

diff --git a/init/once b/init/once
--- a/init/once
+++ b/init/once
@@ -1482,8 +1482,36 @@ private.state.keycloak.started() {
 }
 
 private.state.db.started() {
-  once.docker.scenario.status pg
+  local onceDbScenario=pg
+  if [ "$ONCE_MODE" = "IN_DOCKER" ]; then
+    onceDbScenario=pgv
+    info.log "using docker.scenario $onceDbScenario"
+  fi 
+
+  once.docker.scenario.status $onceDbScenario
   success.log "once-postgresql is UP"
+}
+
+private.state.db.stopped() {
+  local onceDbScenario=pg
+  if [ "$ONCE_MODE" = "IN_DOCKER" ]; then
+    onceDbScenario=pgv
+    info.log "using docker.scenario $onceDbScenario"
+  fi 
+
+  once.docker.scenario.status $onceDbScenario
+  success.log "once-postgresql is \033[1;31mDOWN\033[0m"
+}
+
+private.state.once.tested() {
+  success.log "ONCE_TESTED=$ONCE_TESTED"
+}
+
+private.state.once.ready() {
+
+  once status
+  once.find
+  success.log "once ready"
 }
 
 function deprectaed.su.finalize.installation()            # prints where the repository has been installed 
@@ -1548,6 +1576,64 @@ function once.bind.docker()
     once.hibernate update
   fi
     RETURN=$1
+}
+
+once.db.bind.docker() 
+{
+  if [ "$ONCE_MODE" = "IN_DOCKER" ]; then
+    warn.log "in docker....binding db to once-postgresql:5432"
+
+    export ONCE_POSTGRES_CONNECTION_STRING=postgresql://root:qazwsx123@once-postgresql:5432/oncestore
+    once.hibernate update
+  fi
+  RETURN=$1
+}
+once.db.bind.local() 
+{
+  if [ "$ONCE_MODE" = "LOCAL" ]; then
+    warn.log "not in docker....binding db to localhost:5433"
+
+    export ONCE_POSTGRES_CONNECTION_STRING=postgresql://root:qazwsx123@localhost:5433/oncestore
+    once.hibernate update
+  fi
+  RETURN=$1
+}
+
+once.db.stop() 
+{
+  local onceDbScenario=pg
+  if [ "$ONCE_MODE" = "IN_DOCKER" ]; then
+    onceDbScenario=pgv
+    info.log "using docker.scenario $onceDbScenario"
+  fi
+  once.docker.scenario.stop $onceDbScenario
+  private.stage db.stopped
+}
+
+once.db.start() 
+{
+  local onceDbScenario=pg
+  if [ "$ONCE_MODE" = "IN_DOCKER" ]; then
+    onceDbScenario=pgv
+    info.log "using docker.scenario $onceDbScenario"
+  fi
+  once.db.create.docker.network
+  once.docker.scenario.start $onceDbScenario
+  private.stage db.started
+}
+
+once.db.create.docker.network()
+{
+  NETWORK_NAME=once-woda-network
+  if [ -z $(docker network ls --filter name=^${NETWORK_NAME}$ --format="{{ .Name }}") ] ; then 
+      echo "${NETWORK_NAME} not exists, creating new..."
+      docker network create ${NETWORK_NAME} ; 
+      echo "${NETWORK_NAME} docker network created."
+      echo
+      docker network connect ${NETWORK_NAME} $(hostname)
+  else
+    echo "Docker Network '${NETWORK_NAME}' Already Exists..."
+  fi  
 }
 
 function once.bind.local() 
@@ -2059,17 +2145,44 @@ once.client()
 
 }
 
-function private.state.privileges.checked()     # checks the administrative rights of the current once.su instance 
+function private.state.privileges()     # 
 {
   success.log "privilidges are: $ONCE_PRIVILEGE"
 }
 
+
+function private.state.privileges.checked()     # 
+{
+  success.log "privilidges are: $ONCE_PRIVILEGE"
+}
+
+function private.state.privileges()     # 
+{
+  error.log "privilidges are: $ONCE_PRIVILEGE"
+}
+
+function private.state.certificates.installed()     # 
+{
+  tree -L 1 $ONCE_DEFAULT_SCENARIO
+  success.log "certificates installed"
+}
+
+
 function private.state.root()                 # populates the environmental variables with root administrative rights 
 {
-    ONCE_PRIVILEGE=root
-    ONCE_REPO_PREFIX=/var/dev
-    
+
+  ONCE_PRIVILEGE=root
+  ONCE_REPO_PREFIX=/var/dev
+
+  local state="privileges.checked"
+  once.state.get $state
+  local stateId=$RESULT
+
+  success.log "privilidges are: $ONCE_PRIVILEGE"
+  if [ "$ONCE_STATE_ID" -lt $stateId ]; then
     private.stage root.installation
+  fi
+    
 }
 
 private.state.root.installation()    # installs the repo as root user
@@ -5322,17 +5435,7 @@ function private.docker.scenario.create.structr()
 function private.docker.scenario.create.pg()
 {
   private.docker.scenario.delete.pg
-
-  NETWORK_NAME=once-woda-network
-  if [ -z $(docker network ls --filter name=^${NETWORK_NAME}$ --format="{{ .Name }}") ] ; then 
-      echo "${NETWORK_NAME} not exists, creating new..."
-      docker network create ${NETWORK_NAME} ; 
-      echo "${NETWORK_NAME} docker network created."
-      echo
-      docker network connect ${NETWORK_NAME} $(hostname)
-  else
-    echo "Docker Network '${NETWORK_NAME}' Already Exists..."
-  fi
+  once.db.create.docker.network
 
     echo "Creating postgresql.env file"
     {
@@ -6099,9 +6202,115 @@ once.states.list()      # lists states that are left after current state and all
 
 }
 
+once.states.verify()      # lists states that are left after current state and all with: once states.list all
+{
+  if [ -z "$1" ]; then
+  important.log "ONCE_STATES has ${#ONCE_STATES[@]} states.
+  current state:
+  "
+  once.state.get log
+  echo " "
+  fi
+  let i=0
+  for index in "${!ONCE_STATES[@]}"; do
+    debug.log looping ${ONCE_STATES[$index]}  at $index loop $i
+    if [ "$ONCE_STATE_ID" -ge "$index" ] || [ "$1" = "all" ]; then
+      if private.isNumber ${ONCE_STATES[$index]}; then
+        debug.log "skipping ${ONCE_STATES[$index]}"
+      else 
+        info.log "ONCE_STATES[$index]=${ONCE_STATES[$index]}"
+
+        local state=${ONCE_STATES[$index]}
+        if this.functionExists once.check.$state; then
+          success.log "once.check.$state exists"
+        else
+          error.log "once.check.$state is missing"
+        fi
+
+      fi
+    fi
+    let i++
+  done
+
+  echo " "
+  let i=0
+  for index in "${!ONCE_STATES[@]}"; do
+    debug.log looping ${ONCE_STATES[$index]}  at $index loop $i
+    if [ "$ONCE_STATE_ID" -ge "$index" ] || [ "$1" = "all" ]; then
+      if private.isNumber ${ONCE_STATES[$index]}; then
+        debug.log "skipping ${ONCE_STATES[$index]}"
+      else 
+        info.log "ONCE_STATES[$index]=${ONCE_STATES[$index]}"
+
+        local state=${ONCE_STATES[$index]}
+
+        if this.functionExists private.state.$state; then
+          success.log "private.state.$state exists"
+        else
+          error.log "private.state.$state is missing"
+        fi
+      fi
+    fi
+    let i++
+  done  
+  #declare -ax
+
+}
+
+
+once.states.validate()      # lists states that are left after current state and all with: once states.list all
+{
+  if [ -z "$1" ]; then
+  important.log "ONCE_STATES has ${#ONCE_STATES[@]} states.
+  current state:
+  "
+  once.state.get log
+  echo " "
+  fi
+  let i=0
+  for index in "${!ONCE_STATES[@]}"; do
+    debug.log looping ${ONCE_STATES[$index]}  at $index loop $i
+    if [ "$ONCE_STATE_ID" -ge "$index" ] || [ "$1" = "all" ]; then
+      if private.isNumber ${ONCE_STATES[$index]}; then
+        debug.log "skipping ${ONCE_STATES[$index]}"
+      else 
+        info.log "ONCE_STATES[$index]=${ONCE_STATES[$index]}"
+
+        local state=${ONCE_STATES[$index]}
+        if this.functionExists once.check.$state; then
+          success.log "once.check.$state exists...calling it"
+          if once.check.$state; then
+            success.log "once.check.$state PASSED"
+          else
+            error.log "once.check.$state FAILED"
+          fi
+        else
+          error.log "once.check.$state is missing"
+        fi
+
+      fi
+      console.log "==========================================================================="
+    fi
+    let i++
+  done
+}
+
+
+
 once.states.update()
 {
   once.states update
+}
+
+once.check.not.installed() {
+  warn.log "This check is only for completion"
+  if [ -f /root/init/once ]; then
+    success.log "once is downloaded"
+    important.log "the following error message is by intention since once is installed"
+  else
+    error.log "once is not correctly initialized"
+  fi
+  return 1
 }
 
 once.check.initialized() {
@@ -6170,18 +6379,23 @@ once.check.privileges()     # checks the administrative rights of the current on
       [ -n "$ONCE_SCENARIO" ]
       then
         check=0
+        info.log "privileges.checked $ONCE_STATE_ID"
         if [ "$ONCE_STATE_ID" -lt $stateId ]; then
+          info.log "privileges.checked staging"
           private.stage $ONCE_PRIVILEGE
         else
           private.state.$ONCE_PRIVILEGE
         fi
   else
-    if [ "$USERHOME" != "/root" ]; then
-      private.stage state.user
-    else
-      private.stage state.root
-    fi
-    check=0
+    info.log "privileges.checked NO $ONCE_STATE_ID lt $stateId"
+
+      if [ "$USERHOME" != "/root" ]; then
+        private.stage state.user
+      else
+        private.stage state.root
+      fi
+
+      check=0
   fi
   return $check
 }
@@ -6482,10 +6696,52 @@ once.check.db.started()
   once.state.get $state
   local stateId=$RESULT
 
+  local onceDbScenario=pg
+  if [ "$ONCE_MODE" = "IN_DOCKER" ]; then
+    info.log "using docker.scenario pgv"
+    onceDbScenario=pgv
+    once.db.bind.docker
+  fi 
 
-  if once.docker.scenario.status pg 
+
+  if once.docker.scenario.status $onceDbScenario 
       then
-        info.log "check $state succeded"
+        info.log "check $state succeded for $onceDbScenario"
+        check=0
+        if [ "$ONCE_STATE_ID" -lt $stateId ]; then
+          private.stage $state
+        else
+          private.state.$state
+        fi
+  else
+    info.log "check $state failed for $onceDbScenario"
+    once.docker.scenario.create $onceDbScenario
+    if [ "$ONCE_MODE" = "IN_DOCKER" ]; then
+      warn.log "binding db to docker scenario $onceDbScenario"
+      once.db.bind.docker
+    else
+      warn.log "binding db to localhost"
+      once.db.bind.local
+    fi 
+    private.stage $state
+  fi
+  return $check
+}
+
+
+once.check.once.tested()
+{
+  local check=1
+  if ! once.requires.state docker.installed; then
+    return $check
+  fi
+  
+  local state="once.tested"
+  once.state.get $state
+  local stateId=$RESULT
+
+  if [ "$ONCE_TESTED" = "true" ] 
+      then
         check=0
         if [ "$ONCE_STATE_ID" -lt $stateId ]; then
           private.stage $state
@@ -6494,11 +6750,40 @@ once.check.db.started()
         fi
   else
     info.log "check $state failed"
-    once.docker.scenario.create pg
+    once.test
+    ONCE_TESTED="true"
     private.stage $state
   fi
   return $check
 }
+
+once.check.once.ready()
+{
+  local check=1
+  if ! once.requires.state once.tested; then
+    return $check
+  fi
+  
+  local state="once.ready"
+  once.state.get $state
+  local stateId=$RESULT
+
+  if [ "$ONCE_TESTED" = "true" ] 
+      then
+        check=0
+        if [ "$ONCE_STATE_ID" -lt $stateId ]; then
+          private.stage $state
+        else
+          private.state.$state
+        fi
+  else
+    info.log "check $state failed"
+    once.find
+    private.stage $state
+  fi
+  return $check
+}
+
 
 once.stage() 
 {
