version: 2021-12-08 13:42 tested till state root.installed

diff --git a/init/once b/init/once
--- a/init/once
+++ b/init/once
@@ -11,7 +11,7 @@ set -T
 
 once.version()              # prints out the hard coded version tag of $This | to update the script use e.g. once update here http://192.168.178.49:8080
 {
- console.log "$0 version: 2021-12-06 11:12 eamd free, untested"
+ console.log "$0 version: 2021-12-08 13:42 tested till state root.installed"
 }
 
 if [ -z "$USERHOME" ]; then
@@ -1404,15 +1404,7 @@ function once.su.check.installation()   # checks for a once.su installation in g
       warn.log "cannot initialize ssh without minimum state initialized"
       return 1
     fi
-    checkAndFix "exists $ONCE_REPO_PREFIX" "-d" "$ONCE_REPO_PREFIX" "once.path.create $ONCE_REPO_PREFIX"
 
-    #once.su.pm
-    #checkAndFix "make once alias $(which $0)" -L "$(dirname $(which $0))/once" "ln -s $(which $0) $(dirname $(which $0))/once" 
-    once.cmd wget
-    once.cmd curl
-    once.cmd tree
-    once.cmd vim
-    once.cmd git
     #once.cmd eamd
 
     source $OOSH_DIR/user
@@ -1425,12 +1417,16 @@ function once.su.check.installation()   # checks for a once.su installation in g
 
 
     private.stage root.ssh.dev
-
     once.repo.init
   fi
 
-  
   private.stage root.repo.installed
+  
+  once.su.finalize.installation
+
+
+  once.su.docker.install
+  private.stage docker.installed
 }
 
 private.state.root.ssh.dev() {
@@ -1463,17 +1459,17 @@ private.state.initialized() {
 
 }
 
-function private.state.installed()            # prints where the repository has been installed 
+function deprectaed.su.finalize.installation()            # prints where the repository has been installed 
 {
 
   #once.cmd nslookup dnsutils
   #once.cmd telnet inetutils-telnet
   export DEBIAN_FRONTEND=noninteractive
-  apt install -y dnsutils
-  apt install -y inetutils-telnet
-  apt install -y inetutils-ping
+  once.cmd dnsutils
+  once.cmd inetutils-telnet
+  once.cmd inetutils-ping
 
-  once.docker.install
+  once.su.docker.install
   once.cmd npm
 
   console.log "Repository is installed at: $ONCE_REPO_PREFIX/$ONCE_REPO_NAME"
@@ -1484,23 +1480,25 @@ function private.state.installed()            # prints where the repository has 
   #deprecated.docker.postgresql.createdc
   #deprecated.docker.postgresql.start
 
-  apt-get install sudo
+  once.cmd sudo
   #once.user.developer
   #chown developer:dev /var/run
   #chown developer:dev /var/run/docker.sock
 
   #docker network connect once-postgresql $HOSTNAME
 
-  once.bind.docker
+  #once.bind.docker
   #cp $ONCE_REPO_PREFIX/EAMD.ucp/Components/com/ceruleanCircle/EAM/1_infrastructure/NewUserStuff/scripts/templates/.bashrc ~/.bashrc
   #once.user.rc.fix
-  once.completion.install
+  #once.completion.install
 
   #set password for developer with
   # root> passwd developer (default is dev)
   once.status
 
   unset ONCE_TMP_DURING_INSTALL
+
+  private.stage root.installed
 
   console.log "Once is installed and ready for: once start    ....now testing"
   #once.deprecated.stage test
@@ -1930,13 +1928,13 @@ once.state()                # lists the current state of the once server and the
 
 
 
-once.states()
+once.states()               # initiatlizes the once states and forces to update them with: once states update
 {
   declare -xag ONCE_STATES='(\
   [0]="not.installed" \
   [1]="initialized" \
   [2]="domain.set" \
-  [3]="check.privileges" \
+  [3]="privileges" \
   [4]="privileges.checked" \
   [5]=11 \
   [11]="user" \
@@ -1951,28 +1949,34 @@ once.states()
   [22]="root.installation" \
   [23]="root.ssh.dev" \
   [24]="root.ssh.initialized" \
-  [25]="root.not.installed" \
-  [26]="root.repo.installed" \
-  [27]="root.installed" \
-  [28]=30 \
-  [30]="scenario.updated.to.domain" \
-  [31]="scenario.updated.to.domain" \
-  [32]=40 \
-  [40]="docker.installed" \
-  [41]="nginx.started" \
-  [42]="certbot.started" \
-  [43]="keycloak.started" \
-  [44]="db.started" \
-  [45]="once.tested" \
-  [46]="once.ready" \
-  [47]="once.started" \
-  [48]="once.stopped" \
-  [49]="db.stopped" \
-  [50]=60
-  [60]="all.stopped" \
-  [61]="all.uninstalled" \
-  [62]=46
+  [25]="root.repo.installed" \
+  [26]="root.installed" \
+  [27]=40 \
+  [30]="docker.installed" \
+  [31]="nginx.started" \
+  [32]="certbot.started" \
+  [33]="keycloak.started" \
+  [34]=40 \
+  [40]="dev.ca.installed" \
+  [41]="certificates.installed" \
+  [42]=50 \
+  [50]="db.started" \
+  [55]="once.tested" \
+  [56]="once.ready" \
+  [57]="once.started" \
+  [58]="once.stopped" \
+  [59]="db.stopped" \
+  [60]=56
+  [70]="all.stopped" \
+  [71]="all.uninstalled" \
+  [72]=30
   )' 
+
+  if [ "$1" = "update" ]; then
+    shift
+    once.hibernate update
+  fi
+    
   RETURN=$1
 }
 
@@ -2019,22 +2023,9 @@ once.client()
 
 }
 
-function private.state.check.privileges()     # checks the administrative rights of the current once.su instance 
+function private.state.privileges.checked()     # checks the administrative rights of the current once.su instance 
 {
-
-  ONCE_TMP_DURING_INSTALL="true"
-
-  if [ "$USERHOME" != "/root" ]; then
-    private.stage state.user
-  else
-    private.stage state.root
-  fi
-  # once.su.update.variables
-  # once.hibernate update
-
-  # warn.log "check.priviledges done: stage to $ONCE_STATE"
-  # private.stage
-  # warn.log "END of check.priviledges"
+  success.log "privilidges are: $ONCE_PRIVILEGE"
 }
 
 function private.state.root()                 # populates the environmental variables with root administrative rights 
@@ -2045,26 +2036,66 @@ function private.state.root()                 # populates the environmental vari
     private.stage root.installation
 }
 
-function private.state.root.installation()    # installs the repo as root user
+private.state.root.installation()    # installs the repo as root user
 {
-  once.su.check.installation
+  ONCE_TMP_DURING_INSTALL="true"
+  export DEBIAN_FRONTEND=noninteractive
+
+  checkAndFix "exists $ONCE_REPO_PREFIX" "-d" "$ONCE_REPO_PREFIX" "once.path.create $ONCE_REPO_PREFIX"
+
+  #once.su.pm
+  #checkAndFix "make once alias $(which $0)" -L "$(dirname $(which $0))/once" "ln -s $(which $0) $(dirname $(which $0))/once" 
+  once.cmd sudo
+  once.cmd wget
+  once.cmd curl
+  once.cmd tree
+  once.cmd vim
+  once.cmd git
+  once.cmd dnsutils
+  once.cmd inetutils-telnet
+  once.cmd inetutils-ping
+
+  once.cmd npm
+
+
+
+  once.check.root.repo.installed
+
+
+  once.ca
+  once.cu
+  console.log "Once is installed and ready for: once start    ....now testing"
 }
 
 private.state.root.repo.installed() {
+  success.log "Repository installed under $REPO_DIR"
   once.cmd tree
   tree -L 3 $ONCE_REPO_PREFIX
+  once.scenario
 }
+
+private.state.root.installed() {
+  console.log "npm  version:"
+  npm --version
+  console.log "node version:"
+  node --version
+  success.log "node and npm installed under $(which npm)"
+}
+
 
 function private.state.user()                 # populates the environmental variables with user administrative rights 
 {
     ONCE_PRIVILEGE=user
     ONCE_REPO_PREFIX=$USERHOME/dev
-   warn.log "once.state.su.set" 
-once.state.su.set user.installation
+    
     if [ -z "ONCE_SUDO" ]; then 
       ONCE_SUDO="sudo"
     fi
     ONCE_PM="$ONCE_SUDO $ONCE_PM"
+    once.hibernate update
+
+    private.stage user.installation
+
 
 }
 
@@ -2347,25 +2378,25 @@ once.repo.init() {
     git stash -u 
     git pull
   else
-    # if [ -d "$REPO_DIR" ]; then
-    #   # if [ -d "$REPO_DIR.delete" ]; then
-    #   #   rm -Rf $REPO_DIR.delete
-    #   #   once.repo.new.init
-    #   #   return $?
-    #   # fi
-    #   # mv $REPO_DIR $REPO_DIR.delete
-    # fi
+    if [ -d "$REPO_DIR" ]; then
+      if [ -d "$REPO_DIR.delete" ]; then
+        rm -Rf $REPO_DIR.delete
+        once.repo.init
+        return $?
+      fi
+      mv $REPO_DIR $REPO_DIR.delete
+    fi
     once.cmd git
-    #git clone -c core.symlinks=true git@bitbucket.org:donges/eamd.ucp.git EAMD.ucp
+    git clone -c core.symlinks=true git@bitbucket.org:donges/eamd.ucp.git EAMD.ucp
 
     important.log "ONCE_SCENARIO=$ONCE_SCENARIO
 
     once.path.create $ONCE_SCENARIO
     mv $REPO_DIR.delete${ONCE_SCENARIO#"$REPO_DIR"}/EAM
     "
-  LOG_LEVEL=6
+  #LOG_LEVEL=6
     once.path.create $ONCE_SCENARIO
-    mv $REPO_DIR.delete${ONCE_SCENARIO#"$REPO_DIR"}/EAM $ONCE_SCENARIO
+    cp -r $REPO_DIR.delete${ONCE_SCENARIO#"$REPO_DIR"}/EAM $ONCE_SCENARIO
     stop.log "check last echo line"
   fi
   once.cmd tree
@@ -2979,7 +3010,7 @@ deprecated.docker.old(){
 }
 
 
-once.docker.install(){
+once.su.docker.install(){
   if [ -z "$USERNAME" ]; then
     export USERNAME="$(whoami)"
   fi
@@ -5824,17 +5855,28 @@ once.init()                 # forces reinitialisation
 once.state.check()
 {
 
-  console.log "ONCE_STATE=${ONCE_STATES[ONCE_STATE_ID]}"
+  console.log "ONCE_STATE[$ONCE_STATE_ID]=${ONCE_STATES[ONCE_STATE_ID]}"
 }
 
-once.state.get()
+once.state.get()         # gets state id in RESULT and logs it with: once state.get name|id log
 {
   local id="$1"
   shift
   if [ -z "$id" ]; then
    id=$ONCE_STATE_ID
   fi
-  console.log "ONCE_STATES[$id]=${ONCE_STATES[id]}"
+
+  if ! private.isNumber $id; then
+    once.state.find $id
+    id=$RESULT
+  fi
+
+  if [ "$1" = "log" ]; then
+    console.log "ONCE_STATES[$id]=${ONCE_STATES[id]}"
+    shift
+  fi
+  RESULT=$id
+  RETURN=$1
 }
 
 once.state.find()
@@ -5843,7 +5885,7 @@ once.state.find()
   shift
 
   if private.isNumber $stateName; then
-    once.state.get $stateName
+    once.state.get $stateName $1
     return 0
   fi
 
@@ -5903,17 +5945,17 @@ once.requires.state()
     fi
   fi
   if [ "$ONCE_STATE_ID" -ge "$requiredStateId" ]; then
-    debug.log "state check passed: ONCE_STATE_ID $ONCE_STATE_ID >= requiredStateId $requiredStateId "
+    debug.log "state check passed: ONCE_STATE_ID $ONCE_STATE_ID:${ONCE_STATES[$ONCE_STATE_ID]} >= requiredStateId $requiredStateId:${ONCE_STATES[$requiredStateId]} "
     return 0
   else
-    warn.log "state check failed: ONCE_STATE_ID $ONCE_STATE_ID < requiredStateId $requiredStateId"
+    warn.log "state check failed: ONCE_STATE_ID $ONCE_STATE_ID:${ONCE_STATES[$ONCE_STATE_ID]} < requiredStateId $requiredStateId:${ONCE_STATES[$requiredStateId]}"
     once.check.state
     return 1
   fi
   
 }
 
-once.states.list()
+once.states.list()      # lists states that are left after current state and all with: once states.list all
 {
   important.log "ONCE_STATES has ${#ONCE_STATES[@]} states.
   current state:
@@ -5939,9 +5981,200 @@ once.states.list()
 
 once.states.update()
 {
-  once.states
-  once.hibernate update
+  once.states update
 }
+
+once.check.initialized() {
+  local initialized=1
+  if  [ -f $USERHOME/.once ] && 
+      [ -f $ONCE_DEFAULT_SCENARIO/.once ] && 
+      [ -n "$ONCE_REPO_PREFIX" ]
+      then
+        initialized=0
+        if [ "$ONCE_STATE_ID" -lt 1 ]; then
+          private.stage initialized
+        else
+          private.state.initialized
+        fi
+  else
+    warn.log "once not initialized: 
+    use 
+        once init
+
+    or better
+        /root/init/once
+    " 
+  fi
+  info.log initialized: $initialized
+  return $initialized
+}
+
+once.check.domain.set() {
+  local check=1
+
+  if ! once.requires.state initialized; then
+    return $check
+  fi
+
+  if  [ -n "$HOSTNAME" ] && 
+      [ -n "$ONCE_DEFAULT_HOST" ] && 
+      [ ! "$ONCE_SCENARIO" = "/var/dev/EAMD.ucp/Scenarios/localhost" ]
+      then
+        check=0
+        if [ "$ONCE_STATE_ID" -lt 1 ]; then
+          private.stage initialized
+        else
+          private.state.domain.set
+        fi
+  else
+    error.log "domain not yet set!"
+    private.stage initialized
+  fi
+  #console.log "domain.set: $check"
+  return $check
+}
+
+once.check.privileges()     # checks the administrative rights of the current once.su instance 
+{
+  local check=1
+  if ! once.requires.state domain.set; then
+    return $check
+  fi
+  
+  local state="privileges.checked"
+  once.state.get $state
+  local stateId=$RESULT
+
+  if  [ -n "$ONCE_PRIVILEGE" ] && 
+      [ -n "$ONCE_DEFAULT_HOST" ] && 
+      [ -n "$ONCE_SCENARIO" ]
+      then
+        check=0
+        if [ "$ONCE_STATE_ID" -lt $stateId ]; then
+          private.stage $state
+        else
+          private.state.$state
+        fi
+  else
+    if [ "$USERHOME" != "/root" ]; then
+      private.stage state.user
+    else
+      private.stage state.root
+    fi
+    check=0
+  fi
+  return $check
+}
+
+once.check.root.installed()     # checks the administrative rights of the current once.su instance 
+{
+  local check=1
+  if ! once.requires.state root; then
+    return $check
+  fi
+  
+  local state="root.installed"
+  once.state.get $state
+  local stateId=$RESULT
+
+  if  [ -n "$ONCE_PRIVILEGE" ] && 
+      [ -n "$ONCE_DEFAULT_HOST" ] && 
+      [ -n "$ONCE_SCENARIO" ]
+      then
+        check=0
+        if [ "$ONCE_STATE_ID" -lt $stateId ]; then
+          private.stage $state
+        else
+          private.state.$state
+        fi
+  else
+   private.stage root.installation
+  fi
+  return $check
+}
+
+once.check.root.ssh.dev() {
+    once.check.root.ssh.initialized
+}
+once.check.root.ssh.initialized() {
+
+  local check=1
+  if ! once.requires.state root; then
+    return $check
+  fi
+  
+  local state="root.ssh.dev"
+  if diff /root/.ssh/id_rsa /root/.ssh/private_key/developer.wo-da.de.private_key; then
+    important.log "ssh id is developer@wo-da.de"
+  else
+    important.log "ssh id is configured correctly... check if you enabled it in GitHub"
+    state="root.ssh.initialized"
+  fi
+  once.state.get $state
+  local stateId=$RESULT
+
+  
+  if ! this.functionExists user.ssh.status; then
+    info.log "sourcing $OOSH_DIR/user"
+    source $OOSH_DIR/user
+  fi
+  if user.ssh.status log; then
+      check=0
+      if [ "$ONCE_STATE_ID" -lt $stateId ]; then
+        private.stage $state
+      else
+        private.state.$state
+      fi
+  else
+    console.log "creating .ssh directory preconfigured access to once repositories"
+    once.ssh.init root
+    private.stage $state
+  fi
+  
+  return $check
+}
+
+
+once.check.root.not.installed() {
+    debug.log ""
+}
+once.check.root.repo.installed() {
+  local check=1
+  if ! once.requires.state root; then
+    return $check
+  fi
+  
+  local state="root.repo.installed"
+  once.state.get $state
+  local stateId=$RESULT
+  
+  if [ -d $COMPONENTS_DIR ]; then
+    console.log "Repository found at $COMPONENTS_DIR..."
+      if [ "$ONCE_STATE_ID" -lt $stateId ]; then
+        private.stage $state
+      else
+        private.state.$state
+      fi
+  else
+    console.log "Repository NOT FOUND at $COMPONENTS_DIR..."
+
+    if once.requires.state initialized; then
+      info.log "cheking installation"
+    else
+      warn.log "cannot initialize ssh without minimum state: initialized"
+      return 1
+    fi
+
+    once.check.root.ssh.initialized
+
+
+    once.repo.init
+    private.stage root.repo.installed
+  fi
+  return $check
+}
+
+
 
 once.stage() 
 {
@@ -5967,9 +6200,14 @@ once.stage()
     fi
     once.hibernate update
     important.log "stage to: private.state.${ONCE_STATES[ONCE_STATE_ID]}"
-    private.stage ${ONCE_STATES[ONCE_STATE_ID]}
+    
+    if once.check.${ONCE_STATES[ONCE_STATE_ID]}; then
+      private.stage ${ONCE_STATES[ONCE_STATE_ID]}
+    else
+      error.log "Failed to verify state: ${ONCE_STATES[ONCE_STATE_ID]}"
+    fi
   else
-    warning "could not stage to: $1 - $state"
+    warn.log "could not stage to: $1 - $state"
     return 1
   fi
 }
@@ -5991,6 +6229,8 @@ once.domain.check() {
   ONCE_DEFAULT_HOST: $ONCE_DEFAULT_HOST
 
        VIRTUAL_HOST: $VIRTUAL_HOST
+
+      ONCE_SCENARIO: $ONCE_SCENARIO
   "
 }
 
@@ -6185,7 +6425,9 @@ function private.stage()                # transitions to the next state of th ON
     once.state.su.set ${1#"state."}
   fi
   if [ "$ONCE_STATE" = "stage" ] ; then
-	  once.state.su.set status
+	  error.log "should never come here"
+    stop.log "please intterrupt with pressing q"
+    once.state.su.set status
     private.stage
     return
   fi
@@ -6197,7 +6439,7 @@ function private.stage()                # transitions to the next state of th ON
   #if [ "ON" = "$DEBUG" ]; then 
   #  stepDebugger ON
   #fi
-  stop.log "docker.build check"
+  #stop.log "docker.build check"
   if [[ "$ONCE_STATE" == state.* ]]; then
     private.$ONCE_STATE "$@"
   else
@@ -6478,7 +6720,7 @@ function deprecated.su.check.install(){
     echo 'Error: Required Package is not installed.' >&2
     once.su.double.line
     echo "Trying to install....."
-    once.docker.install
+    once.su.docker.install
     once.su.double.line
     
   fi
