tested till db.started

diff --git a/init/once b/init/once
--- a/init/once
+++ b/init/once
@@ -1466,6 +1466,26 @@ private.state.initialized() {
 
 }
 
+private.state.nginx.started() {
+  once.docker.scenario.status nginx
+  success.log "nginx is UP"
+}
+
+private.state.certbot.started() {
+  once.docker.scenario.status certbot
+  success.log "certbot is UP"
+}
+
+private.state.keycloak.started() {
+  once.docker.scenario.status keycloak
+  success.log "keycloak is UP"
+}
+
+private.state.db.started() {
+  once.docker.scenario.status pg
+  success.log "once-postgresql is UP"
+}
+
 function deprectaed.su.finalize.installation()            # prints where the repository has been installed 
 {
 
@@ -3759,6 +3779,7 @@ once.docker.scenario.status()
   else
     echo -e "      current SCENARIO:    \033[1;31m MISIING \033[0m"
   fi
+  check.debug.level 3
   echo "
        "
   local DI_NAME=$(echo $SELECTED_SCENARIO_DI_NAME | cut -d: -f1)
@@ -3809,6 +3830,12 @@ for l in $image_list
   do
     echo docker volume rm $l
   done
+
+if [  "$service_status" = "\033[1;32m UP \033[0m" ]; then
+  return 0
+else
+  return 1
+fi
 }
 
 once.docker.scenario.backup.restore()
@@ -6144,9 +6171,9 @@ once.check.privileges()     # checks the administrative rights of the current on
       then
         check=0
         if [ "$ONCE_STATE_ID" -lt $stateId ]; then
-          private.stage $state
+          private.stage $ONCE_PRIVILEGE
         else
-          private.state.$state
+          private.state.$ONCE_PRIVILEGE
         fi
   else
     if [ "$USERHOME" != "/root" ]; then
@@ -6325,6 +6352,8 @@ once.check.dev.ca.installed()
   return $check
 }
 
+
+
 once.check.certificates.installed()
 {
     local check=1
@@ -6353,6 +6382,123 @@ once.check.certificates.installed()
   return $check
 }
 
+
+once.check.nginx.started()
+{
+    local check=1
+  if ! once.requires.state docker.installed; then
+    return $check
+  fi
+  
+  local state="nginx.started"
+  once.state.get $state
+  local stateId=$RESULT
+
+
+  if once.docker.scenario.status nginx 
+      then
+        info.log "check $state succeded"
+        check=0
+        if [ "$ONCE_STATE_ID" -lt $stateId ]; then
+          private.stage $state
+        else
+          private.state.$state
+        fi
+  else
+    info.log "check $state failed"
+    once.docker.scenario.create nginx $ONCE_SCENARIO_DOMAIN
+    private.stage $state
+  fi
+  return $check
+}
+
+once.check.certbot.started()
+{
+    local check=1
+  if ! once.requires.state nginx.started; then
+    return $check
+  fi
+  
+  local state="certbot.started"
+  once.state.get $state
+  local stateId=$RESULT
+
+
+  if once.docker.scenario.status nginx 
+      then
+        info.log "check $state succeded"
+        check=0
+        if [ "$ONCE_STATE_ID" -lt $stateId ]; then
+          private.stage $state
+        else
+          private.state.$state
+        fi
+  else
+    info.log "check $state failed"
+    once.docker.scenario.create certbot $ONCE_SCENARIO_DOMAIN
+    private.stage $state
+  fi
+  return $check
+}
+
+once.check.keycloak.started()
+{
+    local check=1
+  if ! once.requires.state docker.installed; then
+    return $check
+  fi
+  
+  local state="keycloak.started"
+  once.state.get $state
+  local stateId=$RESULT
+
+
+  if once.docker.scenario.status keycloak 
+      then
+        info.log "check $state succeded"
+        check=0
+        if [ "$ONCE_STATE_ID" -lt $stateId ]; then
+          private.stage $state
+        else
+          private.state.$state
+        fi
+  else
+    info.log "check $state failed"
+    once.docker.scenario.create psql
+    once.docker.scenario.create keycloak
+    private.stage $state
+  fi
+  return $check
+}
+
+once.check.db.started()
+{
+    local check=1
+  if ! once.requires.state docker.installed; then
+    return $check
+  fi
+  
+  local state="db.started"
+  once.state.get $state
+  local stateId=$RESULT
+
+
+  if once.docker.scenario.status pg 
+      then
+        info.log "check $state succeded"
+        check=0
+        if [ "$ONCE_STATE_ID" -lt $stateId ]; then
+          private.stage $state
+        else
+          private.state.$state
+        fi
+  else
+    info.log "check $state failed"
+    once.docker.scenario.create pg
+    private.stage $state
+  fi
+  return $check
+}
 
 once.stage() 
 {
@@ -6405,15 +6551,16 @@ private.isNumber() {
 once.domain.check() {
   echo "Checking once domain
   
-           Hostname: $(hostname)
-           HOSTNAME: $HOSTNAME
+              Hostname: $(hostname)
+              HOSTNAME: $HOSTNAME
 
-        ONCE_DOMAIN: $ONCE_DOMAIN
-  ONCE_DEFAULT_HOST: $ONCE_DEFAULT_HOST
+           ONCE_DOMAIN: $ONCE_DOMAIN
+  ONCE_SCENARIO_DOMAIN: $ONCE_SCENARIO_DOMAIN
+     ONCE_DEFAULT_HOST: $ONCE_DEFAULT_HOST
 
-       VIRTUAL_HOST: $VIRTUAL_HOST
+          VIRTUAL_HOST: $VIRTUAL_HOST
 
-      ONCE_SCENARIO: $ONCE_SCENARIO
+         ONCE_SCENARIO: $ONCE_SCENARIO
   "
 }
 
@@ -6445,6 +6592,7 @@ once.domain.set()
     RETURN=$1
     return 2
   fi
+  ONCE_SCENARIO_DOMAIN=$domain
   ONCE_DEFAULT_HOST=$domain
   once.domain.discover
 
@@ -6496,12 +6644,22 @@ function once.su.update.variables()     # updates the environmental variables: R
     once.path.create $ONCE_SCENARIO
   fi
 
+
   #if [ ! -d "$ONCE_DEFAULT_SCENARIO" ]; then 
   #  warn.log "no default scenario, using localhost and creating dir: $ONCE_DEFAULT_SCENARIO"
     ONCE_DEFAULT_SCENARIO=$ONCE_SCENARIO/EAM/1_infrastructure/Once/latestServer
   #fi
   
   ONCE_LOAD_DIR=$SCENARIOS_DIR/localhost/EAM/1_infrastructure/Once/latestServer/oosh
+
+  if [ -z "$VIRTUAL_HOST" ]; then 
+    VIRTUAL_HOST=$ONCE_DOMAIN
+  fi
+
+  if [ -z "$ONCE_SCENARIO_DOMAIN" ]; then 
+    ONCE_SCENARIO_DOMAIN=$ONCE_DEFAULT_HOST
+  fi
+
 
   if [ -z "$ONCE_STRUCTR_SERVER" ]; then 
     console.log "no default ONCE_STRUCTR_SERVER"
@@ -6525,7 +6683,9 @@ function once.su.update.variables()     # updates the environmental variables: R
   fi
   
   if [ -z "$ONCE_POSTGRES_CONNECTION_STRING" ] ; then
-    ONCE_POSTGRES_CONNECTION_STRING=postgresql://root:qazwsx123@once-postgresql:5433/oncestore
+    ONCE_POSTGRES_CONNECTION_STRING=postgresql://root:qazwsx123@localhost:5433/oncestore
+    #for docker 
+    #ONCE_POSTGRES_CONNECTION_STRING=postgresql://root:qazwsx123@once-postgresql:5432/oncestore
   fi
 
   if [ -z "$ONCE_DIRECT_HTTPS_URL" ] ; then
@@ -6749,10 +6909,10 @@ once.start()                # starts the Once Server in the background and remem
     BASH_CURRENT_MAJOR_VERSION=${BASH_VERSINFO[0]}
   fi
   if [ $BASH_CURRENT_MAJOR_VERSION -lt 5 ]; then
-    warn.log "old bash version! switching to: $BASH_FILE"
+    info.log "old bash version! switching to: $BASH_FILE"
     #echo BASH_MAJOR_VERSION=$("$BASH_FILE" -c "echo \"\${BASH_VERSINFO[0]}\"")
 
-    echo BASH_CURRENT_MAJOR_VERSION=${BASH_VERSINFO[0]}
+    info.log "BASH_CURRENT_MAJOR_VERSION=${BASH_VERSINFO[0]}"
     "$BASH_FILE" "once" "$@"
     exit 0
   fi  
