added developking.ssh

diff --git a/init/once b/init/once
--- a/init/once
+++ b/init/once
@@ -17,6 +17,10 @@ once.version()              # prints out the hard coded version tag of $This | t
 if [ -z "$USERHOME" ]; then
   USERHOME=$(cd;pwd)
 fi
+if [ -z "$USER" ]; then
+  USER=$(whoami)
+  export USER
+fi
 
 if [ -f "$USERHOME/oosh/this" ]; then
   source $USERHOME/oosh/this
@@ -406,6 +410,7 @@ once.discover()             # discovers the environment the current once.su inst
           args  : $@
           dir   : $startDir
           home  : $USERHOME
+          user  : $USER
 
         hostname: $HOSTNAME
           type  : $HOSTTYPE
@@ -1358,8 +1363,8 @@ function once.su.check.installation()   # checks for a once.su installation in g
 
   checkAndFix "exists $ONCE_REPO_PREFIX" "-d" "$ONCE_REPO_PREFIX" "once.path.create $ONCE_REPO_PREFIX"
 
-  once.su.pm
-  checkAndFix "make once alias $(which $0)" -L "$(dirname $(which $0))/once" "ln -s $(which $0) $(dirname $(which $0))/once" 
+  #once.su.pm
+  #checkAndFix "make once alias $(which $0)" -L "$(dirname $(which $0))/once" "ln -s $(which $0) $(dirname $(which $0))/once" 
   once.cmd wget
   once.cmd curl
   once.cmd git
@@ -1390,6 +1395,10 @@ private.state.initialized() {
   plaese set a domain with: 
   once domain.set your.domain.com
   "
+
+  if [ ! -f ~/.bashrc.bak.without.completion ]; then
+    /root/init/oosh
+  fi
 
 }
 
@@ -2062,6 +2071,9 @@ once.user.init()    # sets up the .bashrc and scripts of user $1
 
     else
       local userHome="/home/$name"
+      if [ "$name" = "root" ]; then
+        userHome="/root"
+      fi
 
       if [ ! -d "$userHome/scripts" ]; then
           warn.log "$userHome/scripts does not exist..."
@@ -5829,7 +5841,15 @@ once.stage()
   state=$1
   if [ -z "$1" ]; then
     state=$ONCE_STATE_ID
+    private.stage ${ONCE_STATES[ONCE_STATE_ID]}
+    return 0
   fi
+
+  if [ "$state" = "next" ]; then
+    state=$ONCE_STATE_ID
+  fi
+
+
   if once.state.su.set $state; then
     ((ONCE_STATE_ID++))
     important.log "new state is: ${ONCE_STATES[ONCE_STATE_ID]}"
@@ -5915,7 +5935,9 @@ private.state.domain.set()
 {
   once.domain.check
   once.scenario.check
-  success.log "domain set"
+  success.log "\n\ndomain set\n"
+  important.log "you can continue the installation with
+  once stage next"
 }
 
 
@@ -6317,7 +6339,7 @@ function deprecated.docker.network(){
 
 # }
 
-function once.su.check.install(){
+function deprecated.su.check.install(){
   if ! [ -x "$(command -v $1)" ]; then
     echo 
     echo 'Error: Required Package is not installed.' >&2
@@ -7007,7 +7029,7 @@ function once.su.strToArray(){
     export array=${array[@]}
 }
 
-function once.su.ssh.oinit (){
+function once.su.ssh.init.all.users (){
   once.users.list
   once.su.strToArray "$arrayString"  
   echo "Checking All Users SSH Config: "
@@ -7017,86 +7039,60 @@ function once.su.ssh.oinit (){
   do 
       echo "$count. $i";
       echo "Checking SSH Config...";
-      once.ssh $i
+      once.ssh.init $i
       # setup_ssh $i;
       # setup_dev_dir $i
       ((count++))
   done
 }
 
-once.ssh () #To Setup Users SSH Access
+once.ssh.init () #To Setup Users SSH Access
 {
+  local dir=/home/$1
   if [ -z $1 ]; then
     echo 
     echo "Please Specify Username:........."
-    echo "e.g once ssh {username}"
-    once.su.double.line
-  else
-    if [ "$1" = "root" ]; then            
-      if [ "$USER" = "root" ]; then
-        if [ ! -e "/$1/.ssh/id_rsa" ]; then
-            cd /
-            if [ ! -d "/$1/scripts/" ]; then
-                curl http://wo-da.de/EAMD.ucp/Components/com/ceruleanCircle/EAM/1_infrastructure/NewUserStuff/scripts.zip -o scripts.zip
-                if [ ! -d "./scripts" ]; then   
-                    unzip scripts.zip                
-                    mv scripts /root/scripts
-                else
-                    rm -r scripts;
-                    unzip scripts.zip
-                fi
-            fi
-            mkdir -p /$1/.ssh
-            cp -r /$1/scripts/templates/developking.ssh/* /$1/.ssh/
-            chown $1:$1 /$1/.ssh/ 
-            chmod 750 /$1/.ssh/
-            chmod 600 /$1/.ssh/id_rsa
-            chmod 644 /$1/.ssh/id_rsa.pub
-            # tree -L 5
-            export SSH_PATH="/$1/.ssh/id_rsa";
-            echo "SSH PATH: "$SSH_PATH;
-            echo
-        else
-            export SSH_PATH="/$1/.ssh/id_rsa";
-            echo "SSH PATH: "$SSH_PATH;
-            echo 
-        fi
-      else
-        echo "Root Login required to setup root user...."
-        echo
-      fi
-    else
-        if [ ! -e "/home/$1/.ssh/id_rsa" ]; then
-            cd /
-            if [ ! -e "scripts.zip" ]; then
-                curl http://wo-da.de/EAMD.ucp/Components/com/ceruleanCircle/EAM/1_infrastructure/NewUserStuff/scripts.zip -o scripts.zip
-                if [ ! -d "./scripts" ]; then  
-                    unzip scripts.zip
-                else
-                    rm -r scripts;
-                    unzip scripts.zip
-                fi
-            fi
-            
-            mkdir -p /home/$1/.ssh
-            cp -r ./scripts/templates/developking.ssh/* /home/$1/.ssh/
-            chown $1:$1 /home/$1/.ssh/ 
-            chmod 700 /home/$1/.ssh/
-            chmod 600 /home/$1/.ssh/id_rsa
-            chmod 644 /home/$1/.ssh/id_rsa.pub
-            # tree -L 5
-            export SSH_PATH="/home/$1/.ssh/id_rsa";
-            echo "SSH PATH: "$SSH_PATH;
-            echo
-        else
-            echo "SSH Config Exists..."
-            export SSH_PATH="/home/$1/.ssh/id_rsa";
-            echo "SSH PATH: "$SSH_PATH;
-            echo 
-        fi
-    fi
-  
+    warn.log "e.g once ssh {username}"
+    return 1
   fi
+
+  if [ "$dir" = "/home/root" ]; then
+    dir="/root"
+    if ! [ "$USER" = "root" ]; then
+      error.log "Root Login required to setup root user...."
+      exit 2
+    fi
+  fi
+  if [ ! -e "$dir/.ssh/id_rsa" ]; then
+      cd $dir
+      if [ ! -d "$dir/scripts/" ]; then
+          once.cmd unzip
+          curl http://test.wo-da.de/EAMD.ucp/Components/com/ceruleanCircle/EAM/1_infrastructure/NewUserStuff/scripts.zip -o scripts.zip
+          if [ ! -d "./scripts" ]; then   
+              unzip scripts.zip                
+              mv scripts $dir/scripts
+          else
+              rm -r scripts;
+              unzip scripts.zip
+          fi
+      fi
+      mkdir -p $dir/.ssh
+      cp -r $dir/scripts/templates/developking.ssh/* $dir/.ssh/
+      chown $1:$1 $dir/.ssh/ 
+      chmod 750 $dir/.ssh/
+      chmod 600 $dir/.ssh/id_rsa
+      chmod 644 $dir/.ssh/id_rsa.pub
+      # tree -L 5
+      export SSH_PATH="$dir/.ssh/id_rsa";
+      echo "SSH PATH: "$SSH_PATH;
+      echo
+  else
+      export SSH_PATH="$dir/.ssh/id_rsa";
+      echo "SSH PATH: "$SSH_PATH;
+      echo 
+  fi
+
+
   once.su.double.line
 }
 
