making it startable easy

diff --git a/init/once b/init/once
--- a/init/once
+++ b/init/once
@@ -11,7 +11,7 @@ set -T
 
 once.version()              # prints out the hard coded version tag of $This | to update the script use e.g. once update here http://192.168.178.49:8080
 {
- console.log "$0 version: 2021-12-02 17:22 major refactoring untested"
+ console.log "$0 version: 2021-12-03 16:12 eamd free, untested"
 }
 
 if [ -z "$USERHOME" ]; then
@@ -1305,7 +1305,7 @@ once.scenario.dir.completion() {
 
 once.scenario.discover()             # forces re-discovery of the current environment and scenario configuration, but does not change settings (use scenario.fix to change settings) 
 {
-  once.cmd eamd
+  #once.cmd eamd
   #once.path
 
   cd $ONCE_DEFAULT_SCENARIO
@@ -1318,14 +1318,14 @@ once.scenario.discover()             # forces re-discovery of the current enviro
   debug.log h:$hostname- H:$HOSTNAME-
   #stepDebugger ON
 
-  eamd call loop $hostname . reverse x log . r / save once.scenario
+  loop $hostname . reverse x log . r / save once.scenario
   ONCE_SCENARIO=$SCENARIOS_DIR/$(cat once.scenario)
   console.log "ONCE_SCENARIO=$ONCE_SCENARIO"
   ONCE_DOMAIN=$(find $ONCE_SCENARIO -type d -name CertBot -exec find {}/1.7.0/config -mindepth 1 -maxdepth 1 -type d \;)
   #console.log "-ONCE_DOMAIN=-$ONCE_DOMAIN-"
   if [ -n "$ONCE_DOMAIN" ]; then
     stop.log "found domain ONCE_DOMAIN=$ONCE_DOMAIN"
-    eamd call loop $ONCE_DOMAIN / silent x result $startDir/.tmp.result.list.env
+    loop $ONCE_DOMAIN / silent x result $startDir/.tmp.result.list.env
     . $startDir/.tmp.result.list.env
     ONCE_DOMAIN=$lastItem
     
@@ -1333,7 +1333,7 @@ once.scenario.discover()             # forces re-discovery of the current enviro
     ONCE_DEFAULT_HOST=$ONCE_DOMAIN
     
     console.log "ONCE_DOMAIN=$ONCE_DOMAIN"
-    eamd call loop $ONCE_DOMAIN . reverse x log . r / save once.domain
+    loop $ONCE_DOMAIN . reverse x log . r / save once.domain
     ONCE_DOMAIN=$(cat once.domain)
     ONCE_SCENARIO=$ONCE_SCENARIO/vhosts/$ONCE_DOMAIN
 
@@ -1361,39 +1361,69 @@ function once.find()                 # finds all running node servers
 function once.su.check.installation()   # checks for a once.su installation in given path
 {
 
-  checkAndFix "exists $ONCE_REPO_PREFIX" "-d" "$ONCE_REPO_PREFIX" "once.path.create $ONCE_REPO_PREFIX"
-
-  #once.su.pm
-  #checkAndFix "make once alias $(which $0)" -L "$(dirname $(which $0))/once" "ln -s $(which $0) $(dirname $(which $0))/once" 
-  once.cmd wget
-  once.cmd curl
-  once.cmd git
-  #once.cmd eamd
-
-  error.log "fix ssh.init"
-  #private.stage deprecated.ssh.init
-
-
-  if [ -d $COMPONENTS_DIR ]; then
+  if ! [ -d $COMPONENTS_DIR ]; then
     console.log "Repository found at $COMPONENTS_DIR..."
-    console.log "discover scenario..."
-    once.scenario.discover
     #once paths.reset paths.save
   else
     console.log "Repository NOT FOUND at $COMPONENTS_DIR..."
-    once.repo.init
 
+
+    if once.requires.state 1; then
+      info.log "cheking installation"
+    else
+      warn.log "cannot initialize ssh without minimum state initialized"
+      return 1
+    fi
+    checkAndFix "exists $ONCE_REPO_PREFIX" "-d" "$ONCE_REPO_PREFIX" "once.path.create $ONCE_REPO_PREFIX"
+
+    #once.su.pm
+    #checkAndFix "make once alias $(which $0)" -L "$(dirname $(which $0))/once" "ln -s $(which $0) $(dirname $(which $0))/once" 
+    once.cmd wget
+    once.cmd curl
+    once.cmd tree
+    once.cmd vim
+    once.cmd git
+    #once.cmd eamd
+
+    source $OOSH_PATH/user
+    if user.ssh.status log; then
+      console.log ".ssh exists"
+    else
+      console.log "creating .ssh directory preconfigured access to once repositories"
+      once.ssh.init root
+    fi
+
+
+    private.stage root.ssh.dev
+
+    once.repo.init
   fi
+
   
-  private.stage state.installed
+  private.stage root.repo.installed
 }
+
+private.state.root.ssh.dev() {
+  warn.log "root ssh is settup for once repository access but only with a freemium developer identity 
+
+  "
+  tree ~/.ssh
+  important.log "plaese initialize your own ssh id and register it with the once repositories:
+
+  user ssh.backup
+  user ssh.init
+  once ssh.register.once.user
+  "
+}
+
 
 private.state.initialized() {
   success.log "oosh and once completion installed. 
   
   ONCE_SCENARIO=$ONCE_SCENARIO
-  
-  plaese set a domain with: 
+  "
+  console.log "plaese set a domain with:
+
   once domain.set your.domain.com
   "
 
@@ -1889,11 +1919,12 @@ once.states()
   [19]=21 \
   [21]="root" \
   [22]="root.installation" \
-  [23]="root.ssh.initialized" \
-  [24]="root.not.installed" \
-  [25]="root.repo.installed" \
-  [26]="root.installed" \
-  [27]=30 \
+  [23]="root.ssh.dev" \
+  [24]="root.ssh.initialized" \
+  [25]="root.not.installed" \
+  [26]="root.repo.installed" \
+  [27]="root.installed" \
+  [28]=30 \
   [30]="scenario.updated.to.domain" \
   [31]="scenario.updated.to.domain" \
   [32]=40 \
@@ -2273,7 +2304,7 @@ once.ssh.set.config.host()
   #reconfigure
 }
 
-once.repo.new.init() {
+once.repo.init() {
   once.path.create $ONCE_REPO_PREFIX
   cd $ONCE_REPO_PREFIX
 
@@ -2281,20 +2312,33 @@ once.repo.new.init() {
     git stash -u 
     git pull
   else
-    if [ -d "$REPO_DIR" ]; then
-      rm -Rf $REPO_DIR
-      if [ -d "$REPO_DIR.delete" ]; then
-        mv $REPO_DIR.delete $REPO_DIR
-        once.repo.new.init
-        return $?
-      fi
-    fi
-    git clone -c core.symlinks=true git@bitbucket.org:donges/eamd.ucp.git EAMD.ucp
+    # if [ -d "$REPO_DIR" ]; then
+    #   # if [ -d "$REPO_DIR.delete" ]; then
+    #   #   rm -Rf $REPO_DIR.delete
+    #   #   once.repo.new.init
+    #   #   return $?
+    #   # fi
+    #   # mv $REPO_DIR $REPO_DIR.delete
+    # fi
+    once.cmd git
+    #git clone -c core.symlinks=true git@bitbucket.org:donges/eamd.ucp.git EAMD.ucp
+
+    important.log "ONCE_SCENARIO=$ONCE_SCENARIO
+
+    once.path.create $ONCE_SCENARIO
+    mv $REPO_DIR.delete${ONCE_SCENARIO#"$REPO_DIR"}/EAM
+    "
+  LOG_LEVEL=6
+    once.path.create $ONCE_SCENARIO
+    mv $REPO_DIR.delete${ONCE_SCENARIO#"$REPO_DIR"}/EAM $ONCE_SCENARIO
+    stop.log "check last echo line"
   fi
+  once.cmd tree
   tree -L 2 $ONCE_REPO_PREFIX
   cd $REPO_DIR
   git status
-  once.scenario.fix
+
+  return 0
 }
 
 once.repo.new.checkout.scenarioBranch() {
@@ -2311,7 +2355,7 @@ once.repo.status()
 }
 
 
-once.repo.init()            # forces reinitialisation 
+once.repo.init.old()            # forces reinitialisation 
 {
 
   console.log "initialize Repository in $ONCE_REPO_PREFIX"
@@ -5927,7 +5971,7 @@ once.domain.set()
 
   private.stage state.domain.set
   
-  once.state.check
+  #once.state.check
 
   RETURN=$1
   return 0
@@ -5938,7 +5982,8 @@ private.state.domain.set()
   once.domain.check
   once.scenario.check
   success.log "\n\ndomain set\n"
-  important.log "you can continue the installation with
+  console.log "you can continue the installation with
+
   once stage next"
 }
 
@@ -6204,23 +6249,20 @@ once.start()                # starts the Once Server in the background and remem
 
   This=$(which $0)
   this=$(basename $This)
-
-
+  local command=$1
  
- 
-  if [ "$1" = "completion.discover" ]; then 
+  if [ "$command" = "completion.discover" ]; then 
     shift
     once.completion.discover "$@"
   fi
   #echo checking $1
-  if [[ "$1" == *completion ]]; then 
+  if [[ "$command" == *completion ]]; then 
     #echo completion found
     source ~/.once
     { 
       once.su.update.variables 
     } >/dev/null
-    #LOG_LEVEL=6
-    local command=$1
+
     shift
     once.$command "$@"
     exit $?
@@ -6228,14 +6270,20 @@ once.start()                # starts the Once Server in the background and remem
   #  echo no completion
   fi
   #stop.log "once.discover $COMMANDS"
-  once.discover "$@"
-  if [ -z "$1" ]; then 
-        console.log "no parameters! stage to: $ONCE_STATE"
-        private.stage
-        console.log "$this: Bye"
-        
-        private.done
+  if [ -z "$command" ]; then 
+      console.log "no parameters! stage to: $ONCE_STATE"
+      if [ -f ~/.once ]; then 
+        source ~/.once
+        { 
+          once.su.update.variables 
+        } >/dev/null
+        once.stage
+        console.log "$This: Bye"
+        exit 0
+      fi
   fi
+  once.discover "$@"
+
 
   while [ -n $1 ]; do
     debug.log "start 1: -$1-"
@@ -7061,25 +7109,25 @@ once.ssh.init () #To Setup Users SSH Access
   if [ "$dir" = "/home/root" ]; then
     dir="/root"
     if ! [ "$USER" = "root" ]; then
-      error.log "Root Login required to setup root user...."
+      error.log "You need to be logged in as root to setup the Root user...."
       exit 2
     fi
   fi
   if [ ! -e "$dir/.ssh/id_rsa" ]; then
-      cd $dir
-      if [ ! -d "$dir/scripts/" ]; then
-          once.cmd unzip
-          curl http://test.wo-da.de/EAMD.ucp/Components/com/ceruleanCircle/EAM/1_infrastructure/NewUserStuff/scripts.zip -o scripts.zip
-          if [ ! -d "./scripts" ]; then   
-              unzip scripts.zip                
-              mv scripts $dir/scripts
-          else
-              rm -r scripts;
-              unzip scripts.zip
-          fi
-      fi
+      # cd $dir
+      # if [ ! -d "$dir/scripts/" ]; then
+      #     once.cmd unzip
+      #     curl http://test.wo-da.de/EAMD.ucp/Components/com/ceruleanCircle/EAM/1_infrastructure/NewUserStuff/scripts.zip -o scripts.zip
+      #     if [ ! -d "./scripts" ]; then   
+      #         unzip scripts.zip                
+      #         mv scripts $dir/scripts
+      #     else
+      #         rm -r scripts;
+      #         unzip scripts.zip
+      #     fi
+      # fi
       mkdir -p $dir/.ssh
-      cp -r $dir/scripts/templates/developking.ssh/* $dir/.ssh/
+      cp -r $dir/oosh/templeates/user/developking.ssh/* $dir/.ssh
       chown $1:$1 $dir/.ssh/ 
       chmod 750 $dir/.ssh/
       chmod 600 $dir/.ssh/id_rsa
