feat(): Modify files with editor config rules

diff --git a/init/oosh b/init/oosh
--- a/init/oosh
+++ b/init/oosh
@@ -2,7 +2,10 @@
 #http://www.etalabs.net/sh_tricks.html
 
 export PS4='sh debug> '
-if [ -z "$SH_OPT" ]; then export SH_OPT="-x"; echo "SH_OPT set to: $SH_OPT"; fi
+if [ -z "$SH_OPT" ]; then
+  export SH_OPT="-x"
+  echo "SH_OPT set to: $SH_OPT"
+fi
 
 # find all set -x
 #  '^ *[^#] *set -x'
@@ -10,74 +13,66 @@ set $SH_OPT
 # force debug
 
 #unset SHELL
-oosh_get_running_shell() 
-{
+oosh_get_running_shell() {
   #SHELLNAME="$(ps -o pid,args | grep "\w*$$ [^g]*sh" | awk '{$1=$1};1' | cut -d\  -f2 | sed s/-//)"
   SHELLPS="$(ps -o pid,args | grep "\w*$$ [^g]*/sh")"
   SHELL=$(which "$SHELLNAME")
 }
 
-log()
-{
+log() {
   if [ "$LOG_LEVEL" -gt 4 ]; then
     echo "$@"
   fi
-} 
+}
 
-oosh_check_pm()             # checks for a package manager
-{
-    packageManager=$1
-    packageManagerCommand=$2
+oosh_check_pm() { # checks for a package manager
+  packageManager=$1
+  packageManagerCommand=$2
 
-
-    if [ -z "$packageManagerCommand" ]; then
-        package=$packageManager
-    fi   
-    if ! [ -x "$(command -v $packageManager)" ]; then
-        log "no $packageManager"
-    else
-        if [ -z "$OOSH_PM" ]; then
-            export OOSH_PM="$packageManagerCommand"
-            #export groupAddCommand=$2
-            #export userAddCommand=$3
-            log "Package Manager found: using $OOSH_PM somePackage"
-            if [ "$packageManager" = "apt-get" ]; then
-                if [ -z "$OOSH_PM_UPDATED" ]; then
-                  OOSH_PM_UPDATED="$SUDO apt-get update"
-                  if [ "$HOME" = "/root" ]; then
-                    $OOSH_PM_UPDATED
-                  else
-                    #sudo $OOSH_PM_UPDATED
-                    PM="sudo $PM"
-                    SUDO="sudo -S"
-                    $SUDO $OOSH_PM_UPDATED
-                  fi
-                else
-                  log "in case of installation errors try to call: apt-get update"
-                fi
-            fi
+  if [ -z "$packageManagerCommand" ]; then
+    package=$packageManager
+  fi
+  if ! [ -x "$(command -v $packageManager)" ]; then
+    log "no $packageManager"
+  else
+    if [ -z "$OOSH_PM" ]; then
+      export OOSH_PM="$packageManagerCommand"
+      #export groupAddCommand=$2
+      #export userAddCommand=$3
+      log "Package Manager found: using $OOSH_PM somePackage"
+      if [ "$packageManager" = "apt-get" ]; then
+        if [ -z "$OOSH_PM_UPDATED" ]; then
+          OOSH_PM_UPDATED="$SUDO apt-get update"
+          if [ "$HOME" = "/root" ]; then
+            $OOSH_PM_UPDATED
+          else
+            #sudo $OOSH_PM_UPDATED
+            PM="sudo $PM"
+            SUDO="sudo -S"
+            $SUDO $OOSH_PM_UPDATED
+          fi
+        else
+          log "in case of installation errors try to call: apt-get update"
         fi
+      fi
     fi
+  fi
 }
 
-oosh_check_all_pm()         # adds tools and configurations to package manager (brew, apt-get, addgroup, adduser, dpkg, pkg)
-{
-
-    oosh_check_pm brew "brew install"    
-   #oosh_check_pm apt "apt add"
-    oosh_check_pm apt-get "apt-get -y install" "groupadd -f" "useradd -g dev"
-    oosh_check_pm apk "apk add" "addgroup" "adduser -g dev"
-    oosh_check_pm dpkg "dpkg install"
-    oosh_check_pm pkg "pkg install"
-    oosh_check_pm pacman "pacman -S"
- 
+oosh_check_all_pm() { # adds tools and configurations to package manager (brew, apt-get, addgroup, adduser, dpkg, pkg)
+  oosh_check_pm brew "brew install"
+  #oosh_check_pm apt "apt add"
+  oosh_check_pm apt-get "apt-get -y install" "groupadd -f" "useradd -g dev"
+  oosh_check_pm apk "apk add" "addgroup" "adduser -g dev"
+  oosh_check_pm dpkg "dpkg install"
+  oosh_check_pm pkg "pkg install"
+  oosh_check_pm pacman "pacman -S"
 }
 
-oosh_check_os() # check on which Operating System oosh is being deploid on #
-{
-  if ! [ -x "$( command -v oo )" ]; then
-   info.log "no os script class installed yet"
-   return 1
+oosh_check_os() { # check on which Operating System oosh is being deploid on #
+  if ! [ -x "$(command -v oo)" ]; then
+    info.log "no os script class installed yet"
+    return 1
   fi
   if os check.env; then
     info.log "OS detected and OOSH_OS populated with $OOSH_OS"
@@ -85,56 +80,52 @@ oosh_check_os() # check on which Operating System oosh is being deploid on #
     error.log "NO OS detected"
   fi
 
-  exit 
+  exit
 }
 
-oosh_cmd() 
-{
-    unset package
-    current=$1
+oosh_cmd() {
+  unset package
+  current=$1
+  shift
+  if [ -n "$1" ]; then
+    package=$1
     shift
-    if [ -n "$1" ]; then
-      package=$1
-      shift
-    fi
-    if [ -z "$package" ]; then
-        package=$current
-    else
-      shift
-      package=$1
-    fi
+  fi
+  if [ -z "$package" ]; then
+    package=$current
+  else
+    shift
+    package=$1
+  fi
 
-    if [ -z "$OOSH_OS" ]; then
-      echo "no OS found...checking" 
-      #oosh_check_os
+  if [ -z "$OOSH_OS" ]; then
+    echo "no OS found...checking"
+    #oosh_check_os
+  fi
+
+  if [ -z "$OOSH_PM" ]; then
+    echo "no PM found...checking"
+    oosh_check_all_pm
+  fi
+  if ! [ -x "$(command -v $current)" ]; then
+    echo "no $current"
+    if [ -n "$OOSH_PM" ]; then
+      $SUDO $OOSH_PM $package
+    else
+      echo "still no PM found: $OOSH_PM $package"
     fi
-    
-    if [ -z "$OOSH_PM" ]; then
-      echo "no PM found...checking" 
-      oosh_check_all_pm
-    fi
-    if ! [ -x "$(command -v $current)" ]; then
-        echo "no $current"
-        if [ -n "$OOSH_PM" ]; then
-          $SUDO $OOSH_PM $package
-        else
-          echo "still no PM found: $OOSH_PM $package"
-        fi
-    # else
-    #   echo "command $current exists"
-    fi
+  # else
+  #   echo "command $current exists"
+  fi
 }
 
-oosh_install_oosh()
-{
-
+oosh_install_oosh() {
   oosh_cmd git
   oosh_cmd rsync
   cd ~
   #if [ -z "$OOSH_DIR" ]; then
-    OOSH_DIR="$(pwd)/oosh"
+  OOSH_DIR="$(pwd)/oosh"
   #fi
-
 
   if ! [ -d "$OOSH_DIR" ]; then
     #set -x # force debug
@@ -150,7 +141,7 @@ oosh_install_oosh()
         chmod +x ./init/oosh
       fi
       mv ./once.sh ./oosh
-      
+
       ### temporary for testing
       if [ ! -z "$DEV_MODE" ] || [ ! -z ${OOSH_BRANCH} ]; then
         cd "$OOSH_DIR"
@@ -170,8 +161,7 @@ oosh_install_oosh()
   fi
 }
 
-oosh_status()
-{
+oosh_status() {
   echo "
   SHELL: $SHELL
        : $SHELLNAME
@@ -180,7 +170,7 @@ oosh_status()
       0: $0
 
      PM: $OOSH_PM
-         $OOSH_PM_UPDATED 
+         $OOSH_PM_UPDATED
 
    BASH: $BASH_FILE
       v: $BASH_MAJOR_VERSION
@@ -188,19 +178,18 @@ oosh_status()
    INSTALL_MODE: $INSTALL_MODE
        DEV_MODE: $DEV_MODE
 
-   USER: $USER 
+   USER: $USER
 
    PATH: $PATH
   "
-  if [ "$HOME"  = "/root" ];then
+  if [ "$HOME" = "/root" ]; then
     SUDO=""
   else
     SUDO="sudo -S"
   fi
 }
 
-oosh_parse_shellps() 
-{
+oosh_parse_shellps() {
   if [ -n "$1" ]; then
     shell_pid=$1
     shift
@@ -218,19 +207,16 @@ oosh_parse_shellps()
   fi
   this=$2
 
-  log " 
+  log "
     shell: $shell
       pid: $shell_pid
    script: $script
      this: $this
   "
   SHELL=$shell
-
 }
 
-
-oosh_start() 
-{
+oosh_start() {
   if [ -n "$1" ]; then
     echo "got parameters: $@"
     while [ -n $1 ]; do
@@ -241,13 +227,13 @@ oosh_start()
           INSTALL_MODE="$1"
           shift
           echo "having: $*"
-          
+
           if [ -n "$1" ]; then
             echo "name used by remote for this ssh connection: $1"
             export SSH_CONFIG_NAME_USED_FOR_LOCAL="$1"
             shift
           fi
-          
+
           if [ -n "$1" ]; then
             echo "name of the remote ssh connection: $1"
             export SSH_CONFIG_FROM_REMOTE="$1"
@@ -260,14 +246,15 @@ oosh_start()
             shift
           fi
           break
-        ;;
+          ;;
         *)
           echo "this.call to: $*"
           #this.call "$@"
           shift
+          ;;
       esac
     done
-    #return 0 
+    #return 0
   fi
 
   if [ -z "$LOG_LEVEL" ]; then
@@ -279,7 +266,7 @@ oosh_start()
   # fi
 
   # for testing: Docker install from OOSH_INSTALL_SOURCE
-  # export OOSH_INSTALL_SOURCE=/opt/once.sh
+  export OOSH_INSTALL_SOURCE=/opt/once.sh
 
   oosh_get_running_shell
   oosh_parse_shellps $SHELLPS
diff --git a/log b/log
--- a/log
+++ b/log
@@ -7,39 +7,37 @@
 # export PS4='\e[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \e[0m'
 # set -x
 
-log.device()
-{
+log.device() {
   local device=$1
   if [ -z "$device" ]; then
     device=/dev/tty
   fi
 
   export LOG_DEVICE=$device
-  echo "initializing logging to $LOG_DEVICE" >>$LOG_DEVICE
+  echo "initializing logging to $LOG_DEVICE" >> $LOG_DEVICE
   RETURN_VALUE="$?"
   if [ $RETURN_VALUE -eq 1 ]; then
     old_log_device=$LOG_DEVICE
     export LOG_DEVICE=/dev/stderr
-    echo "  Tried to initialize logging to $old_log_device and failed" >>$LOG_DEVICE
-    echo "  logging over ssh (or other non-tty) ... using $LOG_DEVICE" >>$LOG_DEVICE
+    echo "  Tried to initialize logging to $old_log_device and failed" >> $LOG_DEVICE
+    echo "  logging over ssh (or other non-tty) ... using $LOG_DEVICE" >> $LOG_DEVICE
   fi
 }
 
-log.init()
-{
+log.init() {
   local device=$1
   if [ -z "$device" ]; then
     device=/dev/tty
   fi
 
   export LOG_DEVICE=$device
-  echo "initializing logging to $LOG_DEVICE" >>$LOG_DEVICE
+  echo "initializing logging to $LOG_DEVICE" >> $LOG_DEVICE
   RETURN_VALUE="$?"
   if [ $RETURN_VALUE -eq 1 ]; then
     old_log_device=$LOG_DEVICE
     export LOG_DEVICE=/dev/stderr
-    echo "  Tried to initialize logging to $old_log_device and failed" >>$LOG_DEVICE
-    echo "  logging over ssh (or other non-tty) ... using $LOG_DEVICE" >>$LOG_DEVICE
+    echo "  Tried to initialize logging to $old_log_device and failed" >> $LOG_DEVICE
+    echo "  logging over ssh (or other non-tty) ... using $LOG_DEVICE" >> $LOG_DEVICE
   fi
 }
 
@@ -55,7 +53,7 @@ log.init() {
     log.init.colors
   fi
 
-  echo "initializing logging to $LOG_DEVICE" >>$LOG_DEVICE
+  echo "initializing logging to $LOG_DEVICE" >> $LOG_DEVICE
   RETURN_VALUE="$?"
   if [ $RETURN_VALUE -eq 1 ]; then
     export LOG_DEVICE=/dev/stderr
@@ -71,7 +69,6 @@ log.init() {
     export LOG_LEVEL=3
   fi
 
-
   important.log "log initialized on level $LOG_LEVEL"
 }
 
@@ -82,7 +79,7 @@ fi
 console.log() {
   seq.puml.log
   if [ "$LOG_LEVEL" -gt "2" ]; then
-    echo -e "${NO_COLOR}$*" >>$LOG_DEVICE
+    echo -e "${NO_COLOR}$*" >> $LOG_DEVICE
   fi
 }
 
@@ -105,61 +102,61 @@ seq.puml.log() {
       export PS4='\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
       set +x
     fi
-  } 2>/dev/null
+  } 2> /dev/null
 }
 
 silent.log() {
-  seq.puml.log 2>/dev/null
+  seq.puml.log 2> /dev/null
   if [ "$LOG_LEVEL" -gt "2" ]; then
-    echo -e "${GRAY}  $*${NORMAL}" >>$LOG_DEVICE
+    echo -e "${GRAY}  $*${NORMAL}" >> $LOG_DEVICE
   fi
 }
 
 success.log() {
-  seq.puml.log 2>/dev/null
+  seq.puml.log 2> /dev/null
   if [ "$LOG_LEVEL" -gt "2" ]; then
-    echo -e "${BOLD_GREEN}SUCCESS> $*${NORMAL}" >>$LOG_DEVICE
+    echo -e "${BOLD_GREEN}SUCCESS> $*${NORMAL}" >> $LOG_DEVICE
   fi
 }
 
 test.success.log() {
-  seq.puml.log 2>/dev/null
+  seq.puml.log 2> /dev/null
   if [ "$LOG_LEVEL" -gt "0" ]; then
     echo -e "${BOLD_GREEN}SUCCESS> $*${NORMAL}"
   fi
 }
 
 error.details.log() {
-  seq.puml.log 2>/dev/null
+  seq.puml.log 2> /dev/null
   if [ "$LOG_LEVEL" -gt "0" ]; then
     echo -e "${NORMAL}$*"
   fi
 }
 
 warn.log() {
-  seq.puml.log 2>/dev/null
+  seq.puml.log 2> /dev/null
   if [ "$LOG_LEVEL" -gt "1" ]; then
     echo -e "${BOLD_YELLOW}> WARNING $*${NORMAL}" | tee -a ~/config/error.txt #>>$CONFIG_PATH/result.txt ## yellow
   fi
   {
     shift
     RETURN=$1
-  } 2>/dev/null
+  } 2> /dev/null
 }
 
 important.log() {
-  seq.puml.log 2>/dev/null
+  seq.puml.log 2> /dev/null
   if [ "$LOG_LEVEL" -gt "1" ]; then
-    echo -e "${ESC}${BOLD_CYAN}IMPORTANT> $*${NORMAL}" >>$LOG_DEVICE ## cyan
+    echo -e "${ESC}${BOLD_CYAN}IMPORTANT> $*${NORMAL}" >> $LOG_DEVICE ## cyan
   fi
   {
     shift
     RETURN=$1
-  } 2>/dev/null
+  } 2> /dev/null
 }
 
 problem.log() {
-  seq.puml.log 2>/dev/null
+  seq.puml.log 2> /dev/null
   if [ "$LOG_LEVEL" -gt "1" ]; then
     echo -e "${BOLD_RED}PROBLEM BREAKPOINT> $*${NORMAL}" #>>$LOG_DEVICE
     export STEP_DEBUG=ON
@@ -167,16 +164,16 @@ problem.log() {
 }
 
 debug.log() {
-  seq.puml.log 2>/dev/null
+  seq.puml.log 2> /dev/null
   if [ "$LOG_LEVEL" -gt "4" ]; then
-    echo -e "${BOLD_CYAN}- $*${NORMAL}" >>$LOG_DEVICE
+    echo -e "${BOLD_CYAN}- $*${NORMAL}" >> $LOG_DEVICE
   fi
 }
 
 stop.log() {
-  seq.puml.log 2>/dev/null
+  seq.puml.log 2> /dev/null
   if [ "$LOG_LEVEL" -gt "3" ]; then
-    echo -e "${BOLD_GREEN}BREAKPOINT> $*${NORMAL}" >>$LOG_DEVICE
+    echo -e "${BOLD_GREEN}BREAKPOINT> $*${NORMAL}" >> $LOG_DEVICE
     export STEP_DEBUG=ON
   fi
 }
@@ -192,7 +189,7 @@ err.log() {
 
   seq.puml.log
   if [ "$LOG_LEVEL" -gt 0 ]; then
-    echo -e "${BOLD_RED}ERROR> $*${NORMAL}" | tee -a ~/config/error.txt ~/config/result.txt >>$LOG_DEVICE
+    echo -e "${BOLD_RED}ERROR> $*${NORMAL}" | tee -a ~/config/error.txt ~/config/result.txt >> $LOG_DEVICE
   fi
 
   seq.puml.log
@@ -213,13 +210,13 @@ capture.log.silent() {
   clear.resultFiles
   important.log "capturing logs of:
    $*
-   
+
    use ${WHITE}log inspect${CYAN} in another shell to see whats going on.
 
    waiting for results...
    "
   #### write to console AND result.text AND write errors to errot.txt AND result.txt
-  "$@" >$CONFIG_PATH/result.txt 2> >(tee -a $CONFIG_PATH/result.txt $CONFIG_PATH/error.txt >&2)
+  "$@" > $CONFIG_PATH/result.txt 2> >(tee -a $CONFIG_PATH/result.txt $CONFIG_PATH/error.txt >&2)
   important.log "
    results ready in: $CONFIG_PATH/result.txt"
 }
@@ -313,7 +310,6 @@ log.level() { # <levelno> # switch to a specific log level
 
   # LOG_LEVEL=6
   # check.debug.level
-
 }
 
 log.device() { # <device:/root/log.out.txt> # set the log device
@@ -324,20 +320,17 @@ log.device() { # <device:/root/log.out.txt> # set the log device
   else
     important.log "LOG_DEVICE=$LOG_DEVICE"
   fi
-
 }
 
 log.init.colors() {
-
   if [ -z "$CONFIG_PATH" ]; then
-    warn.log "no color yet" >>/dev/tty
+    warn.log "no color yet" >> /dev/tty
     return 1
   fi
 
   if [ -f $CONFIG_PATH/setup.color.env ]; then
     source $CONFIG_PATH/setup.color.env
   fi
-
 }
 
 log.usage() {
diff --git a/old/debug b/old/debug
--- a/old/debug
+++ b/old/debug
@@ -3,25 +3,20 @@
 #export PS4='\e[90m+${LINENO} in ${current}: \e[0m'
 current=${BASH_SOURCE[0]}
 
-debug.version()              # prints out the hard coded version tag of $This 
-{
- console.log "$0 debug version: 20210626 20:45"
+debug.version() { # prints out the hard coded version tag of $This
+  console.log "$0 debug version: 20210626 20:45"
 }
 
+function step() {
+  {
+    set +x
+  } 2> /dev/null
 
-
-function step()
-{
-
-  { 
-      set +x
-  } 2>/dev/null
-
-    echo step on level $LOG_LEVEL
-    if [ -z "$LOG_LEVEL" ]; then
-        LOG_LEVEL=5
-        export PS4='\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
-    fi
+  echo step on level $LOG_LEVEL
+  if [ -z "$LOG_LEVEL" ]; then
+    LOG_LEVEL=5
+    export PS4='\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
+  fi
 
   if [ "$STEP_DEBUG" = "ON" ]; then
 
@@ -34,7 +29,7 @@ function step()
     if [[ ! "$CONT" = "" ]]; then
       case $CONT in
         h)
-            echo "
+          echo "
             h     this help
             e     expands variable in the command
             n     next command full with debug
@@ -57,136 +52,134 @@ function step()
             q     exit
                 all other commands exit too
             "
-            step
-            ;;
+          step
+          ;;
         s)
-            removeTrap
-            DEBUG=OFF
-            debug.log "DEBUG is OFF"
-            set +x
-            ;;
+          removeTrap
+          DEBUG=OFF
+          debug.log "DEBUG is OFF"
+          set +x
+          ;;
         n)
-            #removeTrap
-            DEBUG=ON
-            set -x
-            ;;
+          #removeTrap
+          DEBUG=ON
+          set -x
+          ;;
         x)
-            DEBUG=ON
-            removeTrap
-            set -x
-            ;;
+          DEBUG=ON
+          removeTrap
+          set -x
+          ;;
         c)
-            DEBUG=ON
-            removeTrap
-            set +x
-            ;;
+          DEBUG=ON
+          removeTrap
+          set +x
+          ;;
         e)
-            echo "> expands to: $(eval echo "$BASH_COMMAND")"
-            step
-            ;;
+          echo "> expands to: $(eval echo "$BASH_COMMAND")"
+          step
+          ;;
         r)
-            export STEP_TILL_NEXT_RETURN=ON
-            removeTrap
-            warn.log "continue till next Return"
-            step
-            ;;
+          export STEP_TILL_NEXT_RETURN=ON
+          removeTrap
+          warn.log "continue till next Return"
+          step
+          ;;
         t)
-            stackTrace
-            ;;
+          stackTrace
+          ;;
         ls)
-            ls -al
-            step 
-            ;;
+          ls -al
+          step
+          ;;
         d)
-            toggleDebug
-            step
-            ;;
+          toggleDebug
+          step
+          ;;
         p)
-            console.log "PATH=$PATH"
-            step
-            ;;
+          console.log "PATH=$PATH"
+          step
+          ;;
         ll)
-            pwd
-            ls -alF
-            step
-            ;;
+          pwd
+          ls -alF
+          step
+          ;;
         root)
-            tree -aL 2 /root
-            step
-            ;;
+          tree -aL 2 /root
+          step
+          ;;
         home)
-            tree -aL 2 /home
-            step
-            ;;
+          tree -aL 2 /home
+          step
+          ;;
         eamd)
-            tree -aL 2 /$defaultWorkspace/..
-            step
-            ;;
+          tree -aL 2 /$defaultWorkspace/..
+          step
+          ;;
         i)
-            eamd check
-            step
-            ;;
+          eamd check
+          step
+          ;;
         cd)
-            read -p 'cd to?   >' CD_DIR
-            cd $CD_DIR
-            step
-            ;;
+          read -p 'cd to?   >' CD_DIR
+          cd $CD_DIR
+          step
+          ;;
         cmd)
-            read -p 'command?  BE CAREFULL >' command
-            set -x
-            $command
-            step
-            ;;    
+          read -p 'command?  BE CAREFULL >' command
+          set -x
+          $command
+          step
+          ;;
         env)
-            read -p 'ENV VARIBALE NAME>' env
-            set -x
-            echo -e "\e[1;33mexport $env=${!env}\e[0m"
-            step
-            ;;          
+          read -p 'ENV VARIBALE NAME>' env
+          set -x
+          echo -e "\e[1;33mexport $env=${!env}\e[0m"
+          step
+          ;;
         *)
-            set +x
-            warn.log "FORCE EXIT because of command: $CONT"
-            exit 0
+          set +x
+          warn.log "FORCE EXIT because of command: $CONT"
+          exit 0
+          ;;
       esac
-    #else
+      #else
       #echo "ENTER: continue"
     fi
-  #else
+    #else
     #echo "Step Debug is $STEP_DEBUG"
   fi
- 
+
   if [ "$LOG_LEVEL" -gt "4" ]; then
     set -x
   else
-    { 
+    {
       set +x
-    } 2>/dev/null
+    } 2> /dev/null
   fi
-    
 }
 
 function stackTrace() {
-            i=0;
-            #for (( i=0; i<=${#BASH_LINENO[@]}; i++)); do
-            echo -e "\e[1;37m" 
-            for l in ${BASH_LINENO[@]}; do
-                printf "i: %2d  line: %6d  function: %-20s  file: %-30s   args: " "$i" "$l" "${FUNCNAME[$i]}()" "${BASH_SOURCE[$i]}"
-                echo "\"${BASH_ARGV[@]}\" and \"$@\""
-                ((i++))
-            done
-            echo -e "\e[0m"
-            step
+  i=0
+  #for (( i=0; i<=${#BASH_LINENO[@]}; i++)); do
+  echo -e "\e[1;37m"
+  for l in ${BASH_LINENO[@]}; do
+    printf "i: %2d  line: %6d  function: %-20s  file: %-30s   args: " "$i" "$l" "${FUNCNAME[$i]}()" "${BASH_SOURCE[$i]}"
+    echo "\"${BASH_ARGV[@]}\" and \"$@\""
+    ((i++))
+  done
+  echo -e "\e[0m"
+  step
 }
 
 function stepDebugger() {
-
   if [ "$1" = "OFF" ]; then
-      removeTrap
+    removeTrap
   fi
   if [ "$1" = "ON" ]; then
-      export STEP_DEBUG=ON
+    export STEP_DEBUG=ON
   fi
-
 }
 
 function setTrap() {
@@ -198,35 +191,34 @@ function setTrap() {
   #set -e
   trap 'onError ${?}' ERR
   trap 'onReturn ${?}' RETURN
-  trap 'onExit  ${?}' EXIT 
+  trap 'onExit  ${?}' EXIT
 }
 
 function checkTrace() {
-    case $- in
-        *x* ) 
-            echo "Trace is ON"
-            export TRACE=ON
-            ;;
-        * )               
-            echo "Trace is OFF"
-            export TRACE=OFF;
-            ;;
-    esac
+  case $- in
+    *x*)
+      echo "Trace is ON"
+      export TRACE=ON
+      ;;
+    *)
+      echo "Trace is OFF"
+      export TRACE=OFF
+      ;;
+  esac
 }
 
 function setTrace() {
-    case $TRACE in
-        ON ) 
-            set -x
-            export TRACE=ON
-            ;;
-        * )               
-            set +x
-            export TRACE=OFF
-            ;;
-    esac
+  case $TRACE in
+    ON)
+      set -x
+      export TRACE=ON
+      ;;
+    *)
+      set +x
+      export TRACE=OFF
+      ;;
+  esac
 }
-
 
 function removeTrap() {
   export STEP_DEBUG=OFF
@@ -234,70 +226,69 @@ function removeTrap() {
 }
 
 function ckeckDebug() {
-    setTrap
+  setTrap
 
-    source $OOSH_PATH/log
+  source $OOSH_PATH/log
 
-#   if [[ "$(basename -- "$0")" == "debug" ]]; then
-#     # called
-#     if [ -n "$1" ]; then
-#         export DEBUG=$1
-#         config save
-#     fi
-#     warn.log "debug has no effect if it was not sourced with . debug"
-#   else
-#     # sourced
-#     debug.log "debug was sourced from: $0"
-#     if [[ "$(basename -- "$0")" == "-bash" ]]; then
-#        debug.log "sourced from: bash"
-#        DEBUG=$1
-#     fi
-#   fi
+  #   if [[ "$(basename -- "$0")" == "debug" ]]; then
+  #     # called
+  #     if [ -n "$1" ]; then
+  #         export DEBUG=$1
+  #         config save
+  #     fi
+  #     warn.log "debug has no effect if it was not sourced with . debug"
+  #   else
+  #     # sourced
+  #     debug.log "debug was sourced from: $0"
+  #     if [[ "$(basename -- "$0")" == "-bash" ]]; then
+  #        debug.log "sourced from: bash"
+  #        DEBUG=$1
+  #     fi
+  #   fi
 
-
-#   if [ -n "$DEBUG" ]; then
-#     #echo "DEBUG was $DEBUG, and is now ON"
-#     case $DEBUG in
-#       X)
-#         set -x
-#         ;;
-#       OFF)
-#         unset DBEUG
-#         ;;
-#       *)
-#         export DEBUG=ON
-#     esac
-#   #else
-#     #echo "DEBUG is $DEBUG"
-#   fi
+  #   if [ -n "$DEBUG" ]; then
+  #     #echo "DEBUG was $DEBUG, and is now ON"
+  #     case $DEBUG in
+  #       X)
+  #         set -x
+  #         ;;
+  #       OFF)
+  #         unset DBEUG
+  #         ;;
+  #       *)
+  #         export DEBUG=ON
+  #     esac
+  #   #else
+  #     #echo "DEBUG is $DEBUG"
+  #   fi
 }
 
 function toggleDebug() {
-    if [ "ON" = "$DEBUG" ]; then 
-        DEBUG=OFF
-        #set +x
-    else
-        DEBUG=ON
-    fi
-    warn.log "Toggeld DEBUG to $DEBUG"
+  if [ "ON" = "$DEBUG" ]; then
+    DEBUG=OFF
+    #set +x
+  else
+    DEBUG=ON
+  fi
+  warn.log "Toggeld DEBUG to $DEBUG"
 }
 
 function onReturn() {
-    debug.log "function ${FUNCNAME[1]} returned with code: $1 and RETURN=$2"
-    if [ "$0" = "$2" ]; then
-        #do not stop when in this $0 debug file $2
-        return 0
-    fi
-    
-    if [ "ON" = "$STEP_TILL_NEXT_RETURN" ]; then 
-        STEP_TILL_NEXT_RETURN=OFF
-        export STEP_DEBUG=ON
-        #set +x
-    fi
-    #current.context
-#   if [ -z "$2" ]; then
-#     RETURN=$2
-#   fi
+  debug.log "function ${FUNCNAME[1]} returned with code: $1 and RETURN=$2"
+  if [ "$0" = "$2" ]; then
+    #do not stop when in this $0 debug file $2
+    return 0
+  fi
+
+  if [ "ON" = "$STEP_TILL_NEXT_RETURN" ]; then
+    STEP_TILL_NEXT_RETURN=OFF
+    export STEP_DEBUG=ON
+    #set +x
+  fi
+  #current.context
+  #   if [ -z "$2" ]; then
+  #     RETURN=$2
+  #   fi
 }
 
 function onError() {
@@ -307,12 +298,12 @@ function onError() {
     return
   fi
 
-    error.log         "function ${FUNCNAME[1]} in line: ${BASH_LINENO[2]} returned with ERROR code: $1"
-    if [ "ON" = "$DEBUG" ]; then
-      export STEP_DEBUG=
-      stackTrace
-      export STEP_DEBUG=ON
-    fi
+  error.log "function ${FUNCNAME[1]} in line: ${BASH_LINENO[2]} returned with ERROR code: $1"
+  if [ "ON" = "$DEBUG" ]; then
+    export STEP_DEBUG=
+    stackTrace
+    export STEP_DEBUG=ON
+  fi
 }
 
 function onExit() {
@@ -320,55 +311,60 @@ function onExit() {
 }
 
 debug.log() {
-    if [ "$LOG_LEVEL" -gt "3" ]; then
-        #test -t 1 && tput setf 7     
-        echo -e "\e[1;36m- $@\e[0m"
-        #echo "- $@"
-        #test -t 1 && tput sgr0 # Reset terminal
-    fi
+  if [ "$LOG_LEVEL" -gt "3" ]; then
+    #test -t 1 && tput setf 7
+    echo -e "\e[1;36m- $@\e[0m"
+    #echo "- $@"
+    #test -t 1 && tput sgr0 # Reset terminal
+  fi
 }
 
 console.log() {
-    #test -t 1 && tput bold; tput setf 7                                            ## white bold
-    if [ "$LOG_LEVEL" -gt "2" ]; then
-        echo -e "\e[0m>  $@"
-    fi
-    #test -t 1 && tput sgr0 # Reset terminal
+  #test -t 1 && tput bold; tput setf 7                                            ## white bold
+  if [ "$LOG_LEVEL" -gt "2" ]; then
+    echo -e "\e[0m>  $@"
+  fi
+  #test -t 1 && tput sgr0 # Reset terminal
 }
+
 error.log() {
-    err.log "$@"
+  err.log "$@"
 }
+
 err.log() {
-    #test -t 1 && tput bold; tput setf 4  
-    #echo "ERROR>  $@"
-    echo -e "\e[1;31mERROR> $@\e[0m"    
-    #test -t 1 && tput sgr0 # Reset terminal
-    if [ "ON" = "$DEBUG" ]; then 
-        export STEP_DEBUG=ON
-    fi   
+  #test -t 1 && tput bold; tput setf 4
+  #echo "ERROR>  $@"
+  echo -e "\e[1;31mERROR> $@\e[0m"
+  #test -t 1 && tput sgr0 # Reset terminal
+  if [ "ON" = "$DEBUG" ]; then
+    export STEP_DEBUG=ON
+  fi
 }
+
 warn.log() {
-    #test -t 1 && tput bold; tput setf 6
-    if [ "$LOG_LEVEL" -gt "1" ]; then
-        echo -e "\e[1;33m> WARNING $@\e[0m"                                    ## yellow
-    fi
-    #test -t 1 && tput sgr0 # Reset terminal
+  #test -t 1 && tput bold; tput setf 6
+  if [ "$LOG_LEVEL" -gt "1" ]; then
+    echo -e "\e[1;33m> WARNING $@\e[0m" ## yellow
+  fi
+  #test -t 1 && tput sgr0 # Reset terminal
 }
+
 stop.log() {
-    if [ "$LOG_LEVEL" -gt "4" ]; then
-        #test -t 1 && tput bold; tput setf 6                                    ## green
-        #echo "BREAKPOINT> $@"
-        echo -e "\e[1;32mBREAKPOINT> $@\e[0m" 
-        #test -t 1 && tput sgr0 # Reset terminal
-        export STEP_DEBUG=ON
-    fi  
+  if [ "$LOG_LEVEL" -gt "4" ]; then
+    #test -t 1 && tput bold; tput setf 6                                    ## green
+    #echo "BREAKPOINT> $@"
+    echo -e "\e[1;32mBREAKPOINT> $@\e[0m"
+    #test -t 1 && tput sgr0 # Reset terminal
+    export STEP_DEBUG=ON
+  fi
 }
+
 success.log() {
-    #if [ "ON" = "$DEBUG" ]; then 
-    if [ "$LOG_LEVEL" -gt "1" ]; then
-        echo -e "\e[1;32mSUCCESS> $@\e[0m" 
-    fi
-    #fi  
+  #if [ "ON" = "$DEBUG" ]; then
+  if [ "$LOG_LEVEL" -gt "1" ]; then
+    echo -e "\e[1;32mSUCCESS> $@\e[0m"
+  fi
+  #fi
 }
 
 ckeckDebug "$@"
diff --git a/this b/this
--- a/this
+++ b/this
@@ -6,13 +6,11 @@
 export PS4='\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
 if [ -n "$SH_OPT" ]; then set $SH_OPT; fi # force debug
 
-
 if [ -z "$LOG_LEVEL" ]; then
   export LOG_LEVEL=3
   #export LOG_DEVICE=/dev/stdout
   export LOG_DEVICE=/dev/tty
 fi
-
 
 if [ -z "$EXPECTED_RETURN_VALUE" ]; then
   export EXPECTED_RETURN_VALUE=1
@@ -22,9 +20,11 @@ if [ "$EXPECTED_RETURN_VALUE" -lt 1 ]; then
   export EXPECTED_RETURN_VALUE=1
 fi
 
-
 if [ -z "$OOSH_DIR" ]; then
-  OOSH_DIR=$( cd "$(dirname ${BASH_SOURCE[0]})" ; pwd ) 
+  OOSH_DIR=$(
+    cd "$(dirname ${BASH_SOURCE[0]})"
+    pwd
+  )
   if [ "$OOSH_DIR" = "." ]; then
     OOSH_DIR=$(pwd)
   fi
@@ -36,19 +36,18 @@ fi
 
 info.log() {
   if [ "$LOG_LEVEL" -gt "3" ]; then
-    echo -e "\e[90mINFO> $*\e[0m" >>$LOG_DEVICE ## normal
+    echo -e "\e[90mINFO> $*\e[0m" >> $LOG_DEVICE ## normal
   fi
 }
 
 this.isNumber() {
   case $1 in
-  '' | *[!0-9]*) return 1 ;;
-  *) return 0 ;;
+    '' | *[!0-9]*) return 1 ;;
+    *) return 0 ;;
   esac
 }
 
 this.functionExists() {
-
   local startFunc="$1"
   shift
   RETURN=$1
@@ -60,7 +59,7 @@ this.functionExists() {
     info.log "$startFunc does not exist"
     return 1
   fi
-} 2>/dev/null
+} 2> /dev/null
 
 if (this.functionExists this.load); then
   info.log "this was already sourced"
@@ -114,7 +113,7 @@ check.debug.level() {
   else
     {
       set +x
-    } 2>/dev/null
+    } 2> /dev/null
   fi
   #set -x
 } #2>/dev/null
@@ -154,7 +153,6 @@ this.init() {
     #   #source $OOSH_DIR/../config/user.env
     #   #config.save
 
-
     #   this.path.add "$OOSH_DIR"
     #   this.path.add "$OOSH_DIR/ng"
     #   this.path.add "$OOSH_DIR/external"
@@ -185,61 +183,58 @@ this.init() {
   fi
 }
 
-create.result() # <processRETURN_VALUE:0> <RESULT:all went well> <option:$1> # creates a process return value and a function RESULT that been be returned in the calling function
-# to make create result work, you have to call a SOURCED function
-# e.g.  if os.check some.function; then ...
-#   if you call 'os check' from th scrip 'os', it cannot return a RESULT since the porcess will end and no RESULT is left...
-#   if you call 'os.check' you have to source the script oo before: 
-#       source oo
-# Then $RESULT will be in the same process and can be read from the calling function
-#   otherwise if you call 'os check' you have to call:
-#      create.result ERROR_CODE "some RSULT value" save
-# <option> can be 'save' then you can retrieve the result with
-#      result.load
-# in the calling function.
-# normaly <option> should always be "$1" to mark the start of the next command
-{
+create.result() { # <processRETURN_VALUE:0> <RESULT:all went well> <option:$1> # creates a process return value and a function RESULT that been be returned in the calling function
+  # to make create result work, you have to call a SOURCED function
+  # e.g.  if os.check some.function; then ...
+  #   if you call 'os check' from th scrip 'os', it cannot return a RESULT since the porcess will end and no RESULT is left...
+  #   if you call 'os.check' you have to source the script oo before:
+  #       source oo
+  # Then $RESULT will be in the same process and can be read from the calling function
+  #   otherwise if you call 'os check' you have to call:
+  #      create.result ERROR_CODE "some RSULT value" save
+  # <option> can be 'save' then you can retrieve the result with
+  #      result.load
+  # in the calling function.
+  # normaly <option> should always be "$1" to mark the start of the next command
 
   RETURN_VALUE=$1
   shift
   RESULT=$1
   shift
   RETURN=$1
-  
 
   if ! (this.isNumber "$RETURN_VALUE"); then
     export RESULT=$RETURN_VALUE
     RETURN_VALUE=0
   fi
-  
+
   info.log "create.result: $RETURN_VALUE $RESULT"
-  if [ "$RETURN" = "save" ]; then    
+  if [ "$RETURN" = "save" ]; then
     shift
     RETURN=$1
     result.save "$@"
     info.log "result saved"
   fi
   info.log "next argument: $RETURN"
-  
+
   # if ! (this.isSourced); then
   #   important.log "show RESULT: $RESULT"
   # fi
 }
 
 result() {
-  if [ "$1" = "save" ]; then    
+  if [ "$1" = "save" ]; then
     shift
     result.save "$@"
     RETURN=$1
   fi
   if [ -z "$RETURN_VALUE" ]; then
     RETURN_VALUE=0
-  fi 
+  fi
   echo $RETURN_VALUE
 }
 
-result.save()
-{
+result.save() {
   export RESULT_RETURN_VALUE=$RETURN_VALUE
   export RESULT=$RESULT
 
@@ -250,7 +245,7 @@ result.save()
   export RESULT_NEXT_ARGS="$*"
   {
     declare -px | grep "RESULT"
-  } >$CONFIG_PATH/result.env
+  } > $CONFIG_PATH/result.env
 }
 
 result.cat() { # # logs the $CONFIG_PATH/result.env file
@@ -265,14 +260,13 @@ result.view() { # # alias to result.cat
   result.cat
 }
 
-result.load()
-{
+result.load() {
   source $CONFIG_PATH/result.env
 }
 
 result.into() { # <shellVarname> <?method> #
-  export $1="$( cat - )"
-  echo "$1=${!1}" >$CONFIG_PATH/result.env
+  export $1="$(cat -)"
+  echo "$1=${!1}" > $CONFIG_PATH/result.env
   # if [ -n "$2" ]; then
   #   "$@"
   # fi
@@ -288,8 +282,7 @@ this.scope.full() {
   this.scope
 }
 
-this.absolutePathName()     # <?path:"."> <?option:"pipe"> echos the absolut path if started else it just puts it into $RESTULT
-{
+this.absolutePathName() { # <?path:"."> <?option:"pipe"> echos the absolut path if started else it just puts it into $RESTULT
   local file=$1
   shift
 
@@ -306,12 +299,13 @@ this.absolutePathName()     # <?path:"."> <?option:"pipe"> echos the absolut pat
     dir="$(dirname "$file")"
   fi
   debug.log "local dir: $dir"
-  path=$(cd $dir; pwd) 
+  path=$(
+    cd $dir
+    pwd
+  )
   local name="$(basename $file)"
-    
 
   create.result 0 "$path/$name" "$1"
-
 
   if ! (this.isSourced); then
     if [ -n "$1" ]; then
@@ -324,8 +318,7 @@ this.absolutePathName()     # <?path:"."> <?option:"pipe"> echos the absolut pat
   fi
 }
 
-this.absolutePath()     # <?path:"."> <?option:"pipe"> echos the absolut path if started else it just puts it into $RESTULT
-{
+this.absolutePath() { # <?path:"."> <?option:"pipe"> echos the absolut path if started else it just puts it into $RESTULT
   local file=$1
   shift
 
@@ -352,11 +345,12 @@ this.absolutePath()     # <?path:"."> <?option:"pipe"> echos the absolut path if
     dir=$(dirname "$file")
   fi
   info.log "local dir: $dir"
-  path=$( cd "$dir" ; pwd ) 
-    
+  path=$(
+    cd "$dir"
+    pwd
+  )
 
   create.result "$path" "$1"
-
 
   if ! (this.isSourced); then
     if [ "$1" = "pipe" ]; then
@@ -383,17 +377,16 @@ this.caller() {
   info.log "script: $0"
   info.log "caller: $caller"
   info.log "source stack: ${BASH_SOURCE[*]##*/}"
-  create.result "$caller" "$1" 
+  create.result "$caller" "$1"
 }
 
 this.caller.function() {
   local function=${FUNCNAME[1]}
   info.log "function stack: ${FUNCNAME[*]}"
-  create.result "$function" "$1" 
+  create.result "$function" "$1"
 }
 
-this.call() # <aFunction> <?aShellScript> # loads <aFunction> from a <aShellScript>
-{
+this.call() { # <aFunction> <?aShellScript> # loads <aFunction> from a <aShellScript>
   local aFunction=$1
   shift
 
@@ -407,7 +400,7 @@ this.call() # <aFunction> <?aShellScript> # loads <aFunction> from a <aShellScri
     debug.log "this.call: $aFunction $*"
     $aFunction "$@"
     return "$?"
-  #else
+    #else
     #info.log "$aFunction does not exist!"
   fi
   if (this.functionExists $caller.$aFunction); then
@@ -448,10 +441,7 @@ this.call() # <aFunction> <?aShellScript> # loads <aFunction> from a <aShellScri
   fi
 } #2>/dev/null
 
-
-
 this.path.add() {
-
   # if ! this.functionExists "line.add"; then
   #   source line
   # fi
@@ -478,15 +468,14 @@ this.path.add() {
     #set -x
   fi
 
-    echo $PATH \
-  | line.split ":" \
-  | line.quote \
-  | line.remove "$currentPath" \
-  | line.prepend "$1" \
-  | line.join ":" \
-  | line.into PATH
+  echo $PATH \
+    | line.split ":" \
+    | line.quote \
+    | line.remove "$currentPath" \
+    | line.prepend "$1" \
+    | line.join ":" \
+    | line.into PATH
 
-  
   # source $CONFIG_PATH/result.env
   # shift
 
@@ -500,7 +489,6 @@ this.path.add() {
   #export PATH="$1:$RESULT"
 }
 
-
 this.help.table() {
   #echo $@
   local from="$1"
@@ -512,12 +500,12 @@ this.help.table() {
   fi
   shift
   cat "$from" \
-  | line find "\(\) " "$" \
-  | sed 's/() //'  \
-  | sed 's/{//' \
-  | sed "s/^$this.//" \
-  | grep "$1" \
-  | line table '#' 
+    | line find "\(\) " "$" \
+    | sed 's/() //' \
+    | sed 's/{//' \
+    | sed "s/^$this.//" \
+    | grep "$1" \
+    | line table '#'
 }
 
 this.help() {
@@ -534,25 +522,23 @@ this.help() {
   shift
 
   cat "$from" \
-  | line.find "\(\)" "\{" \
-  | line.filter "^#" \
-  | line.filter "^{" \
-  | line.filter "\.completion" \
-  | line.filter "^private" \
-  | line.quote \
-  | sort \
-  | grep "$this\.$1" \
-  | line.prepend "'=========== # =========== # ==========='" \
-  | line.prepend "'METHOD # PARAMETER # DESCRIPTION'" \
-  | line.unify '#' " no name" " ${GRAY}none" " ${GRAY}please add a description" \
-  | line.trim.quoted \
-  | line.replace "\([^ ]\)()" "\1" \
-  | line.replace " {" \
-  | line.replace "$this\." \
-  | line.format FORMAT_HELP 
+    | line.find "\(\)" "\{" \
+    | line.filter "^#" \
+    | line.filter "^{" \
+    | line.filter "\.completion" \
+    | line.filter "^private" \
+    | line.quote \
+    | sort \
+    | grep "$this\.$1" \
+    | line.prepend "'=========== # =========== # ==========='" \
+    | line.prepend "'METHOD # PARAMETER # DESCRIPTION'" \
+    | line.unify '#' " no name" " ${GRAY}none" " ${GRAY}please add a description" \
+    | line.trim.quoted \
+    | line.replace "\([^ ]\)()" "\1" \
+    | line.replace " {" \
+    | line.replace "$this\." \
+    | line.format FORMAT_HELP
 }
-
-
 
 this.isSourced() {
   # test.isSourced this.isSourced \ this.isSourced main                                               => called by main            and started
@@ -565,52 +551,51 @@ this.isSourced() {
   callerFunction=${FUNCNAME[1]}
 
   case $callerFunction in
-  "main") #started
-    create.result 1 "started by $callerFunction in $caller"
-    ;;
-  "this.call") #called therfore sourced
-    create.result 0 "sourced because called by $callerFunction in $caller"
-    ;;
-  "this.start") #started depending on command [3]
-    if [ "${FUNCNAME[3]}" = "source" ]; then
-      create.result 0 "sourced because called by $callerFunction in $caller" >/dev/null
-    else
-      create.result 1 "started by ${FUNCNAME[4]} in ${BASH_SOURCE[4]##*/}" >/dev/null
-    fi
-    ;;
-  *) #called therfore sourced
-    if [ "${0##*/}" = "$caller" ]; then
-      create.result 1 "started because $caller is $0" >/dev/null
-    else
-      create.result 0 "sourced because called by $callerFunction in $caller" >/dev/null
-    fi
+    "main") #started
+      create.result 1 "started by $callerFunction in $caller"
+      ;;
+    "this.call") #called therfore sourced
+      create.result 0 "sourced because called by $callerFunction in $caller"
+      ;;
+    "this.start") #started depending on command [3]
+      if [ "${FUNCNAME[3]}" = "source" ]; then
+        create.result 0 "sourced because called by $callerFunction in $caller" > /dev/null
+      else
+        create.result 1 "started by ${FUNCNAME[4]} in ${BASH_SOURCE[4]##*/}" > /dev/null
+      fi
+      ;;
+    *) #called therfore sourced
+      if [ "${0##*/}" = "$caller" ]; then
+        create.result 1 "started because $caller is $0" > /dev/null
+      else
+        create.result 0 "sourced because called by $callerFunction in $caller" > /dev/null
+      fi
+      ;;
   esac
   info.log "return result $(result)"
   return $(result)
 }
 
 # shellcheck disable=SC2120
-this.restart()
-{
-    important.log "exited back into this $STARTED: exit code: $RETURN_VALUE"
-    unset STARTED
-    export STARTED
+this.restart() {
+  important.log "exited back into this $STARTED: exit code: $RETURN_VALUE"
+  unset STARTED
+  export STARTED
 
-    if [ -z "$RETURN_VALUE" ]; then
-      important.log "no return value set....propably on MacOS...mitigating"
-      source ~/config/result.env
-      export RETURN_VALUE=$RESULT_RETURN_VALUE
-      important.log "found RETURN_VALUE=$RETURN_VALUE"
-    fi
+  if [ -z "$RETURN_VALUE" ]; then
+    important.log "no return value set....propably on MacOS...mitigating"
+    source ~/config/result.env
+    export RETURN_VALUE=$RESULT_RETURN_VALUE
+    important.log "found RETURN_VALUE=$RETURN_VALUE"
+  fi
 
-    if [ "$1" = "again" ] || [ "$RETURN_VALUE" -eq "$ERROR_CODE_RECONFIG" ] ; then 
-      echo "
+  if [ "$1" = "again" ] || [ "$RETURN_VALUE" -eq "$ERROR_CODE_RECONFIG" ]; then
+    echo "
       restarting again $?
       "
-      $OOSH_DIR/this restart
-    fi
+    $OOSH_DIR/this restart
+  fi
 }
-
 
 this.start() {
   local len=${#BASH_LINENO[@]}
@@ -632,57 +617,55 @@ this.start() {
     fi
   fi
 
-
   while [ -n $1 ]; do
     info.log "start 1: -$1-"
     case $1 in
-    # call)
-    #   shift
-    #   "$@"
-    #   ;;
-    # discover)
-    #   once.discover
-    #   if [ "$ONCE_STATE" = "disvocer" ]; then
-    #     ONCE_STATE=check.installation
-    #     once.stage
-    #   fi
-    #   ;;
-    start)
-      stop.log "once start"
-      once.server.start "$@"
-      ;;
-    '')
-      debug.log "$0: EXIT"
-      #exit 0
-      return $RETURN_VALUE
-      ;;
-    help*)
-      this.$1 $This "$@"
-      ;;
-    localInstall)
-      echo "local install mode"
-      ;;
-    restart)
-      if [ -z "$BASH_FILE" ]; then
-        export BASH_FILE="$(which bash)"
-      fi
-      echo "restarting $BASH_FILE: $RETURN_VALUE = $ERROR_CODE_RECONFIG"
+      # call)
+      #   shift
+      #   "$@"
+      #   ;;
+      # discover)
+      #   once.discover
+      #   if [ "$ONCE_STATE" = "disvocer" ]; then
+      #     ONCE_STATE=check.installation
+      #     once.stage
+      #   fi
+      #   ;;
+      start)
+        stop.log "once start"
+        once.server.start "$@"
+        ;;
+      '')
+        debug.log "$0: EXIT"
+        #exit 0
+        return $RETURN_VALUE
+        ;;
+      help*)
+        this.$1 $This "$@"
+        ;;
+      localInstall)
+        echo "local install mode"
+        ;;
+      restart)
+        if [ -z "$BASH_FILE" ]; then
+          export BASH_FILE="$(which bash)"
+        fi
+        echo "restarting $BASH_FILE: $RETURN_VALUE = $ERROR_CODE_RECONFIG"
 
-
-      if [ "$RETURN_VALUE" -eq "$ERROR_CODE_RECONFIG" ]; then
-        export SHELL=$BASH_FILE
-        $BASH_FILE #-x # force debug
+        if [ "$RETURN_VALUE" -eq "$ERROR_CODE_RECONFIG" ]; then
+          export SHELL=$BASH_FILE
+          $BASH_FILE #-x # force debug
+          RETURN_VALUE=$?
+          #      this.restart again
+        else
+          echo "finally exiting oosh"
+        fi
+        ;;
+      *)
+        debug.log "this.call to: $*"
+        this.call "$@"
         RETURN_VALUE=$?
-        #      this.restart again
-      else
-        echo "finally exiting oosh"
-      fi
-      ;;
-    *)
-      debug.log "this.call to: $*"
-      this.call "$@"
-      RETURN_VALUE=$?
-    #  ;;
+        ;;
     esac
 
     shift
@@ -706,7 +689,6 @@ this.start() {
   return $RETURN_VALUE
 }
 
-
 ###################################
 info.log "
 still in ${BASH_SOURCE[0]##*/}
@@ -715,10 +697,8 @@ still in ${BASH_SOURCE[0]##*/}
 
 this.init
 
-
-
 case "${0##*/}" in
-  "init"|"oosh"|"log"|"this")
+  "init" | "oosh" | "log" | "this")
     #source $OOSH_DIR/loop
     #LOG_LEVEL=6
     this.path.add "$OOSH_DIR/external"
@@ -733,22 +713,17 @@ case "${0##*/}" in
 
     if [ -n "$OOSH_CONFIG_NEEDS_SAVE" ]; then
       unset OOSH_CONFIG_NEEDS_SAVE
-      source $OOSH_DIR/config 
+      source $OOSH_DIR/config
       config.save
     fi
-  ;;
-  "config"|"loop")
+    ;;
+  "config" | "loop")
     info.log "  running ${0##*/}"
-  ;;
+    ;;
   *)
     info.log "  running unknown ${0##*/}"
-  ;;
+    ;;
 esac
-
-
-
-
-
 
 if (this.isSourced); then
   info.log "this was sourced"
@@ -756,21 +731,20 @@ if (this.isSourced); then
 
 else
   if [ -z "$STARTED" ]; then
-    echo "this was started as $0" 
-
+    echo "this was started as $0"
 
     case "${0##*/}" in
-      "init"|"oosh"|"log"|"this")
+      "init" | "oosh" | "log" | "this")
         #source $OOSH_DIR/loop
         #LOG_LEVEL=6
         info.log "  running ${0##*/}"
-      ;;
-      "config"|"loop")
+        ;;
+      "config" | "loop")
         info.log "  running ${0##*/}"
-      ;;
+        ;;
       *)
         info.log "  running unknown ${0##*/}"
-      ;;
+        ;;
     esac
 
     if ! [ -f $OOSH_DIR/init/once ]; then
@@ -781,18 +755,17 @@ else
     if [ -z "$BASH_FILE" ]; then
       export BASH_FILE="$(which bash)"
       #   echo "BASH_FILE was not set"
-      # else 
+      # else
       #   echo "BASH_FILE is set to: $BASH_FILE"
     fi
     echo running bash with following settings
     echo -------------------------------------
-    echo  OOSH_DIR=$OOSH_DIR
-    echo      PATH=$PATH
+    echo OOSH_DIR=$OOSH_DIR
+    echo PATH=$PATH
     echo BASH_FILE=$BASH_FILE
-    echo    CONFIG=$CONFIG
+    echo CONFIG=$CONFIG
     echo ARGUMENTS=$*
     echo -------------------------------------
-
 
     if [ -n "$1" ]; then
       echo using arguments $*
@@ -806,19 +779,15 @@ else
     export EXPECTED_RETURN_VALUE=117
 
     # TDOD move into this start?
-    if [ "$1" = "localInstall" ]; then 
+    if [ "$1" = "localInstall" ]; then
 
-        oo state
-        # HACK needed to get the package manager right for the first time
-        user get home
-        # crashed the state next otherwise 
+      oo state
+      # HACK needed to get the package manager right for the first time
+      user get home
+      # crashed the state next otherwise
 
+      important.log "
 
-
-
-
-        important.log "
-        
         still during oosh installation
 
         continue with:
@@ -832,13 +801,12 @@ else
     $BASH_FILE #-x # force debug
     this.restart
 
-
   else
     if [ -z "$1" ]; then
       console.log "
       ${GREEN}oosh is already started $GRAY(shell level: $SHLVL)$NORMAL
-      
-      Welcome to 4.0 again      
+
+      Welcome to 4.0 again
       "
     else
       important.log "starting this with: $@"
