backup diff fills result and error.txt correctly

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -18,7 +18,30 @@ $0
 
       usage     prints this dialog while it will print the status when tehere are no parameters          
       v         print version information
-      init      initializes ...nothing yet
+      
+      list
+      list.config
+      config.list      lists the configuration
+
+      to               <directory> sets the backup target directory                 and saves the configuration
+      from             <directory> sets the root source directroy to be backuped    and saves the configuration
+      strategy         stes the startegy.... use Tab Completion to find out values  and saves the configuration
+
+      diff             <?directory> compares SOURCE/<?directory> to TARGET/<?directory> ${RED}not recursively...only flat${NORMAL}
+      full.diff        same but recursively  ${yellow}can tike some time${NORMAL}
+
+      inspect          inspects the current backup process log file so that yo can follow a long lasting process
+
+      list.last.diff.result     all following command work on the last result 
+      list.last.result.raw
+
+      list.notBackuped
+      list.onlyInSource
+
+      list.onlyInBackup
+      list.onlyInTarget
+
+      list.same         user Tab Completion to prevent the warning
   
   Examples
     $this v
@@ -49,8 +72,38 @@ backup.strategy() {
 }
 
 backup.strategy.completion() {
-  echo -e "full \\nincremental \\nsecureMove \\nreplace±ByLinks " | grep "^$1" 
+  echo -e "full \\nincremental \\nsecureMove \\nreplaceByFolderLinks " | grep "^$1" 
 }
+
+backup.capture.log.mode() {
+  export BACKUP_CAPTURE_LOG_MODE="$1"
+  shift
+  private.check.log.mode
+
+  backup.config.save
+  RETURN="$1"
+}
+
+private.check.log.mode() {
+  case "$BACKUP_CAPTURE_LOG_MODE" in
+    "full")
+      export BACKUP_CAPTURE_LOG_COMMAND="capture.log"
+      ;;
+    "silent")
+      export BACKUP_CAPTURE_LOG_COMMAND="capture.log.silent"
+      ;;
+    "none"|"screen")
+      export BACKUP_CAPTURE_LOG_COMMAND=""
+      ;;
+  esac
+}
+
+backup.capture.log.mode.completion() {
+  echo -e "full \\nsilent \\nnone \\nscreen " | grep "^$1" 
+}
+
+
+
 
 backup.from.completion() {
   compgen -o nospace -o dirnames  "$1" | grep "^$1" 
@@ -60,13 +113,10 @@ backup.to.completion() {
   private.complete.folders "$1"
 }
 
-private.complete.folders() {
-  compgen -o dirnames "$1" | grep "^$1" 
-}
 
 private.complete.folders() {
   #https://unix.stackexchange.com/questions/151118/understand-compgen-builtin-command
-  compgen -o dirnames "$1" 
+  compgen -o dirnames "$1" | grep "^$1" 
 }
 
 backup.config.list() {
@@ -83,14 +133,19 @@ backup.diff() {
   local backup_source="${BACKUP_SOURCE/\//}"
   debug.log "backup_source: $backup_source"
   
-  local path="${1/\//}"
+  backup.get.backupPath "$1"
+  local path="$RESULT"
+
   debug.log "path: $path"
 
   if [ "$backup_source/" = "//" ]; then
     backup_source=""
   fi
   debug.log "backup_source after : $backup_source"
-  diff -q --brief "$backup_source/$path" "$BACKUP_TARGET/$path" >$CONFIG_PATH/result.txt
+  
+  $BACKUP_CAPTURE_LOG_COMMAND diff -q --brief "$backup_source/$path" "$BACKUP_TARGET/$path"
+  #diff -q --brief "$backup_source/$path" "$BACKUP_TARGET/$path" > >(tee -a $CONFIG_PATH/result.txt) 2> >(tee -a $CONFIG_PATH/result.txt $CONFIG_PATH/error.txt >&2)
+
   backup.list.last.diff.result
 }
 
@@ -106,19 +161,28 @@ backup.full.diff() {
   if [ "$backup_source/" = "//" ]; then
     backup_source=""
   fi
-  debug.log "backup_source after : $backup_source"
-  diff -qr --brief "$backup_source/$path" "$BACKUP_TARGET/$path" >$CONFIG_PATH/result.txt
-  backup.list.last.diff.result
+  debug.log "backup_source after : $backup_source"               # write to console AND result.text AND wite errors to errot.txt AND result.txt
+  $BACKUP_CAPTURE_LOG_COMMAND diff -qr --brief "$backup_source/$path" "$BACKUP_TARGET/$path" > >(tee -a $CONFIG_PATH/result.txt) 2> >(tee -a $CONFIG_PATH/result.txt $CONFIG_PATH/error.txt >&2)
+  backup.list.last.diff.result no-warn
 }
 
 backup.inspect() {
   tail -f $CONFIG_PATH/result.txt
 }
 
+backup.list.errors() {
+  cat $CONFIG_PATH/error.txt | xargs -I {} printf "$RED%s\n" {}
+  console.log "$NORMAL"
+}
+
+backup.list.last.result.raw() {
+  cat $CONFIG_PATH/result.txt
+}
+
 backup.list.last.diff.result() {
   backup.list.onlyInSource
   backup.list.onlyInTarget
-  backup.list.common
+  backup.list.same "$1"
 }
 
 backup.list.onlyInSource() {
@@ -152,6 +216,53 @@ backup.list.same() {
   console.log "$NORMAL"
 }
 
+backup.replace.same.with.folderLinks() {
+  backup.list.same no-warn | sed 's/\(Common subdirectories: \)\(.*\)\( and \)\(.*\)/private.replace.by.folderLink \"\4\" \"\2\"\n/' | xargs
+}
+
+backup.replace.by.folderLink() {
+  backup.get.backupPath "$1" >/dev/null
+
+  local backup_source="${BACKUP_SOURCE/\//}"
+  info.log "Path absolute local: $backup_source/$RESULT"
+  info.log "Path      in Backup: $backup_source/$RESULT"
+  private.replace.by.folderLink $BACKUP_TARGET/$RESULT $backup_source/$RESULT
+
+}
+
+backup.replace.by.folderLink.completion() {
+    compgen -o dirnames "$1" | grep "^$1" 
+}
+
+private.replace.by.folderLink() {
+  mv "${2}" "${2}.isBackuped"
+  ln -s "$1" "${2}.lnk"
+  ln -s "$1" "${2}"
+  important.log "Please check result:"
+  ls -al "$2/.."
+}
+
+backup.get.backupPath() {
+  local path="$1"
+  if [ -z "$path" ]; then
+    path="."
+  fi
+
+  this.absolutePath "$path"
+  local path=$RESULT
+
+  info.log "$1 system absolute path: $path"
+
+  export RESULT=${path/$BACKUP_SOURCE/}
+  info.log "$1 backup relative path: $RESULT"
+  echo $RESULT
+}
+
+backup.get.backupPath.completion() {
+    compgen -o dirnames "$1" | grep "^$1" 
+}
+
+
 backup.list.same.completion() {
   echo -e "no-warn-for-pipe" | grep "^$1" 
 }
@@ -182,6 +293,11 @@ backup.list.config() {
   console.log "${NORMAL}Strategy:
   ${WHITE}$BACKUP_STRATEGY${NORMAL}
   "
+
+
+  console.log "${NORMAL}Log Capture Mode:
+  ${WHITE}$BACKUP_CAPTURE_LOG_MODE${NORMAL}
+  "
 }
 
 backup.start()
@@ -189,6 +305,7 @@ backup.start()
   #echo "sourcing init"
   source this
   source $CONFIG_PATH/backup.env
+  private.check.log.mode
   #source config
 
   # if [ -z "$1" ]; then
diff --git a/log b/log
--- a/log
+++ b/log
@@ -28,7 +28,7 @@ fi
 console.log()
 {
   if [ "$LOG_LEVEL" -gt "2" ]; then
-    echo -e "${ESC}0m$*"
+    echo -e "${ESC}0m$*" 
   fi
 }
 
@@ -59,7 +59,7 @@ error.details.log() {
 warn.log()
 {
     if [ "$LOG_LEVEL" -gt "1" ]; then
-        echo -e "${BOLD};33m> WARNING $*\033[0m"                                    ## yellow
+        echo -e "${BOLD};33m> WARNING $*\033[0m" | tee -a $CONFIG_PATH/error.txt >>$CONFIG_PATH/result.txt                               ## yellow
     fi
     {
       shift
@@ -105,13 +105,71 @@ error.log() {
 }
 err.log() {
 
-    if [ "$LOG_LEVEL" -gt 0 ]; then   
-      echo -e "${BOLD};31mERROR> $*\033[0m"    
+    if [ "$LOG_LEVEL" -gt 0 ]; then
+       echo -e "${BOLD};31mERROR> $*\033[0m" | tee -a $CONFIG_PATH/error.txt $CONFIG_PATH/result.txt     
     fi
 
     if [ "$LOG_LEVEL" -gt "4" ]; then   
         export STEP_DEBUG=ON
     fi   
+}
+
+capture.log() {
+  clear.resultFiles
+  important.log "capturing logs of:
+   $*"
+   #### write to console AND result.text AND wite errors to errot.txt AND result.txt
+   "$@" > >(tee -a $CONFIG_PATH/result.txt) 2> >(tee -a $CONFIG_PATH/result.txt $CONFIG_PATH/error.txt >&2)
+}
+
+capture.log.silent() {
+  clear.resultFiles
+  important.log "capturing logs of:
+   $*
+   
+   use ${WHITE}log inspect${CYAN} in another shell to see whats going on.
+
+   waiting for results...
+   "
+   #### write to console AND result.text AND wite errors to errot.txt AND result.txt
+   "$@" >$CONFIG_PATH/result.txt 2> >(tee -a $CONFIG_PATH/result.txt $CONFIG_PATH/error.txt >&2)
+   important.log "
+   results ready in: $CONFIG_PATH/result.txt"
+}
+
+log.capture.result() {
+  capture.log "$@"
+}
+
+log.capture.result.silent() {
+  capture.log.silent "$@"
+}
+
+
+
+log.inspect() {
+  tail -f $CONFIG_PATH/result.txt
+}
+
+log.inspect.errors() {
+  tail -f $CONFIG_PATH/error.txt
+}
+
+clear.resultFiles() {
+  cd $CONFIG_PATH
+  if [ -f result.txt ]; then
+    rm result.txt
+  else
+    silet.log "result.txt already clean"
+  fi
+
+  if [ -f error.txt ]; then
+    rm error.txt
+  else
+    silet.log "error.txt already clean"
+  fi
+  success.log "result log files cleared"
+  cd -
 }
 
 # log.noop() 
@@ -260,7 +318,7 @@ log.start()
   return $(result)
 }
 
-  log.start "$@"
+log.start "$@"
 
 
 
