check works from cli

diff --git a/check b/check
--- a/check
+++ b/check
@@ -16,88 +16,235 @@ check.usage()
 $0
 
   Usage:
-  $this: command   description and parameter
+  $this: command    <?message <?level> text> object value condition <?fix.message <?level> text> <?fix \"method parameter\"> 
+
+  where \'object\' is one of    
       argument      checks \$1
       function      initializes a new user config
       file          checks if \$FILE   
+      dir           checks if \$FILE   
+    
+  where \'condition\' is one of
+    not
+    exists
+    empty
+    readable
+    writable
+    executable    
   
-      parameter
-        name        name of argument, file or function
-        condition   one of exists, readable, ...
   Examples
-    $this message 
+    $this message \"test the west\" file .oce not exists
+    $this message test     fix.message success \"repair it all\"      fix test.repair      file .once not exists 
+    $this message test     fix.message success \"repair it all\"      fix test.repair      dir  config    exists 
+    
+    $this message test fix.message success repair   file .once not exists fix success.log \"success is cool\"    
+    $this message test file .once not exists fix.message success repair fix success.log \"success is cool\"    
+    
+    $this message test fix.message success repair fix success.log \"success is cool\"   file .once not exists 
+
     $this file ./test.debug exists fix no.test.debug
     $this argument exists
   "
 }
 
 check.condition() {
-  if ($condition); then
-    if [ -z "$CHECK_MESSAGE" ]; then
-      $CHECK_MESSAGE_LEVEL.log "$CHECK_MESSAGE"
+  local condition=$1
+  shift
+
+  local value=$1
+  shift
+
+  if [ -n "$not" ]; then 
+    not="!"
+  fi
+  debug.log "test $not \"$condition\" \"$value\""
+
+  test $not "$condition" "$value"
+  TEST_RESULT=$?
+  if [ "$TEST_RESULT" = 0 ]; then
+    create.result 0 "$condition $value true   :$*"
+    if [ -n "$CHECK_MESSAGE" ]; then 
+      success.log "check    ok: $CHECK_MESSAGE"
     fi
   else
-    if [ -z "$CHECK_FIX_METHOD" ]; then
-      if [ -z "$CHECK_MESSAGE" ]; then
-        $CHECK_MESSAGE_LEVEL.log "$CHECK_MESSAGE"
-      fi
-      $CHECK_FIX_METHOD "$@"
+    create.result 1 "$condition $value false"
+    if [ -n "$CHECK_MESSAGE" ]; then 
+      warn.log "check failed: $CHECK_MESSAGE"
     fi
+    fix.it
   fi
+  return "$(result)"
 }
 
 check.message()
 {
   local level=$1
+  CHECK_MESSAGE_LEVEL="console"
+
   if (this.functionExists $level.log); then
     CHECK_MESSAGE_LEVEL=$1
     CHECK_MESSAGE=$2 
     shift
     shift
   else
-    CHECK_MESSAGE_LEVEL="console"
     CHECK_MESSAGE=$1
     shift
   fi
+  #"$CHECK_MESSAGE_LEVEL".log "$CHECK_MESSAGE"
   RETURN=$1
 }
 
-check.file()
-{
-  FILE=$1
-  if [ -z "$FILE" ]; then
-    error.log "check.file: no file specified"
-  else
-    shift
-  fi
-  RETURN=$1
-}
-
-check.fix()
+check.fix.message()
 {
   local level=$1
+  CHECK_FIX_MESSAGE_LEVEL="console"
+
   if (this.functionExists $level.log); then
     CHECK_FIX_MESSAGE_LEVEL=$1
     CHECK_FIX_MESSAGE=$2 
     shift
     shift
   else
-    CHECK_FIX_MESSAGE_LEVEL="console"
     CHECK_FIX_MESSAGE=$1
     shift
-  fi
-  
-  if (this.functionExists $1); then
-    important.log "fixing with: $@"
   fi
 
   RETURN=$1
 }
 
+check.file.completion() {
+  ls $1*
+}
+
+check.directory() {
+  check.dir "$@"
+}
+
+check.dir()
+{
+  DIR=$1
+  info.log "set DIR: $DIR"
+  
+  if [ -z "$DIR" ]; then
+    create.result 2 "check.dir: no directory specified" "$1"
+    error.log "$RESULT"
+  else
+    shift
+    create.result 0 "check.dir: $DIR"
+  fi
+
+  if [ -f "$DIR" ]; then
+    create.result 1 "check.dir: $DIR is a file" "$1"
+    warn.log "$RESULT"
+    FILE=$DIR
+    unset DIR
+    exit "$(result)"
+  fi
+
+  RETURN=$1
+}
+
+check.file()
+{
+  FILE=$1
+  info.log "set FILE: $FILE"
+  
+  if [ -z "$FILE" ]; then
+    create.result 2 "check.dir: no file specified"
+    error.log "$RESULT"
+  else
+    shift
+  fi
+
+  if [ -d "$FILE" ]; then
+    create.result 1 "check.file: $FILE is a dir"
+    warn.log "$RESULT"
+    DIR=$FILE
+    unset FILE
+    exit "$(result)"
+  fi
+
+  RETURN=$1
+}
+
+check.exists()
+{
+  if [ -n "$DIR" ]; then
+      condition="-d $DIR"
+      info.log "set dir condition: $condition"
+  fi
+  if [ -n "$FILE" ]; then
+      condition="-f $FILE"
+      info.log "set file condition: $condition"
+  fi
+  check.condition $condition
+
+  RETURN=$1
+}
+
+check.not() {
+  not=true
+  RETURN=$1
+}
+
+check.and() {
+  debug.log "and"
+  RETURN=$1
+}
+
+check.fix()
+{
+  FIX_FUNCTION=$1
+  shift
+  FIX_ARGUMENTS="$*"
+  if (this.functionExists $FIX_FUNCTION); then
+    debug.log "fixing with: $FIX_FUNCTION $*"
+  else
+    error.log "fix method: $FIX_FUNCTION does not exist"
+    exit 1
+  fi
+  shift
+
+
+  fix.it
+  return $?
+
+  RETURN=$1
+}
+
+
+fix.it()
+{
+  if [ -n "$TEST_RESULT" ]; then
+      if [ "$TEST_RESULT" = 0 ]; then
+        debug.log "nothing to fix...test was ok"
+        unset RETURN
+        exit "$(result)"
+      else
+        if [ -n "$FIX_FUNCTION" ]; then
+          debug.log "$FIX_FUNCTION $FIX_ARGUMENTS"
+          $FIX_FUNCTION $FIX_ARGUMENTS
+          create.result $? "fixed it with $FIX_FUNCTION $FIX_ARGUMENTS" "$1"
+
+          if [ -n "$CHECK_FIX_MESSAGE" ]; then 
+            "$CHECK_FIX_MESSAGE_LEVEL".log "$CHECK_FIX_MESSAGE"
+          fi
+          unset RETURN
+          exit "$(result)"
+        else
+          debug.log "no fixfunction: $FIX_FUNCTION"
+        fi
+      fi
+  else
+    debug.log "not yet tested"
+  fi
+}
 
 check.start()
 {
   this.start "$@"
+  debug.log "check result $TEST_RESULT"
+  return "$TEST_RESULT"
 }
 
 check.start "$@"
