fixed minor bugs on exit

diff --git a/debug b/debug
--- a/debug
+++ b/debug
@@ -229,8 +229,18 @@ function onError() {
   fi
 
   if [ "$RETURN_VALUE" = "$EXPECTED_RETURN_VALUE" ]; then
+
+    if [ "$RETURN_VALUE" -eq "$ERROR_CODE_RECONFIG" ]; then
+      unset STARTED_OOSH
+      export STARTED_OOSH
+      echo -e "${CYAN}applying new configuration${NORMAL}"
+      $OOSH_DIR/this 
+      #echo -e "${CYAN}exited onError ${ERROR_CODE_RECONFIG}${NORMAL}"
+      exit $ERROR_CODE_RECONFIG
+    fi
+
     if [ ! "$RETURN_VALUE" = "1" ]; then
-      info.log "GOT EXPECTED ERROR in function ${FUNCNAME[1]} in line: ${BASH_LINENO[1]} from ${BASH_SOURCE[2]} returned with ERROR code: $RETURN_VALUE"
+      warn.log "GOT EXPECTED ERROR in function ${FUNCNAME[1]} in line: ${BASH_LINENO[1]} from ${BASH_SOURCE[2]} returned with ERROR code: $RETURN_VALUE"
     fi
     EXPECTED_RETURN_VALUE=1
     return
