test.suite working

diff --git a/debug b/debug
--- a/debug
+++ b/debug
@@ -36,7 +36,7 @@ function step()
 
     echo -e "\033[37m+<----------------------------------------- $STEP_DEBUG"
     echo "> function ${FUNCNAME[1]}(" "${BASH_ARGV[@]}" ")  in file: ${BASH_SOURCE[1]}"
-    echo -e "> line: ${BASH_LINENO[1]} '${BASH_COMMAND}'\033[0m"
+    echo -e "> line: ${BASH_LINENO[0]} '${BASH_COMMAND}'\033[0m"
 
     read -p '' CONT
 
@@ -49,10 +49,11 @@ function step()
             n     next command full with debug
             ENTER next command
 
-            d     toggle debug messages
+            d     eneble debug messages
+            x     TRON: full code trace on
             t     trace the stack
             s     continue silently
-            c     with debug
+            c     continue
             p     print PATH
             ll    list dir
             cd    changing to entered path
@@ -81,7 +82,7 @@ function step()
             check.debug.level 6
             ;;
         c)
-            check.debug.level 5
+            log.level reset
             ;;
         e)
             echo "> expands to: $(eval echo "$BASH_COMMAND")"
@@ -101,7 +102,7 @@ function step()
             step 
             ;;
         d)
-            toggleDebug
+            check.debug.level 5
             step
             ;;
         p)
@@ -164,13 +165,13 @@ function step()
 }
 
 function stackTrace() {
-            i=0;
+
             #for (( i=0; i<=${#BASH_LINENO[@]}; i++)); do
             echo -e "\033[1;37m" 
-            for l in ${BASH_LINENO[@]}; do
+            for i in ${!BASH_LINENO[@]}; do
+                l=${BASH_LINENO[i]}
                 printf "i: %2d  line: %6d  function: %-20s  file: %-30s   args: " "$i" "$l" "${FUNCNAME[$i]}()" "${BASH_SOURCE[$i]}"
-                echo "\"${BASH_ARGV[@]}\" and \"$@\""
-                ((i++))
+                echo "${BASH_ARGV[@]}"
             done
             echo -e "\033[0m"
             step
@@ -216,16 +217,31 @@ function onReturn() {
 function onError() {
   #echo -e "\033[1;31m   line: ${BASH_LINENO[2]} '${BASH_COMMAND[2]}'\033[0m"
 
-  if [ "$1" = "1" ]; then
-    return
+  if [ -n "$1" ]; then
+    RETURN_VALUE=$1
   fi
 
-    error.log         "function ${FUNCNAME[1]} in line: ${BASH_LINENO[2]} from ${BASH_SOURCE[2]} returned with ERROR code: $1"
-    if [ "ON" = "$DEBUG" ]; then
-      export STEP_DEBUG=
+  if [ "$RETURN_VALUE" = "$EXPECTED_RETURN_VALUE" ]; then
+    info.log "GOT EXPECTED ERROR in function ${FUNCNAME[1]} in line: ${BASH_LINENO[2]} from ${BASH_SOURCE[2]} returned with ERROR code: $RETURN_VALUE"
+    EXPECTED_RETURN_VALUE=1
+    return
+  fi
+    debug.log "source stack: ${BASH_SOURCE[@]##*/}"
+    error.log         "line ${BASH_LINENO[0]}: \"$2\" from ${BASH_SOURCE[1]} returned with ERROR code: $RETURN_VALUE"
+    if [ "$LOG_LEVEL" -gt 3 ]; then
+      check.debug.level 3
       stackTrace
-      export STEP_DEBUG=ON
-    fi
+      check.debug.level reset
+    fi   
+}
+
+expect.error()
+{
+  if (this.isNumber "$1"); then
+    export EXPECTED_RETURN_VALUE=$1
+  else
+    warn.log "ignoring expect error, because \"$1\" is not a number."
+  fi
 }
 
 function onExit() {
@@ -240,7 +256,7 @@ function setTrap() {
 
 
   #set -e
-  trap 'onError ${?}' ERR
+  trap 'onError ${?} ${BASH_COMMAND}' ERR
   trap 'onReturn ${?}' RETURN
   trap 'onExit  ${?}' EXIT 
   
