test.call good but nod debug ERRORS as planed

diff --git a/init b/init
--- a/init
+++ b/init
@@ -27,10 +27,17 @@ this.load()
   local aShellScript=$1
   shift
 
-  if (this.functionExists $aFunction) ; then
+  if [ -z "$aShellScript" ]; then
+    error.log "No script name provided!"
+    return 1
+  fi
+
+  if (this.functionExists $aShellScript.$aFunction) ; then
     debug.log "$aShellScript was already sourced"
   else
-    source $aShellScript $aFunction
+    #important.log "sourcing $aShellScript $aShellScript.$aFunction $@"
+    source $aShellScript
+    $aShellScript.$aFunction "$@"
   fi
   RETURN=$1
 }
@@ -50,7 +57,7 @@ this.init()
   export PATH=$initStartPath:$PATH
   #loop list PATH
 }
-this.load step debug
+this.load v debug
 
 this.absolutePath()
 {
@@ -72,7 +79,7 @@ this()
 this.caller()
 {
   local len=${#BASH_LINENO[@]}
-  local caller=${BASH_SOURCE[$len-2]##*/}
+  local caller=${BASH_SOURCE[3]##*/}
   info.log "script: $0"
   info.log "caller: $caller"
   result "$caller" "$1" >/dev/null
@@ -95,30 +102,56 @@ this.call()
   info.log "script: $0"
   info.log "caller: $caller"
 
+  if (this.functionExists $aFunction) ; then
+    debug.log "this.call: $aFunction $@"
+    $aFunction "$@"
+    return "$?"
+  else
+    info.log "$aFunction does not exist!"
+  fi
+
+
   if (this.functionExists $caller.$aFunction) ; then
     debug.log "this.call: $caller.$aFunction $@"
     $caller.$aFunction "$@"
   else
+    info.log "$caller.$aFunction does not exist!"
     local aShellScript=$aFunction
     aFunction=$1
     shift
 
+    info.log "aShellScript: $aShellScript"
+    info.log "aFunction: $aFunction"
+    info.log "next parameter \$1: $1"
+
     if (this.functionExists $aFunction) ; then
-      debug.log "this.call: $aFunction $@"
+      debug.log "this.call: $aFunction $@ "
       $aFunction "$@"
     else
-      this.load $aFunction $aShellScript "$@"
-      debug.log "this.call: $aFunction $@"
-      $aFunction "$@"
+      debug.log "this.load: $aFunction $aShellScript"
+      if (this.load $aFunction $aShellScript "$@"); then
+        debug.log "done this.call: $aShellScript.$aFunction $@"
+        #$aShellScript.$aFunction "$@"
+      else
+        error.log "this.load faild to load $aShellScript from \"$aFunction\""
+        return 127
+      fi
     fi
   fi
 } #2>/dev/null
 
 this.start() 
 {
+  if (this.isSourced); then
+    debug.log "is sourced"
+    return 0
+  fi
+
   if [ -z "$1" ]; then
     local len=${#BASH_LINENO[@]}
     local caller=${BASH_SOURCE[$len-2]##*/}
+
+
     if (this.functionExists $caller.usage) then
       $caller.usage
     else
@@ -184,11 +217,20 @@ this.isSourced()
   info.log len=$len, depth=$depth
   info.log "check: ${FUNCNAME[1]}"
 
-  if [ "${FUNCNAME[1]}" = "main" ]; then
-    info.log "mode starting ${FUNCNAME[@]} in ${BASH_SOURCE[0]##*/} from ${BASH_SOURCE[$len-1]##*/}"
+
+    caller=${BASH_SOURCE[$len-2]##*/}
+    check=${FUNCNAME[$len-2]}
+  if [ $len -gt 3 ]; then
+    local caller=${BASH_SOURCE[3]##*/}
+    local check=${FUNCNAME[3]}
+  fi
+  debug.log "caller $caller and mode: $check"
+
+  if [ "$check" = "main" ]; then
+    debug.log "mode starting ${FUNCNAME[@]} in ${BASH_SOURCE[0]##*/} from ${BASH_SOURCE[$len-1]##*/}"
     return 1
   else
-    info.log "mode sourcing ${BASH_SOURCE[0]##*/} from ${BASH_SOURCE[$len-1]##*/}" 
+    debug.log "mode sourcing $caller from ${BASH_SOURCE[$len-1]##*/}" 
     return 0
   fi
 }
@@ -197,7 +239,7 @@ this.isSourced()
 info.log "
 still in ${BASH_SOURCE[0]##*/}
 "
-
+#set -x
 if (this.isSourced); then
  info.log "init was sourced"
  this.init
