added LOG_DEVICE

diff --git a/log b/log
--- a/log
+++ b/log
@@ -13,6 +13,17 @@ log.init()
     CONFIG=~/config/user.env
     source $CONFIG
     log.init.colors
+  else
+    export LOG_DEVICE=/dev/tty
+    
+    echo "initializing logging" >$LOG_DEVICE
+    RETURN_VALUE="$?"
+    if [ $RETURN_VALUE -eq 1 ]; then
+      export LOG_DEVICE=/dev/stderr
+      echo "  logging over ssh ... using $LOG_DEVICE"
+      config save log LOG
+
+    fi
   fi
 
   if [ -n "$1" ]; then
@@ -35,19 +46,19 @@ fi
 console.log()
 {
   if [ "$LOG_LEVEL" -gt "2" ]; then
-    echo -e "${NO_COLOR}$*" >/dev/tty
+    echo -e "${NO_COLOR}$*" >$LOG_DEVICE
   fi
 }
 
 silent.log() {
     if [ "$LOG_LEVEL" -gt "2" ]; then
-        echo -e "${GRAY}  $*${NORMAL}" >/dev/tty
+        echo -e "${GRAY}  $*${NORMAL}" >$LOG_DEVICE
     fi
 }
 
 success.log() {
     if [ "$LOG_LEVEL" -gt "2" ]; then
-        echo -e "${BOLD_GREEN}SUCCESS> $*${NORMAL}" >/dev/tty
+        echo -e "${BOLD_GREEN}SUCCESS> $*${NORMAL}" >$LOG_DEVICE
     fi
 }
 
@@ -77,7 +88,7 @@ warn.log()
 important.log()
 {
     if [ "$LOG_LEVEL" -gt "1" ]; then
-        echo -e "${BOLD_CYAN}IMPORTANT> $*${NORMAL}"   >/dev/tty                                 ## cyan
+        echo -e "${BOLD_CYAN}IMPORTANT> $*${NORMAL}"   >$LOG_DEVICE                                 ## cyan
     fi
     {
       shift
@@ -87,7 +98,7 @@ important.log()
 
 problem.log() {
     if [ "$LOG_LEVEL" -gt "1" ]; then
-        echo -e "${BOLD_RED}PROBLEM BREAKPOINT> $*${NORMAL}" #>/dev/tty
+        echo -e "${BOLD_RED}PROBLEM BREAKPOINT> $*${NORMAL}" #>$LOG_DEVICE
         export STEP_DEBUG=ON
     fi  
 }
@@ -96,13 +107,13 @@ problem.log() {
 
 debug.log() {
     if [ "$LOG_LEVEL" -gt "4" ]; then  
-        echo -e "${BOLD_CYAN}- $*${NORMAL}" >/dev/tty
+        echo -e "${BOLD_CYAN}- $*${NORMAL}" >$LOG_DEVICE
     fi
 }
 
 stop.log() {
     if [ "$LOG_LEVEL" -gt "3" ]; then
-        echo -e "${BOLD_GREEN}BREAKPOINT> $*${NORMAL}" >/dev/tty
+        echo -e "${BOLD_GREEN}BREAKPOINT> $*${NORMAL}" >$LOG_DEVICE
         export STEP_DEBUG=ON
     fi  
 }
@@ -117,7 +128,7 @@ err.log() {
     fi
 
     if [ "$LOG_LEVEL" -gt 0 ]; then
-       echo -e "${BOLD_RED}ERROR> $*${NORMAL}" | tee -a ~/config/error.txt ~/config/result.txt  >/dev/tty     
+       echo -e "${BOLD_RED}ERROR> $*${NORMAL}" | tee -a ~/config/error.txt ~/config/result.txt  >$LOG_DEVICE     
     fi
 
     if [ "$LOG_LEVEL" -gt "4" ]; then   
