fixed colors

diff --git a/log b/log
--- a/log
+++ b/log
@@ -28,38 +28,38 @@ fi
 console.log()
 {
   if [ "$LOG_LEVEL" -gt "2" ]; then
-    echo -e "${ESC}0m$*" 
+    echo -e "${NO_COLOR}$*" 
   fi
 }
 
 silent.log() {
     if [ "$LOG_LEVEL" -gt "2" ]; then
-        echo -e "${ESC}90m  $*\033[0m" 
+        echo -e "${GRAY}  $*${NORMAL}" 
     fi
 }
 
 success.log() {
     if [ "$LOG_LEVEL" -gt "2" ]; then
-        echo -e "${BOLD};32mSUCCESS> $*\033[0m" 
+        echo -e "${BOLD_GREEN}SUCCESS> $*${NORMAL}" 
     fi
 }
 
 test.success.log() {
     if [ "$LOG_LEVEL" -gt "0" ]; then
-        echo -e "${BOLD};32mSUCCESS> $*\033[0m" 
+        echo -e "${BOLD_GREEN}SUCCESS> $*${NORMAL}" 
     fi
 }
 
 error.details.log() {
     if [ "$LOG_LEVEL" -gt "0" ]; then
-      echo -e "${ESC}0m$*"
+      echo -e "${NORMAL}$*"
     fi
 }
 
 warn.log()
 {
     if [ "$LOG_LEVEL" -gt "1" ]; then
-        echo -e "${BOLD};33m> WARNING $*\033[0m" | tee -a $CONFIG_PATH/error.txt #>>$CONFIG_PATH/result.txt                               ## yellow
+        echo -e "${BOLD_YELLOW}> WARNING $*${NORMAL}" | tee -a $CONFIG_PATH/error.txt #>>$CONFIG_PATH/result.txt                               ## yellow
     fi
     {
       shift
@@ -70,7 +70,7 @@ warn.log()
 important.log()
 {
     if [ "$LOG_LEVEL" -gt "1" ]; then
-        echo -e "${BOLD};96mIMPORTANT> $*\033[0m"                                    ## cyan
+        echo -e "${BOLD_CYAN}IMPORTANT> $*${NORMAL}"                                    ## cyan
     fi
     {
       shift
@@ -80,7 +80,7 @@ important.log()
 
 problem.log() {
     if [ "$LOG_LEVEL" -gt "1" ]; then
-        echo -e "${BOLD};31mPROBLEM BREAKPOINT> $*\033[0m" 
+        echo -e "${BOLD_RED}PROBLEM BREAKPOINT> $*${NORMAL}" 
         export STEP_DEBUG=ON
     fi  
 }
@@ -89,13 +89,13 @@ problem.log() {
 
 debug.log() {
     if [ "$LOG_LEVEL" -gt "4" ]; then  
-        echo -e "${BOLD};36m- $*\033[0m"
+        echo -e "${BOLD_CYAN}- $*${NORMAL}"
     fi
 }
 
 stop.log() {
     if [ "$LOG_LEVEL" -gt "3" ]; then
-        echo -e "${BOLD};32mBREAKPOINT> $*\033[0m" 
+        echo -e "${BOLD_GREEN}BREAKPOINT> $*${NORMAL}" 
         export STEP_DEBUG=ON
     fi  
 }
@@ -106,7 +106,7 @@ error.log() {
 err.log() {
 
     if [ "$LOG_LEVEL" -gt 0 ]; then
-       echo -e "${BOLD};31mERROR> $*\033[0m" | tee -a $CONFIG_PATH/error.txt $CONFIG_PATH/result.txt     
+       echo -e "${BOLD_RED}ERROR> $*${NORMAL}" | tee -a $CONFIG_PATH/error.txt $CONFIG_PATH/result.txt     
     fi
 
     if [ "$LOG_LEVEL" -gt "4" ]; then   
@@ -224,27 +224,37 @@ log.level()
 
 log.init.colors() 
 {
-  ESC="\033["
-  BOLD="${ESC}1"
-  RED="${BOLD};31m"
-  GREEN="${BOLD};32m"
-  BLUE="${ESC}0m"
-  CYAN="${BOLD};96m"
-  GRAY="${ESC}90m"
-  YELLOW="${BOLD};33m"
-  WHITE="${BOLD};37m"
 
-  NORMAL="${ESC}0m"
-  COLOR_NONE="${ESC}0m"
+           ESC=$'\033['
+          BOLD="${ESC}0;1m"
+        NORMAL=${ESC}"0m"
+      NO_COLOR=${ESC}"0m"
 
-  COLOR_RED=${RED}
-  COLOR_GREEN=${GREEN}
-  COLOR_BLUE=${BLUE}
-  COLOR_CYAN=${CYAN}
-  COLOR_GRAY=${GRAY}
-  COLOR_YELLOW=${YELLOW}
-  COLOR_WHITE=${WHITE}
+  
+  if ! [ -f $CONFIG_PATH/color.env ];then
+    {  
+      echo     COLOR_RED="${ESC}31m"
+      echo   COLOR_GREEN="${ESC}32m"
+      echo    COLOR_BLUE="${ESC}0m"
+      echo    COLOR_CYAN="${ESC}96m"
+      echo    COLOR_GRAY="${ESC}90m"
+      echo  COLOR_YELLOW="${ESC}33m"
+      echo   COLOR_WHITE="${ESC}37m"
+    } >$CONFIG_PATH/color.env
+    # cat $CONFIG_PATH/color.env | line find "COLOR_" | line replace COLOR_ >$CONFIG_PATH/color.names.env
+    # cat $CONFIG_PATH/color.env | line find COLOR_ | line replace COLOR_ BOLD_ | line replace "{ESC}" "{ESC}1;" >bold.color.names.env
+  else 
+    source $CONFIG_PATH/color.env
+    source $CONFIG_PATH/color.names.env
+    source bold.color.names.env
+  fi
+
+
+
+
+
 }
+
 
 log.usage()
 {
