improoving log init

diff --git a/log b/log
--- a/log
+++ b/log
@@ -9,12 +9,19 @@
 
 log.init()
 {
+  if [ -z "$CONFIG" ]; then
+    CONFIG=~/config/user.env
+    source $CONFIG
+    log.init.colors
+  fi
+
   if [ -n "$1" ]; then
     export LOG_LEVEL="$1"
     important.log "log level changed to $LOG_LEVEL"
   else
     export LOG_LEVEL=3
   fi
+
 
   important.log "log initialized on level $LOG_LEVEL"
 }
@@ -58,13 +65,8 @@ error.details.log() {
 
 warn.log()
 {
-    if [ -z "$CONFIG" ]; then
-      CONFIG=~/config/user.env
-      source $CONFIG
-    fi
-
     if [ "$LOG_LEVEL" -gt "1" ]; then
-        echo -e "${BOLD_YELLOW}> WARNING $*${NORMAL}" | tee -a $CONFIG_PATH/error.txt #>>$CONFIG_PATH/result.txt ## yellow
+        echo -e "${BOLD_YELLOW}> WARNING $*${NORMAL}" | tee -a ~/config/error.txt #>>$CONFIG_PATH/result.txt ## yellow
     fi
     {
       shift
@@ -115,7 +117,7 @@ err.log() {
     fi
 
     if [ "$LOG_LEVEL" -gt 0 ]; then
-       echo -e "${BOLD_RED}ERROR> $*${NORMAL}" | tee -a $CONFIG_PATH/error.txt $CONFIG_PATH/result.txt     
+       echo -e "${BOLD_RED}ERROR> $*${NORMAL}" | tee -a $~/config/error.txt ~/config/result.txt     
     fi
 
     if [ "$LOG_LEVEL" -gt "4" ]; then   
@@ -128,7 +130,7 @@ capture.log() {
   important.log "capturing logs of:
    $*"
    #### write to console AND result.text AND wite errors to errot.txt AND result.txt
-   "$@" > >(tee -a $CONFIG_PATH/result.txt) 2> >(tee -a $CONFIG_PATH/result.txt $CONFIG_PATH/error.txt >&2)
+   "$@" > >(tee -a $CONFIG_PATH/result.txt) 2> >(tee -a ~/config/result.txt ~/config/error.txt >&2)
 }
 
 capture.log.silent() {
@@ -273,7 +275,7 @@ log.usage()
 log.start()
 {
   #echo "log startet"
-  log.init.colors
+
   if [ -z "$LOG_LEVEL" ]; then
     log.init $1
   else
