changed log order

diff --git a/log b/log
--- a/log
+++ b/log
@@ -16,6 +16,16 @@ log.init()
   fi
 
   export LOG_DEVICE=/dev/tty
+
+  echo "initializing logging" >$LOG_DEVICE
+  RETURN_VALUE="$?"
+  if [ $RETURN_VALUE -eq 1 ]; then
+    export LOG_DEVICE=/dev/stderr
+    echo "  logging over ssh ... using $LOG_DEVICE"
+    config save log LOG
+
+  fi
+
   if [ -n "$level" ]; then
     export LOG_LEVEL="$level"
     important.log "log level changed to $LOG_LEVEL"
@@ -31,14 +41,7 @@ log.init()
     log.init.colors
   fi
     
-  echo "initializing logging" >$LOG_DEVICE
-  RETURN_VALUE="$?"
-  if [ $RETURN_VALUE -eq 1 ]; then
-    export LOG_DEVICE=/dev/stderr
-    echo "  logging over ssh ... using $LOG_DEVICE"
-    config save log LOG
 
-  fi
 
 
 
@@ -66,8 +69,11 @@ seq.puml.log()
       pumlPrefix='echo ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - '
       export STEP_DEBUG=OFF
     else
-      pumlPrefix=""
-      export PS4='\e[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \e[0m'
+      # TODO cleanup PS4
+      # pumlPrefix=""
+      # export PS4='\e[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \e[0m'
+      pumlPrefix='echo ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - '
+      export PS4='\e[90m  ${BASH_SOURCE[0]##*/} -> ${BASH_SOURCE[1]##*/}: ${FUNCNAME[0]}:${LINENO}   - ${BASH_SOURCE[@]##*/} \e[0m'
     fi
 }
 
