Consolidate log.setdevice

diff --git a/log b/log
--- a/log
+++ b/log
@@ -8,6 +8,24 @@
 
 # set -x
 
+log.device()
+{
+  local device=$1
+  if [ -z "$device" ]; then
+    device=/dev/tty
+  fi
+
+  export LOG_DEVICE=$device
+  echo "initializing logging to $LOG_DEVICE" >>$LOG_DEVICE
+  RETURN_VALUE="$?"
+  if [ $RETURN_VALUE -eq 1 ]; then
+    old_log_device=$LOG_DEVICE
+    export LOG_DEVICE=/dev/stderr
+    echo "  Tried to initialize logging to $old_log_device and failed" >>$LOG_DEVICE
+    echo "  logging over ssh (or other non-tty) ... using $LOG_DEVICE" >>$LOG_DEVICE
+  fi
+}
+
 log.init()
 {
   local level=$1
@@ -15,16 +33,7 @@ log.init()
     level=3
   fi
 
-  export LOG_DEVICE=/dev/tty
-
-  echo "initializing logging to $LOG_DEVICE" >>$LOG_DEVICE
-  RETURN_VALUE="$?"
-  if [ $RETURN_VALUE -eq 1 ]; then
-    export LOG_DEVICE=/dev/stderr
-    echo "  logging over ssh ... using $LOG_DEVICE"
-    #config save log LOG
-
-  fi
+  log.device /dev/tty
 
   if [ -n "$level" ]; then
     export LOG_LEVEL="$level"
@@ -263,7 +272,7 @@ log.level() # <levelno> # switch to a specific log level
         info.log "log level sourced"
       else
           info.log "log level started"
-          export LOG_DEVICE=/dev/tty
+          log.device /dev/tty
           config save log LOG
           exit 0
           #config add log
