fixed sourcing hell

diff --git a/log b/log
--- a/log
+++ b/log
@@ -1,11 +1,11 @@
 #!/bin/bash
 
-#echo "entering: ${BASH_SOURCE[0]}"
-#echo "remove all echos to preseve output"
-#echo ""
-#export PS4='\033[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \033[0m'
+# echo "entering: ${BASH_SOURCE[0]}"
+# echo "remove all echos to preseve output"
+# echo ""
 
-
+# export PS4='\033[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \033[0m'
+# set -x
 
 log.init()
 {
@@ -18,6 +18,10 @@ log.init()
   important.log "log initialized on level $LOG_LEVEL"
 }
 
+if ! [ "$(type -t info.log)" = "function" ]; then
+  source init; 
+fi  
+
 this.isNumber() 
 {
   case $1 in
@@ -29,20 +33,20 @@ this.isNumber()
 console.log()
 {
   if [ "$LOG_LEVEL" -gt "2" ]; then
-    echo -e "\033[0m$@"
+    echo -e "\033[0m$*"
   fi
 }
 
 success.log() {
     if [ "$LOG_LEVEL" -gt "2" ]; then
-        echo -e "\033[1;32mSUCCESS> $@\033[0m" 
+        echo -e "\033[1;32mSUCCESS> $*\033[0m" 
     fi
 }
 
 warn.log()
 {
     if [ "$LOG_LEVEL" -gt "1" ]; then
-        echo -e "\033[1;33m> WARNING $@\033[0m"                                    ## yellow
+        echo -e "\033[1;33m> WARNING $*\033[0m"                                    ## yellow
     fi
     {
       shift
@@ -53,7 +57,7 @@ warn.log()
 important.log()
 {
     if [ "$LOG_LEVEL" -gt "1" ]; then
-        echo -e "\033[1;96mIMPORTANT> $@\033[0m"                                    ## cyan
+        echo -e "\033[1;96mIMPORTANT> $*\033[0m"                                    ## cyan
     fi
     {
       shift
@@ -63,27 +67,22 @@ important.log()
 
 problem.log() {
     if [ "$LOG_LEVEL" -gt "1" ]; then
-        echo -e "\033[1;31mPROBLEM BREAKPOINT> $@\033[0m" 
+        echo -e "\033[1;31mPROBLEM BREAKPOINT> $*\033[0m" 
         export STEP_DEBUG=ON
     fi  
 }
 
-info.log()
-{
-    if [ "$LOG_LEVEL" -gt "3" ]; then
-        echo -e "\033[0mINFO> $@"                                             ## normal
-    fi
-}
+
 
 debug.log() {
     if [ "$LOG_LEVEL" -gt "4" ]; then  
-        echo -e "\033[1;36m- $@\033[0m"
+        echo -e "\033[1;36m- $*\033[0m"
     fi
 }
 
 stop.log() {
     if [ "$LOG_LEVEL" -gt "3" ]; then
-        echo -e "\033[1;32mBREAKPOINT> $@\033[0m" 
+        echo -e "\033[1;32mBREAKPOINT> $*\033[0m" 
         export STEP_DEBUG=ON
     fi  
 }
@@ -94,7 +93,7 @@ error.log() {
 err.log() {
 
     if [ "$LOG_LEVEL" -gt "0" ]; then   
-      echo -e "\033[1;31mERROR> $@\033[0m"    
+      echo -e "\033[1;31mERROR> $*\033[0m"    
     fi
 
     if [ "$LOG_LEVEL" -gt "4" ]; then   
@@ -114,39 +113,18 @@ log.level()
       LOG_LEVEL_RESET=$LOG_LEVEL
       LOG_LEVEL="$1"
       important.log "log level changed to $LOG_LEVEL"
-      log.checkDebug
+      check.debug.level
     fi
 
     shift  
-    RETURN=$1
+    export RETURN=$1
   else
     result "export LOG_LEVEL=$LOG_LEVEL" "$1" >/dev/null
     echo "$RESULT"
   fi
 }
 
-log.checkDebug()
-{
-  if [ -n "$1" ]; then
-    log.level $1
-  fi
 
-  if [ "$LOG_LEVEL" -gt "6" ]; then
-    export STEP_DEBUG=ON 
-  else
-    export STEP_DEBUG=OFF
-  fi
-
-  if [ "$LOG_LEVEL" -gt "5" ]; then
-    export PS4='\033[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \033[0m'
-    set -x
-  else
-    { 
-        set +x
-    } 2>/dev/null
-  fi
-
-} #2>/dev/null
 
 log.start()
 {
@@ -162,11 +140,17 @@ log.start()
       shift
       log.$command "$@"
     fi
-    result 0 "export LOG_LEVEL=$LOG_LEVEL" "$1" >/dev/null
+    if [ "$(type -t this.init)" = "function" ]; then
+      result 0 "export LOG_LEVEL=$LOG_LEVEL" "$1" >/dev/null
+    else
+      RETURN_VALUE=0
+      RESULT="export LOG_LEVEL=$LOG_LEVEL"
+      RETURN="$1"
+    fi
     return $RETURN_VALUE
   fi
 
-  log.checkDebug
+  check.debug.level
   result 0 "export LOG_LEVEL=$LOG_LEVEL" "$1" >/dev/null
   return $RETURN_VALUE
 }
