migrate once cmd to oo cmd

diff --git a/oo b/oo
--- a/oo
+++ b/oo
@@ -196,7 +196,7 @@ oo.install.dev() # # install the official dev oosh. GitHub keys required
   cd ..
 
   check dir /var/dev not exists \
-    call mkdir -p /var/dev/Workspaces/2cuGitHub
+    call $SUDO mkdir -p /var/dev/Workspaces/2cuGitHub
   
   ossh config.create 2cuGitHub git@github.com:Cerulean-Circle-GmbH/once.sh.git '~/.ssh/ids/ssh.marcel.iMac/private_key/donges.mcdonges.fritz.box.private_key'
   ossh config.last.save
@@ -226,12 +226,155 @@ oo.mode.fullDebug() # # switches to fullDebug branch
 
 oo.cmd() # <cmd> <?packageName> # checks if <cmd> is installed and installes it with: $SUDO $PM <?packageName>
 {
-  once cmd "$@"
+    current=$1
+    shift
+    package=$1
+
+    if [ -z "$1" ]; then
+        package=$current
+    else
+      shift
+      package=$1
+    fi   
+    
+    if [ -z "$OOSH_PM" ]; then
+      console.log "no PM found...checking" 
+      once.su.check.all.pm
+    fi
+    if ! [ -x "$(command -v $current)" ]; then
+        console.log "no $current"
+        if [ -n "$OOSH_PM" ]; then
+          case $current in
+            eamd)
+              once.load $current tla/EAMD/UcpComponentSupport/1.0.0/src/sh/eamd
+              export PATH="$PATH:$ONCE_LOAD_DIR"
+              hash -d eamd    #clears the command cache for eamd
+              #hash -r   #clears the command cache completley
+              ;;
+            oosh)
+              once.load $current com/ceruleanCircle/EAM/1_infrastructure/OOSH/1.0.0/src/sh/oosh
+              ;;
+            once)
+              once.load once.sh tla/EAM/layer1/Thinglish/Once/latestServer/src/sh/once.sh
+              cd $ONCE_LOAD_DIR
+              mv once.sh once
+              private.stage status
+              ;;
+            npm)
+              # if ! which $current > /dev/null; then
+                once.su.npm.install
+              # else
+              #   console.log "$current allready installed!";
+              # fi
+              # exit;
+              ;;
+            mkcert)
+              once.su.mkcert.install
+              ;;
+            update)
+              if [ -z "$OOSH_PM_UPDATED" ]; then
+                apt-get update
+              else
+                warn.log "Package manager already updated with: $OOSH_PM_UPDATED"
+              fi
+              ;;
+            *)
+              $OOSH_PM $package
+            esac
+        else
+            console.log "no package manger"
+        fi
+        if [ -n "$1" ]; then
+          shift
+        fi
+    fi
+    RETURN=$1
+
 }
 
 oo.pm() # # finds out OS and corresponding package manager (pm)
 {
-  oo.cmd "$@"
+  if [ -n "$OOSH_PM" ]; then
+    important.log "package manager is set:"
+    console.log "for OOSH: $OOSH_PM"
+    console.log "for ONCE: $ONCE_PM"
+    if [ "$OOSH_PM" = "$ONCE_PM" ]; then
+      success.log "package manager well configured"
+      return 0
+    else
+      warn.log "package manager differ!
+      use
+      
+        oo pm.discover
+      
+      to fix that
+      "
+      return 1
+    fi
+  fi
+  OOSH_PM=
+  private.check.all.pm
+  console.log "PM: $OOSH_PM"
+
+  RETURN=$1
+}
+
+oo.pm.discover() # # finds out OS and corresponding package manager (pm)
+{
+  OOSH_PM=
+  private.check.all.pm
+  console.log "OOSH_PM: $OOSH_PM"
+  config save
+
+  RETURN=$1
+}
+
+private.check.pm()             # checks for a package manager
+{
+
+    local packageManager=$1
+    local packageManagerCommand=$2
+
+
+    if [ -z "$packageManagerCommand" ]; then
+        package=$packageManager
+    fi   
+    if ! [ -x "$(command -v $packageManager)" ]; then
+        debug.log "no $packageManager"
+    else
+        if [ -z "$OOSH_PM" ]; then
+            export OOSH_PM=$packageManagerCommand
+            export groupAddCommand=$3
+            export userAddCommand=$4
+            echo "Package Manager found: using $OOSH_PM somePackage"
+            if [ "$packageManager" = "apt-get" ]; then
+                if [ -z "$OOSH_PM_UPDATED" ]; then
+                  OOSH_PM_UPDATED="apt-get update"
+                  #if [ "$ONCE_PRIVILEGE" = root ]; then
+                    $OOSH_PM_UPDATED
+                  # else 
+                  #   PM="sudo $PM"
+                  # fi
+                else
+                  echo "in case of installation errors try to call: apt-get update"
+                fi
+            fi
+        fi
+    fi
+}
+
+private.check.all.pm()         # adds tools and configurations to package manager (brew, apt-get, addgroup, adduser, dpkg, pkg)
+{
+
+    private.check.pm brew "brew install"    
+    #once.check.pm apt "apt add"
+    private.check.pm apt-get "apt-get -y install" "groupadd -f" "useradd -g dev"
+    private.check.pm apk "apk add" "addgroup" "adduser -g dev"
+    private.check.pm dpkg "dpkg install"
+    private.check.pm pkg "pkg install"
+    private.check.pm pacman "pacman -S"
+
+ 
 }
 
 oo.install() { # <scriptClass> <path> # installs an external oo script from <path> into oosh/external as a link
