made completion parameter aware

diff --git a/state b/state
--- a/state
+++ b/state
@@ -551,13 +551,13 @@ private.itterator.find() {  # <currentName> <currentValue> <currentID> <rest> #
   return 0
 }
 
-state.rename() # <?machine> <state> <newStateName> <print> #
+state.rename() # <?machine> <state> <newStateName:> <print:> #
 {
   local aMachine=$1
   if state.machine.exists "$aMachine"; then shift; fi 
   source $CONFIG_PATH/current.state.machine.env
 
-  if ! private.check.setup; then return 1; fi
+  if ! private.check.setup rename; then return 1; fi
 
   local stateToRename=$1
   if [ -n "$1" ]; then 
@@ -604,7 +604,7 @@ state.rename() # <?machine> <state> <newStateName> <print> #
   RETURN=$1
 }
 
-private.check.setup() {
+private.check.setup() { # <?action:add> # returns error 1 if state is not equal to setup 
   if [ -z "$state" ]; then
       source $CONFIG_PATH/current.state.machine.env
   fi
@@ -613,15 +613,18 @@ private.check.setup() {
     state.stage $machine; 
     source $CONFIG_PATH/current.state.machine.env
   fi
-  if [ $state -gt 2 ]; then 
-    error.log "cannot add state!"
-    error.log "state machine not in state: [2] = setup  
-    but is in state: $state
+  if [ $state -gt 2 ]; then
+    local action=$1
+    if [ -n "$action" ]; then shift; else action="add"; fi
+
+    error.log "cannot $action state!"
+    error.log "state machine ${CYAN}$machine${RED} is not in state: ${CYAN}[2] = setup${RED}  
+    but is in state: ${CYAN}$state
     "
     important.log "
     you could hard reset the machine $machine to state 2 with
 
-    state set $machine 2
+    state of $machine set 2
     "
     return 1
   fi
