added state set and find

diff --git a/state b/state
--- a/state
+++ b/state
@@ -22,18 +22,12 @@ state.of() # <machine> <?method> # returns the state of the <machine>
   source $CONFIG_PATH/stateMachines/${machine}.states.env
   local state=${!stateID}
   local stateName="${machine}_STATES[${state}]"
+  local stateList="${machine}_STATES[@]"
+  local stateFile="$CONFIG_PATH/stateMachines/${machine}.states.env"
 
   debug.log "machine ${YELLOW}$machine ${CYAN}state is: ${WHITE}${!stateName}"
   export STATE_MACHINE_CURRENT=$machine
-  {
-    echo machine=$machine
-    echo stateID=$stateID
-    echo state=$state
-    echo stateName=$stateName
-    echo stateValue=${!stateName}
-    echo stateList=${machine}_STATES[@]
-    echo stateFile=$CONFIG_PATH/stateMachines/${machine}.states.env
-  } >$CONFIG_PATH/current.state.machine.env
+  private.state.update.current.machine
 
   if [ -n "$1" ]; then 
     local call=$1
@@ -46,6 +40,22 @@ state.of() # <machine> <?method> # returns the state of the <machine>
   RETURN=$1
 }
 
+
+private.state.update.current.machine() {
+  local stateName="${machine}_STATES[${!stateID}]"
+  export STATE_MACHINE_CURRENT=$machine
+  {
+    echo machine=$machine
+    echo stateID=$stateID
+    echo state=${!stateID}
+    echo stateFound=$stateFound
+    echo stateName="${machine}_STATES[${state}]"
+    echo stateValue=${!stateName}
+    echo stateList=$stateList
+    echo stateFile=$stateFile
+    echo source $stateFile
+  } >$CONFIG_PATH/current.state.machine.env  
+}
 
 state.current() # <print> # load current state
 {
@@ -61,7 +71,7 @@ state.name() # <machine> #
   local aMachine=$1
   if [ -n "$1" ]; then shift; fi
   if ! [ "$aMachine" = "-" ]; then 
-    state.of $machine name
+    state.of $aMachine name
     return 0
   fi
   echo ${!stateName}
@@ -72,7 +82,7 @@ state.id() # <machine> #
   local aMachine=$1
   if [ -n "$1" ]; then shift; fi
   if ! [ "$aMachine" = "-" ]; then 
-    state.of $machine id
+    state.of $aMachine id
     return 0
   fi
   echo ${state}
@@ -113,7 +123,7 @@ state.find() # <machine> <state> #
   local aMachine=$1
   if [ -n "$1" ]; then shift; fi
   if ! [ "$aMachine" = "-" ]; then 
-    state.of $machine find "$@"
+    state.of $aMachine find "$@"
     shift
     RETURN=$1
     return 0
@@ -124,16 +134,53 @@ state.find() # <machine> <state> #
   if [ -n "$1" ]; then shift; fi  
 
   if this.isNumber $stateName;then
-    local stateName="${machine}_STATES[${state}]"
-    important
-    echo ${!stateName}
+    local stateFound=${stateName}
+    local stateName="${machine}_STATES[${stateName}]"
+    stateValue=${!stateName}
+    if [ -z "$stateValue" ]; then 
+      stateFound=0; 
+    else 
+      echo ${!stateName}: ${stateFound}
+    fi
   else
-    echo "$stateName"
+    let i=0
+    let count=0
+    let countInternal=0
+    for index in "${!stateList}"; do
+      local currentName="${machine}_STATES[$i]"
+      debug.log looping ${currentName}  at $index loop $i
+
+        if this.isNumber ${!currentName}; then
+          debug.log "skipping ${!currentName}"
+          local next=${!currentName}
+          i=$next-1
+        else 
+          let count++
+          if [ "${!currentName}" = "$stateName" ]; then
+            echo "$i"
+            stateFound=$i
+            break
+          else
+            stateFound=0
+          fi
+        fi
+      let i++
+      let countInternal++
+    done
+
   fi
 
-  echo find to ${stateName}
   shift
   RETURN=$1
+
+
+  if [ $stateFound -eq 0 ]; then
+    error.log "State '$stateName' not found!"
+    return 1
+  fi
+  private.state.update.current.machine
+  debug.log found ${stateName} = $stateFound $stateValue
+  return 0
 }
 
 state.stage() # <machine> <stateName> #
@@ -141,7 +188,7 @@ state.stage() # <machine> <stateName> #
   local aMachine=$1
   if [ -n "$1" ]; then shift; fi
   if ! [ "$aMachine" = "-" ]; then 
-    state.of $machine add "$@"
+    state.of $aMachine add "$@"
     shift
     RETURN=$1
     return 0
@@ -161,7 +208,7 @@ state.add() # <machine> <stateName> #
   local aMachine=$1
   if [ -n "$1" ]; then shift; fi
   if ! [ "$aMachine" = "-" ]; then 
-    state.of $machine add "$@"
+    state.of $aMachine add "$@"
     shift
     RETURN=$1
     return 0
@@ -172,6 +219,39 @@ state.add() # <machine> <stateName> #
   if [ -n "$1" ]; then shift; fi  
 
   echo add ${stateName}
+  shift
+  RETURN=$1
+}
+
+state.set() # <machine> <stateName> #
+{
+  local aMachine=$1
+  if [ -n "$1" ]; then shift; fi
+  if ! [ "$aMachine" = "-" ]; then 
+    state.of $aMachine set "$@"
+    shift
+    RETURN=$1
+    return 0
+  fi
+
+  
+  local stateValue=$1
+  if [ -n "$1" ]; then shift; fi  
+
+
+
+  info.log set ${stateValue} of $machine
+
+  if state.find $machine ${stateValue}; then
+    state.current
+    info.log set values ${stateValue} = $state = $stateFound 
+    declare -x ${machine}_STATE_ID=${stateFound}
+    private.state.machine.update
+    important.log "Set state of ${machine} to: [${stateFound}] = ${stateValue}"
+  else
+    error.log "not found: $state = $stateFound = $stateResult"
+  fi
+
   shift
   RETURN=$1
 }
@@ -262,31 +342,34 @@ state.machine.init() {
     )' 
   
   declare -x ${machine}_STATE_ID=1 >>$CONFIG_PATH/stateMachines/${machine}.states.env
+  private.state.machine.update
+}
+
+
+private.state.machine.update() {
   {
     declare -a | line find ${machine}_STATES | line replace ' \[' ' \\-SPLIT-[' | line split '-SPLIT-' | line unquote
     local name=${machine}_STATE_ID
     echo
     echo ${name}=${!name}
-  }>$CONFIG_PATH/stateMachines/${machine}.states.env
-  
+  } >$CONFIG_PATH/stateMachines/${machine}.states.env
 }
 
 state.parameter.completion.state() {
   important.log "Par: $@"
   local stateFilter=$1
   if [ -n "$1" ]; then shift; fi  
-  local machine="$STATE_MACHINE_CURRENT"
+  state.current
 
-  debug.log "machine=${machine}    stateFilter=${stateFilter}   1=$1"
+  console.log "machine=${machine}    stateFilter=${stateFilter}   1=$1  stateList=${!stateList}"
 
-  local stateList="${machine}_STATES[@]"
 
   let i=0
   let count=0
   let countInternal=0
   for index in "${!stateList}"; do
     local currentName="${machine}_STATES[$i]"
-    debug.log looping ${currentName}  at $index loop $i
+    console.log looping ${currentName}  at $index loop $i
     if [ "$state" -lt "$i" ] || [ "$stateFilter" = "all" ]; then
       if this.isNumber ${!currentName}; then
         debug.log "skipping ${!currentName}"
@@ -318,8 +401,27 @@ state.parameter.completion.state() {
 state.machine.edit() # <machine> # creates a stateMachine
 {
   local machine=$1
+  if [ -z "$1" ]; then state.current; fi
   oo cmd vim
   vim $CONFIG_PATH/stateMachines/${machine}.states.env
+}
+
+state.edit() # <machine> # creates a stateMachine
+{
+  state.machine.edit "$@"
+}
+
+state.machine.show() # <machine> # creates a stateMachine
+{
+  local machine=$1
+  if [ -z "$1" ]; then state.current; fi
+  oo cmd vim
+  cat $CONFIG_PATH/stateMachines/${machine}.states.env
+}
+
+state.show() # <machine> # creates a stateMachine
+{
+  state.machine.show "$@"
 }
 
 state.machine.delete() # <machine> # creates a stateMachine
