added state add

diff --git a/state b/state
--- a/state
+++ b/state
@@ -21,6 +21,10 @@ state.of() # <machine> <?method> # returns the state of the <machine>
 
   source $CONFIG_PATH/stateMachines/${machine}.states.env
   local state=${!stateID}
+  if [ -z "$state" ]; then
+    warn.log "state not set"
+    state=1
+  fi
   local stateName="${machine}_STATES[${state}]"
   local stateList="${machine}_STATES[@]"
   local stateFile="$CONFIG_PATH/stateMachines/${machine}.states.env"
@@ -110,12 +114,7 @@ state.list.machines() # <?nameFilter> # lists all available stateMachines
 }
 
 state.parameter.completion.method() {
-  echo "list"
-  echo "id"
-  echo "name"
-  echo "add"
-  echo "stage"
-  echo "start"
+  c2 get.functions $OOSH_DIR/state | line find "#[ ]*<machine>" | line replace "^state\." | line replace "().*$" | line filter "machine\." | line filter "of"
 }
 
 state.find() # <machine> <state> #
@@ -140,6 +139,12 @@ state.find() # <machine> <state> #
     if [ -z "$stateValue" ]; then 
       stateFound=0; 
     else 
+      ## TDOD maybe this is a while loop
+      if this.isNumber ${!stateName}; then 
+        important.log "found transition state: ${stateFound} => ${!stateName}"
+        stateFound=${!stateName}
+        stateName="${machine}_STATES[${stateFound}]"
+      fi
       echo ${!stateName}: ${stateFound}
     fi
   else
@@ -183,7 +188,29 @@ state.find() # <machine> <state> #
   return 0
 }
 
-state.stage() # <machine> <stateName> #
+state.stage() # <machine> <state> #
+{
+  local aMachine=$1
+  if [ -n "$1" ]; then shift; fi
+  if ! [ "$aMachine" = "-" ]; then 
+    state.of $aMachine stage "$@"
+    shift
+    RETURN=$1
+    return 0
+  fi
+  
+  local stateName=$1
+  if [ -n "$1" ]; then shift; fi  
+
+  let state++
+  info.log "stage to ${state}"
+  state.set $machine ${state}
+
+  shift
+  RETURN=$1
+}
+
+state.add() # <machine> <newStateName> #
 {
   local aMachine=$1
   if [ -n "$1" ]; then shift; fi
@@ -194,36 +221,60 @@ state.stage() # <machine> <stateName> #
     return 0
   fi
 
-  
-  local stateName=$1
-  if [ -n "$1" ]; then shift; fi  
+  if [ $state -eq 1 ]; then state.stage $machine; fi
+  if [ $state -gt 2 ]; then 
+    error.log "cannot add state!"
+    error.log "state machine not in state: [2] = setup  
+    but is in state: $state
+    "
+    important.log "
+    you could hard reset the machine $machine to state 2 with
 
-  echo stage to ${stateName}
-  shift
-  RETURN=$1
-}
-
-state.add() # <machine> <stateName> #
-{
-  local aMachine=$1
-  if [ -n "$1" ]; then shift; fi
-  if ! [ "$aMachine" = "-" ]; then 
-    state.of $aMachine add "$@"
-    shift
-    RETURN=$1
-    return 0
+    state set $machine 2
+    "
+    return 1
   fi
-
   
-  local stateName=$1
-  if [ -n "$1" ]; then shift; fi  
+  local newStateName=$1
+  if [ -n "$1" ]; then 
+    shift; 
+  else
+    error.log "no ${YELLOW}<newStateName>${RED} provided!"
+    return 1
+  fi  
 
-  echo add ${stateName}
+  echo add ${newStateName}
+  local state=$(state.find $machine next.custom.state)
+  local stateID="${machine}_STATES[${state}]"
+  
+  ## TODO check security
+  eval ${stateID}=${newStateName}
+  
+  if this.isNumber ${newStateName}; then
+    important.log "adding transition state [${state}] => ${newStateName}"
+    state=${newStateName}
+  else
+    let state++
+  fi
+  local stateID="${machine}_STATES[${state}]"
+  if [ -n "${!stateID}" ]; then
+    if [ "${!stateID}" = "99" ]; then
+      eval ${stateID}="next.custom.state"
+    else
+      warn.log "canot overwrite existing state ${stateID}=${!stateID}"
+    fi
+  else 
+    eval ${stateID}="next.custom.state"
+  fi
+  private.state.machine.update
+
+  state.show
+
   shift
   RETURN=$1
 }
 
-state.set() # <machine> <stateName> #
+state.set() # <machine> <state> #
 {
   local aMachine=$1
   if [ -n "$1" ]; then shift; fi
@@ -245,12 +296,17 @@ state.set() # <machine> <stateName> #
   if state.find $machine ${stateValue}; then
     state.current
     info.log set values ${stateValue} = $state = $stateFound 
+    if [ "$stateFound" -lt "$state" ]; then
+      warn.log " State of ${machine} will be hard reset from: [${!stateID}] => [${stateFound}]"
+    fi
     declare -x ${machine}_STATE_ID=${stateFound}
     private.state.machine.update
+    source $CONFIG_PATH/current.state.machine.env
     important.log "Set state of ${machine} to: [${stateFound}] = ${stateValue}"
   else
     error.log "not found: $state = $stateFound = $stateResult"
   fi
+
 
   shift
   RETURN=$1
@@ -349,19 +405,29 @@ state.machine.init() {
 private.state.machine.update() {
   {
     declare -a | line find ${machine}_STATES | line replace ' \[' ' \\-SPLIT-[' | line split '-SPLIT-' | line unquote
-    local name=${machine}_STATE_ID
+    local stateID=${machine}_STATE_ID
+    local state=${!stateID}
+    if [ -z "$state" ]; then
+      error.log "State broken!  reseting to 1"
+      state=1
+    fi
+
     echo
-    echo ${name}=${!name}
+    echo ${stateID}=${state}
   } >$CONFIG_PATH/stateMachines/${machine}.states.env
+  
+  local stateName="${machine}_STATES[${state}]"
+  local stateValue="${!stateName}"
+  private.state.update.current.machine
 }
 
 state.parameter.completion.state() {
-  important.log "Par: $@"
+  debug.log "parameter.completion.state: $@"
   local stateFilter=$1
   if [ -n "$1" ]; then shift; fi  
-  state.current
+  source $CONFIG_PATH/current.state.machine.env
 
-  console.log "machine=${machine}    stateFilter=${stateFilter}   1=$1  stateList=${!stateList}"
+  debug.log "machine=${machine}    stateFilter=${stateFilter}   1=$1  stateList=${!stateList}"
 
 
   let i=0
@@ -369,7 +435,7 @@ state.parameter.completion.state() {
   let countInternal=0
   for index in "${!stateList}"; do
     local currentName="${machine}_STATES[$i]"
-    console.log looping ${currentName}  at $index loop $i
+    debug.log looping ${currentName}  at $index loop $i
     if [ "$state" -lt "$i" ] || [ "$stateFilter" = "all" ]; then
       if this.isNumber ${!currentName}; then
         debug.log "skipping ${!currentName}"
@@ -390,7 +456,7 @@ state.parameter.completion.state() {
 
   echo
   let transitionStates=$countInternal-$count
-  important.log "${machine}_STATES has $count states (and $transitionStates transition states)
+  debug.log "${machine}_STATES has $count states (and $transitionStates transition states)
   
   "
 
@@ -402,6 +468,7 @@ state.machine.edit() # <machine> # creates a stateMachine
 {
   local machine=$1
   if [ -z "$1" ]; then state.current; fi
+  if [ "$1" = "-" ]; then state.current; fi
   oo cmd vim
   vim $CONFIG_PATH/stateMachines/${machine}.states.env
 }
@@ -415,6 +482,7 @@ state.machine.show() # <machine> # creates a stateMachine
 {
   local machine=$1
   if [ -z "$1" ]; then state.current; fi
+  if [ "$1" = "-" ]; then state.current; fi
   oo cmd vim
   cat $CONFIG_PATH/stateMachines/${machine}.states.env
 }
@@ -427,6 +495,10 @@ state.show() # <machine> # creates a stateMachine
 state.machine.delete() # <machine> # creates a stateMachine
 {
   local machine=$1
+  if [ -z "$1" ]; then 
+    error.log "no ${YELLOW}<machine>${RED} provided!"
+    return 1 
+  fi
   oo cmd vim
   rm $CONFIG_PATH/stateMachines/${machine}.states.env
 }
