check state started

diff --git a/state b/state
--- a/state
+++ b/state
@@ -119,86 +119,13 @@ state.parameter.completion.method() {
   c2 get.functions $OOSH_DIR/state | line find "#[ ]*<machine>" | line replace "^state\." | line replace "().*$" | line filter "machine\." | line filter "of"
 }
 
-state.find() # <machine> <state> #
-{
-  local aMachine=$1
-  if [ -n "$1" ]; then shift; fi
-  if ! [ "$aMachine" = "-" ]; then 
-    state.of $aMachine find "$@"
-    shift
-    RETURN=$1
-    return 0
-  else 
-      source $CONFIG_PATH/current.state.machine.env
-  fi
-
-  
-  local stateName=$1
-  if [ -n "$1" ]; then shift; fi  
-
-  if this.isNumber $stateName;then
-    local stateFound=${stateName}
-    local stateName="${machine}_STATES[${stateName}]"
-    stateValue=${!stateName}
-    if [ -z "$stateValue" ]; then 
-      stateFound=0; 
-    else 
-      ## TDOD maybe this is a while loop
-      if this.isNumber ${!stateName}; then 
-        important.log "found transition state: ${stateFound} => ${!stateName}"
-        stateFound=${!stateName}
-        stateName="${machine}_STATES[${stateFound}]"
-      fi
-      echo ${!stateName}: ${stateFound}
-    fi
-  else
-    let i=0
-    let count=0
-    let countInternal=0
-    for index in "${!stateList}"; do
-      local currentName="${machine}_STATES[$i]"
-      debug.log looping ${currentName}  at $index loop $i
-
-        if this.isNumber ${!currentName}; then
-          debug.log "skipping ${!currentName}"
-          local next=${!currentName}
-          i=$next-1
-        else 
-          let count++
-          if [ "${!currentName}" = "$stateName" ]; then
-            echo "$i"
-            stateFound=$i
-            break
-          else
-            stateFound=0
-          fi
-        fi
-      let i++
-      let countInternal++
-    done
-
-  fi
-
-  shift
-  RETURN=$1
-
-
-  if [ $stateFound -eq 0 ]; then
-    error.log "State '$stateName' not found!"
-    return 1
-  fi
-  private.state.update.current.machine
-  debug.log found ${stateName} = $stateFound $stateValue
-  return 0
-}
-
 state.stage() # <machine> <state> #
 {
   local aMachine=$1
   if [ -n "$1" ]; then 
     shift; 
     if ! [ "$aMachine" = "-" ]; then 
-      state.of $aMachine list "$@"
+      state.of $aMachine stage "$@"
       shift
       RETURN=$1
       return 0
@@ -259,7 +186,7 @@ state.next() # <machine> <state> #
     important.log "Going to set state of ${machine} to: [${stateFound}] = ${stateValue}"
     if this.functionExists "$script.check"; then
       console.log   "Going to call:
-      state check - $script.check - ${stateValue} ${script}"
+      state check - ${stateValue} ${script}"
       $script.check - ${stateValue} ${script}
     else
       console.log   "Going to call:
@@ -304,6 +231,21 @@ state.check() # <machine> <state> <script> # checks if the state can be set
       success.log "$RESULT"
       return $(result)
     fi
+
+
+    if this.functionExists "private.check.$stageTo"; then
+      echo calling private.check.$stageTo $script $stageTo $stateFound
+      if private.check.$stageTo state $stageTo $stateFound; then
+        state.set - $stateFound
+        success.log "cool"
+      else
+        error.log "$RESULT"
+      fi
+      return $(return)
+    else
+      echo "private.check.$stageTo not found..."
+    fi
+
     if this.functionExists "$script.check.$stageTo"; then
       echo calling $script.check.$stageTo $script $stageTo $stateFound
       if $script.check.$stageTo $script $stageTo $stateFound; then
@@ -312,15 +254,18 @@ state.check() # <machine> <state> <script> # checks if the state can be set
       else
         error.log "did not go well"
       fi
+      return $(return)
     else
-      echo not found
+      echo "$script.check.$stageTo not found..."
     fi
+
+
   else
     error.log "not found: $state = $stateFound = $stateResult"
   fi
 }
 
-state.check.all.states.added() # must not have parameters # checks if the current machine cans switch to this state
+private.check.all.states.added() # must not have parameters # checks if the current machine cans switch to this state
 {
   source $CONFIG_PATH/current.state.machine.env
 
@@ -335,53 +280,12 @@ state.check.all.states.added() # must not have parameters # checks if the curren
       create.result 0 "machine ${machine} already in state [$stageTo] = ${stateValue}"
       return $(result)
   else
-      
-  let i=0
-  let count=0
-  let countInternal=0
-  for index in "${!stateList}"; do
-    local currentName="${machine}_STATES[$i]"
-    debug.log looping ${currentName}  at $index loop $i
-    if [ "$state" -lt "$i" ] || [ "$stateFilter" = "all" ]; then
-      if this.isNumber ${!currentName}; then
-        debug.log "skipping ${!currentName}"
-        local next=${!currentName}
-        i=$next-1
-      else 
-        let count++
-        local colorMod=""
-        if [ "$i" -eq "${state}" ]; then
-          colorMod=${CYAN}
-        fi
-        #console.log "${colorMod}[$i]\t= ${!currentName}"
-        local name="undefined"
-        if [ $i -lt 6 ]; then
-          name="state.check.${!currentName}"
-          if this.functionExists $name; then
-            debug.log "$function exists"
-          else
-            create.result 1 "at least 1 function does not exist" "$1"
-            error.log "function ${CYAN}$name${RED} is missing in $script"
-          fi
-          
-          # name="private.state.${!currentName}"
-          # if this.functionExists $name; then
-          #   debug.log "$function exists"
-          # else
-          #   create.result 1 "at least 1 function does not exist" "$1"
-          #   error.log "function ${CYAN}$name${RED} is missing in $script"
-          # fi
-        # else
-        #   console.log "$script.check.${!currentName}"
-        fi
 
-      fi
-    fi
-    let i++
-    let countInternal++
-  done
+  private.loop.states \
+    private.itterator.check.all.states.added
 
-  if [ $RETURN_VALUE -ge 1 ]; then
+
+  if [ "$RESULT" = "at least 1 function does not exist" ]; then
     error.log "$RESULT"
     return $(result)
   fi
@@ -414,10 +318,31 @@ state.check.all.states.added() # must not have parameters # checks if the curren
 }
 
 
-state.check.started() {
+private.itterator.check.all.states.added() { # <currentName> <currentValue> <currentID> <stateID> #
+  local currentName=$1
+  if [ -n "$1" ]; then shift; fi  
+  local currentValue=$1
+  if [ -n "$1" ]; then shift; fi  
+  local currentID=$1
+  if [ -n "$1" ]; then shift; fi  
+
+        local name="undefined"
+        if [ $currentID -lt 6 ]; then
+          name="private.check.${currentValue}"
+          if this.functionExists $name; then
+            debug.log "$function exists"
+          else
+            create.result 0 "at least 1 function does not exist" "$1"
+            error.log "function ${CYAN}$name${RED} is missing in $script"
+          fi
+        fi
+
+}
+
+private.check.started() {
     source $CONFIG_PATH/current.state.machine.env
 
-  local script=state
+  local stateScript=$1
   if [ -n "$1" ]; then shift; fi  
   local stateValue=started
   if [ -n "$1" ]; then shift; fi  
@@ -436,46 +361,21 @@ state.check.started() {
         return $(result)
       fi
 
-      let i=0
-      let count=0
-      let countInternal=0
-      for index in "${!stateList}"; do
-        local currentName="${machine}_STATES[$i]"
-        debug.log looping ${currentName}  at $index loop $i
-        if [ "$state" -lt "$i" ] || [ "$stateFilter" = "all" ]; then
-          if this.isNumber ${!currentName}; then
-            debug.log "skipping ${!currentName}"
-            local next=${!currentName}
-            i=$next-1
-          else 
-            let count++
-            local colorMod=""
-            if [ "$i" -eq "${state}" ]; then
-              colorMod=${CYAN}
-            fi
-            #console.log "${colorMod}[$i]\t= ${!currentName}"
-            local name="undefined"
-            if [ $i -gt 10 ]; then
-              name="$stateScript.check.${!currentName}"
-              if this.functionExists $name; then
-                debug.log "$function exists"
-              else
-                create.result 1 "at least 1 function does not exist" "$1"
-                error.log "function ${CYAN}$name${RED} is missing in script: ${CYAN}$script"
-              fi
-              
-            # else
-            #   console.log "$script.check.${!currentName}"
-            fi
+      source $(which $stateScript)
 
-          fi
-        fi
-        let i++
-        let countInternal++
-      done
+      private.loop.states \
+        private.itterator.check.started
 
-      if [ $RETURN_VALUE -ge 1 ]; then
+      if [ "$RESULT" = "at least 1 function does not exist" ]; then
+
         error.log "$RESULT"
+        important.log "to continue, implement the required private.check methods and use
+        
+        state machine.start - ${YELLOW}<stateScript>${CYAN}
+
+        ${GREEN}where ${YELLOW}<stateScript>${GREEN} is the script that implements the private.check methods and handels the transitions 
+        "
+        create.result 1 "please implement the functions listed above in script: $stateScript"
         return $(result)
       fi
 
@@ -490,6 +390,166 @@ state.check.started() {
   return $(result)
 
 }
+
+private.itterator.check.started() { # <currentName> <currentValue> <currentID> <stateID> #
+  local currentName=$1
+  if [ -n "$1" ]; then shift; fi  
+  local currentValue=$1
+  if [ -n "$1" ]; then shift; fi  
+  local currentID=$1
+  if [ -n "$1" ]; then shift; fi  
+
+            local name="undefined"
+            info.log "private.itterator.check.started: $currentID"
+            if [ $currentID -gt 10 ]; then
+              name="private.check.${currentValue}"
+              if this.functionExists $name; then
+                debug.log "$function exists"
+              else
+                create.result 0 "at least 1 function does not exist" "$1"
+                error.log "function ${CYAN}$name${RED} is missing in script: ${CYAN}$script"
+              fi
+              
+            # else
+            #   console.log "$script.check.${!currentName}"
+            fi
+
+}
+
+state.machine.start() # <machine> <script> # checks if the state can be set
+{
+  local aMachine=$1
+  if [ -n "$1" ]; then 
+    shift; 
+    if ! [ "$aMachine" = "-" ]; then 
+      state.of $aMachine machine.start "$@"
+      shift
+      RETURN=$1
+      return 0
+    else 
+        source $CONFIG_PATH/current.state.machine.env
+    fi
+  else
+    source $CONFIG_PATH/current.state.machine.env
+  fi
+
+  local script=$1
+  if [ -n "$1" ]; then shift; fi  
+
+  if private.check.started $script; then
+    state.set - 4
+  else
+    error.log "could not start machine $machine: \n$RESULT"
+  fi
+}
+
+private.loop.states() # <iteratorFunction> # itterates all states and calls on each the itterator function. stops the iterration on non-null return value 
+{
+  local itteratorFunction=$1
+  if [ -n "$1" ]; then shift; fi
+
+
+  let i=0
+  let count=0
+  let countInternal=0
+  for index in "${!stateList}"; do
+    local currentName="${machine}_STATES[$i]"
+    debug.log looping ${currentName}  at $index loop $i
+    if [ "$state" -lt "$i" ] || [ "$stateFilter" = "all" ]; then
+      if this.isNumber ${!currentName}; then
+        debug.log "skipping ${!currentName}"
+        local next=${!currentName}
+        i=$next-1
+      else 
+        let count++
+        local colorMod=""
+        # if [ "$i" -eq "${state}" ]; then
+        #   colorMod=${CYAN}
+        # fi
+        $itteratorFunction $currentName ${!currentName} $i "$@"
+        #console.log "${colorMod}[$i]\t= ${!currentName}"
+      fi
+    fi
+    let i++
+    let countInternal++
+  done
+}
+
+
+state.find() # <machine> <state> #
+{
+  local aMachine=$1
+  if [ -n "$1" ]; then shift; fi
+  if ! [ "$aMachine" = "-" ]; then 
+    state.of $aMachine find "$@"
+    shift
+    RETURN=$1
+    return 0
+  else 
+      source $CONFIG_PATH/current.state.machine.env
+  fi
+
+  
+  local stateName=$1
+  if [ -n "$1" ]; then shift; fi  
+
+  if this.isNumber $stateName;then
+    local stateFound=${stateName}
+    local stateName="${machine}_STATES[${stateName}]"
+    stateValue=${!stateName}
+    if [ -z "$stateValue" ]; then 
+      stateFound=0; 
+    else 
+      ## TDOD maybe this is a while loop
+      if this.isNumber ${!stateName}; then 
+        important.log "found transition state: ${stateFound} => ${!stateName}"
+        stateFound=${!stateName}
+        stateName="${machine}_STATES[${stateFound}]"
+      fi
+      echo ${!stateName}: ${stateFound}
+    fi
+  else
+
+    private.loop.states \
+      private.itterator.find
+    
+    stateFound="$RESULT"
+  fi
+
+  shift
+  RETURN=$1
+  
+
+  if [ $stateFound -eq 0 ]; then
+    error.log "State '$stateName' not found!"
+    return 1
+  fi
+
+  private.state.update.current.machine
+  debug.log found ${stateName} = $stateFound $stateValue
+  return 0
+}
+
+private.itterator.find() {  # <currentName> <currentValue> <currentID> <rest> #
+  local currentName=$1
+  if [ -n "$1" ]; then shift; fi  
+  local currentValue=$1
+  if [ -n "$1" ]; then shift; fi  
+  local currentID=$1
+  if [ -n "$1" ]; then shift; fi  
+
+  if [ "${!currentName}" = "$stateName" ]; then
+    echo "$currentID"
+    stateFound=$currentID
+    create.result 1 "$stateFound" 
+    return $(result)
+  else
+    stateFound=0
+  fi
+  return 0
+}
+
+
 
 
 state.add() # <machine> <newStateName> <print> #
@@ -531,9 +591,12 @@ state.add() # <machine> <newStateName> <print> #
   fi  
 
   local print=$1
-  if [ -n "$1" ]; then shift; fi  
+  if [ -n "$print" ]; then 
+    shift; 
+    echo going to $print
+  fi  
 
-  echo add ${newStateName}
+  echo add ${newStateName} "--- $@ --- $print"
   local state=$(state.find $machine next.custom.state)
   local stateID="${machine}_STATES[${state}]"
   
@@ -565,6 +628,7 @@ state.add() # <machine> <newStateName> <print> #
   if [ -n "$print" ]; then
     state.show
   fi
+
 
   shift
   RETURN=$1
@@ -646,29 +710,8 @@ state.list() # <machine> <stateName> #
 
   local stateList="${machine}_STATES[@]"
 
-  let i=0
-  let count=0
-  let countInternal=0
-  for index in "${!stateList}"; do
-    local currentName="${machine}_STATES[$i]"
-    debug.log looping ${currentName}  at $index loop $i
-    if [ "$state" -lt "$i" ] || [ "$stateFilter" = "all" ]; then
-      if this.isNumber ${!currentName}; then
-        debug.log "skipping ${!currentName}"
-        local next=${!currentName}
-        i=$next-1
-      else 
-        let count++
-        local colorMod=""
-        if [ "$i" -eq "${state}" ]; then
-          colorMod=${CYAN}
-        fi
-        console.log "${colorMod}[$i]\t= ${!currentName}"
-      fi
-    fi
-    let i++
-    let countInternal++
-  done
+    private.loop.states \
+      private.itterator.list
 
   echo
   let transitionStates=$countInternal-$count
@@ -679,6 +722,21 @@ state.list() # <machine> <stateName> #
   shift
   RETURN=$1
 }
+
+private.itterator.list() { # <currentName> <currentValue> <currentID> <stateID> #
+  local currentName=$1
+  if [ -n "$1" ]; then shift; fi  
+  local currentValue=$1
+  if [ -n "$1" ]; then shift; fi  
+  local currentID=$1
+  if [ -n "$1" ]; then shift; fi  
+
+    if [ "$currentID" -eq "${state}" ]; then
+      colorMod=${CYAN}
+    fi
+    console.log "${colorMod}[$currentID]\t= ${currentValue}"
+}
+
 
 state.machine.exists() # <machine> # creates a stateMachine
 {
@@ -749,30 +807,8 @@ state.parameter.completion.state() {
 
   debug.log "machine=${machine}    stateFilter=${stateFilter}   1=$1  stateList=${!stateList}"
 
-
-  let i=0
-  let count=0
-  let countInternal=0
-  for index in "${!stateList}"; do
-    local currentName="${machine}_STATES[$i]"
-    debug.log looping ${currentName}  at $index loop $i
-    if [ "$state" -lt "$i" ] || [ "$stateFilter" = "all" ]; then
-      if this.isNumber ${!currentName}; then
-        debug.log "skipping ${!currentName}"
-        local next=${!currentName}
-        i=$next-1
-      else 
-        let count++
-        local colorMod=""
-        if [ "$i" -eq "${state}" ]; then
-          colorMod=${CYAN}
-        fi
-        echo "${!currentName}"
-      fi
-    fi
-    let i++
-    let countInternal++
-  done
+  private.loop.states \
+  private.itterator.completion.state
 
   echo
   let transitionStates=$countInternal-$count
@@ -782,6 +818,17 @@ state.parameter.completion.state() {
 
   shift
   RETURN=$1
+}
+
+private.itterator.completion.state() { # <currentName> <currentValue> <currentID> <stateID> #
+  local currentName=$1
+  if [ -n "$1" ]; then shift; fi  
+  local currentValue=$1
+  if [ -n "$1" ]; then shift; fi  
+  local currentID=$1
+  if [ -n "$1" ]; then shift; fi  
+
+  echo "${currentValue}"
 }
 
 state.machine.edit() # <machine> # creates a stateMachine
