fixed reconfigure and setup nvm

diff --git a/this b/this
--- a/this
+++ b/this
@@ -640,13 +640,17 @@ this.start() {
       echo "local install mode"
       ;;
     restart)
-      echo "restarting $BASH_FILE"
+      if [ -z "$BASH_FILE" ]; then
+        export BASH_FILE="$(which bash)"
+      fi
+      echo "restarting $BASH_FILE: $RETURN_VALUE = $ERROR_CODE_RECONFIG"
 
-      export SHELL=$BASH_FILES
-      $BASH_FILE #-x # force debug
-      RETURN_VALUE=$?
+
       if [ "$RETURN_VALUE" -eq "$ERROR_CODE_RECONFIG" ]; then
-        this.restart again
+        export SHELL=$BASH_FILE
+        $BASH_FILE #-x # force debug
+        RETURN_VALUE=$?
+        #      this.restart again
       else
         echo "finally exiting oosh"
       fi
