fixed path configes and added r,c,v aliasees

diff --git a/this b/this
--- a/this
+++ b/this
@@ -127,7 +127,9 @@ this.init() {
   if [ -n "$CONFIG" ]; then
     info.log "inititlized"
     if [ -f "$CONFIG" ]; then
-      source "$CONFIG"
+      if ! (this.isSourced); then
+        source "$CONFIG"
+      fi
     fi
     return 0
   fi
@@ -182,7 +184,7 @@ this.init() {
   fi
 }
 
-create.result() # <processRETURN_VALUE:0> <RESULT:all went well> <option:$1> # creates a process return value and a function RESULT that bcen be returned in the calling function
+create.result() # <processRETURN_VALUE:0> <RESULT:all went well> <option:$1> # creates a process return value and a function RESULT that been be returned in the calling function
 # to make create result work, you have to call a SOURCED function
 # e.g.  if os.check some.function; then ...
 #   if you call 'os check' from th scrip 'os', it cannot return a RESULT since the porcess will end and no RESULT is left...
@@ -248,6 +250,18 @@ result.save()
   {
     declare -px | grep "RESULT"
   } >$CONFIG_PATH/result.env
+}
+
+result.cat() { # # logs the $CONFIG_PATH/result.env file
+  cat $CONFIG_PATH/result.env
+}
+
+result.show() { # # alias to result.cat
+  result.cat
+}
+
+result.view() { # # alias to result.cat
+  result.cat
 }
 
 result.load()
@@ -467,7 +481,8 @@ this.path.add() {
   #   loop.list PATH rm $1 silent
   #   debug.log "PATH=$1:$RESULT"
   # fi
-  export PATH="$1:$RESULT"
+
+  #export PATH="$1:$RESULT"
 }
 
 
