fix the mv error mv: cannot stat '/root/*.public_key': No such file or directory

diff --git a/this b/this
--- a/this
+++ b/this
@@ -381,7 +381,7 @@ this.call() {
         debug.log "done this.call: $aShellScript.$aFunction $*"
         #$aShellScript.$aFunction "$@"
       else
-        problem.log "this.load faild to load $aShellScript from \"$aFunction\""
+        problem.log "this.load faild to load $aShellScript from \"$aFunction\": $?"
         return 127
       fi
     fi
