checked in v2 and moved others to old

diff --git a/old/debug b/old/debug
--- a/old/debug
+++ b/old/debug
@@ -1,11 +1,14 @@
 #!/bin/bash
 
-# echo "entering: ${BASH_SOURCE[0]}"
-# echo "remove all echos to preseve output"
-# echo ""
+#export PS4='\033[90m+${LINENO} in ${current}: \033[0m'
+current=${BASH_SOURCE[0]}
 
-source init
-this.load log.checkDebug log
+debug.version()              # prints out the hard coded version tag of $This 
+{
+ console.log "$0 debug version: 20210626 20:45"
+}
+
+
 
 function step()
 {
@@ -14,7 +17,7 @@ function step()
       set +x
   } 2>/dev/null
 
-    #info.log "step on level $LOG_LEVEL"
+    echo step on level $LOG_LEVEL
     if [ -z "$LOG_LEVEL" ]; then
         LOG_LEVEL=5
         export PS4='\033[90m+${LINENO} in ${#BASH_SOURCE[@]}>${FUNCNAME[0]}:${BASH_SOURCE[@]##*/} \033[0m'
@@ -57,19 +60,25 @@ function step()
             step
             ;;
         s)
-            log.checkDebug 1
+            removeTrap
+            DEBUG=OFF
+            debug.log "DEBUG is OFF"
+            set +x
             ;;
         n)
-            log.checkDebug 6
-            echo "ENTER: continue"
-            export STEP_DEBUG=ON
-            return 0
+            #removeTrap
+            DEBUG=ON
+            set -x
             ;;
         x)
-            log.checkDebug 6
+            DEBUG=ON
+            removeTrap
+            set -x
             ;;
         c)
-            log.checkDebug 5
+            DEBUG=ON
+            removeTrap
+            set +x
             ;;
         e)
             echo "> expands to: $(eval echo "$BASH_COMMAND")"
@@ -135,19 +144,24 @@ function step()
             step
             ;;          
         *)
+            set +x
             warn.log "FORCE EXIT because of command: $CONT"
             exit 0
       esac
-    else
-      echo "ENTER: continue"
-      export STEP_DEBUG=ON
-      return 0
+    #else
+      #echo "ENTER: continue"
     fi
   #else
     #echo "Step Debug is $STEP_DEBUG"
   fi
  
-  log.checkDebug
+  if [ "$LOG_LEVEL" -gt "4" ]; then
+    set -x
+  else
+    { 
+      set +x
+    } 2>/dev/null
+  fi
     
 }
 
@@ -164,13 +178,106 @@ function stackTrace() {
             step
 }
 
+function stepDebugger() {
+
+  if [ "$1" = "OFF" ]; then
+      removeTrap
+  fi
+  if [ "$1" = "ON" ]; then
+      export STEP_DEBUG=ON
+  fi
+
+}
+
+function setTrap() {
+  #echo "trap DEBUG set to step"
+
+  #export PS4='\033[90m+${LINENO}: '
+
+  trap step DEBUG
+  #set -e
+  trap 'onError ${?}' ERR
+  trap 'onReturn ${?}' RETURN
+  trap 'onExit  ${?}' EXIT 
+}
+
+function checkTrace() {
+    case $- in
+        *x* ) 
+            echo "Trace is ON"
+            export TRACE=ON
+            ;;
+        * )               
+            echo "Trace is OFF"
+            export TRACE=OFF;
+            ;;
+    esac
+}
+
+function setTrace() {
+    case $TRACE in
+        ON ) 
+            set -x
+            export TRACE=ON
+            ;;
+        * )               
+            set +x
+            export TRACE=OFF
+            ;;
+    esac
+}
+
+
+function removeTrap() {
+  export STEP_DEBUG=OFF
+  #trap - DEBUG ERR RETURN EXIT
+}
+
+function ckeckDebug() {
+    setTrap
+
+    source log
+
+#   if [[ "$(basename -- "$0")" == "debug" ]]; then
+#     # called
+#     if [ -n "$1" ]; then
+#         export DEBUG=$1
+#         config save
+#     fi
+#     warn.log "debug has no effect if it was not sourced with . debug"
+#   else
+#     # sourced
+#     debug.log "debug was sourced from: $0"
+#     if [[ "$(basename -- "$0")" == "-bash" ]]; then
+#        debug.log "sourced from: bash"
+#        DEBUG=$1
+#     fi
+#   fi
+
+
+#   if [ -n "$DEBUG" ]; then
+#     #echo "DEBUG was $DEBUG, and is now ON"
+#     case $DEBUG in
+#       X)
+#         set -x
+#         ;;
+#       OFF)
+#         unset DBEUG
+#         ;;
+#       *)
+#         export DEBUG=ON
+#     esac
+#   #else
+#     #echo "DEBUG is $DEBUG"
+#   fi
+}
+
 function toggleDebug() {
-    if [ "$LOG_LEVEL" -gt "4" ]; then
-      log.checkDebug 3
-      export STEP_DEBUG=OFF
+    if [ "ON" = "$DEBUG" ]; then 
+        DEBUG=OFF
+        #set +x
     else
-      log.checkDebug 5
-      export STEP_DEBUG=OFF
+        DEBUG=ON
     fi
     warn.log "Toggeld DEBUG to $DEBUG"
 }
@@ -200,7 +307,7 @@ function onError() {
     return
   fi
 
-    error.log         "function ${FUNCNAME[1]} in line: ${BASH_LINENO[2]} from ${BASH_SOURCE[2]} returned with ERROR code: $1"
+    error.log         "function ${FUNCNAME[1]} in line: ${BASH_LINENO[2]} returned with ERROR code: $1"
     if [ "ON" = "$DEBUG" ]; then
       export STEP_DEBUG=
       stackTrace
@@ -212,17 +319,59 @@ function onExit() {
   debug.log "exiting"
 }
 
-
-function setTrap() {
-  #echo "trap DEBUG set to step"
-
-  #export PS4='\033[90m+${LINENO}: '
-
-  trap step DEBUG
-  #set -e
-  trap 'onError ${?}' ERR
-  trap 'onReturn ${?}' RETURN
-  trap 'onExit  ${?}' EXIT 
+debug.log() {
+    if [ "$LOG_LEVEL" -gt "3" ]; then
+        #test -t 1 && tput setf 7     
+        echo -e "\033[1;36m- $@\033[0m"
+        #echo "- $@"
+        #test -t 1 && tput sgr0 # Reset terminal
+    fi
 }
 
-setTrap
+console.log() {
+    #test -t 1 && tput bold; tput setf 7                                            ## white bold
+    if [ "$LOG_LEVEL" -gt "2" ]; then
+        echo -e "\033[0m>  $@"
+    fi
+    #test -t 1 && tput sgr0 # Reset terminal
+}
+error.log() {
+    err.log "$@"
+}
+err.log() {
+    #test -t 1 && tput bold; tput setf 4  
+    #echo "ERROR>  $@"
+    echo -e "\033[1;31mERROR> $@\033[0m"    
+    #test -t 1 && tput sgr0 # Reset terminal
+    if [ "ON" = "$DEBUG" ]; then 
+        export STEP_DEBUG=ON
+    fi   
+}
+warn.log() {
+    #test -t 1 && tput bold; tput setf 6
+    if [ "$LOG_LEVEL" -gt "1" ]; then
+        echo -e "\033[1;33m> WARNING $@\033[0m"                                    ## yellow
+    fi
+    #test -t 1 && tput sgr0 # Reset terminal
+}
+stop.log() {
+    if [ "$LOG_LEVEL" -gt "4" ]; then
+        #test -t 1 && tput bold; tput setf 6                                    ## green
+        #echo "BREAKPOINT> $@"
+        echo -e "\033[1;32mBREAKPOINT> $@\033[0m" 
+        #test -t 1 && tput sgr0 # Reset terminal
+        export STEP_DEBUG=ON
+    fi  
+}
+success.log() {
+    #if [ "ON" = "$DEBUG" ]; then 
+    if [ "$LOG_LEVEL" -gt "1" ]; then
+        echo -e "\033[1;32mSUCCESS> $@\033[0m" 
+    fi
+    #fi  
+}
+
+ckeckDebug "$@"
+
+#`debug.version
+#setTrap
